Repository okteto/okteto, pull requests merged in 2020-03, with the labels that each got.

#730 Remove OKTETO_TOKEN
  .circleci/config.yml
  integration/integration_test.go
  pkg/analytics/analytics_test.go
  pkg/okteto/auth.go
  pkg/okteto/auth_test.go
Labels: no-dco

#732 Copy using io.Copy instead of os.Rename
  cmd/dependencies.go
  cmd/progress.go
  cmd/up.go
  pkg/model/utils.go
  pkg/model/utils_test.go
  pkg/ssh/config.go
  pkg/syncthing/install.go
Labels: no-dco

#738 build with golang 1.14
  .circleci/config.yml
  contributing.md
  go.mod
Labels: no-dco

#744 use the current user for SSH
  pkg/cmd/login/browser.go
  pkg/config/config.go
  pkg/k8s/deployments/translate.go
  pkg/model/dev.go
  pkg/model/translation_test.go
  pkg/ssh/client.go
  pkg/ssh/exec.go
  pkg/ssh/reverse.go
  pkg/ssh/reverse_test.go
Labels: no-dco

#746 Pin the downloaded version in the homebrew formula
  update_homebrew_formula.sh
Labels: no-dco

#757 Add scope badge
  README.md
  integration/integration_test.go
Labels: no-dco

#758 Add install instructions to readme
  README.md
Labels: invalid, no-dco

#773 move SSH file atomically
  cmd/up.go
  pkg/ssh/config.go
  pkg/ssh/ssh.go
Labels: no-dco

#774 Generate ssh key
  cmd/dependencies.go
  cmd/up.go
  cmd/version.go
  pkg/k8s/secrets/crud.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/ssh/client.go
  pkg/ssh/config.go
  pkg/ssh/exec.go
  pkg/ssh/key.go
  pkg/ssh/key_test.go
  pkg/ssh/manager.go
  pkg/ssh/ssh.go
Labels: no-dco

#780 installer: test writable install directory
  scripts/get-okteto.sh
Labels: new-contributor

#788 Add azure auth provider
  go.sum
  main.go
Labels: new-contributor

#786 check for null before dereferencing
  pkg/k8s/volumes/crud.go
Labels: new-contributor, no-dco

#790 update to scope 0.1.15
  go.mod
  go.sum
Labels: no-dco
