Repository okteto/okteto, pull requests merged in 2020-04, with the labels that each got.

#800 Install syncthing 1.4.2
  pkg/k8s/deployments/translate.go
  pkg/syncthing/install.go
Labels: no-dco

#821 Stop scope agent after CLI span is finished
  main.go
Labels: new-contributor

#831 fix python example link in Readme
  README.md
Labels: new-contributor, no-dco

#848 forward the SSH_AUTH_SOCK in Go client
  pkg/ssh/exec.go
Labels: new-contributor
