Repository okteto/okteto, pull requests merged in 2020-08, with the labels that each got.

#994 add missing ctx to integration test
  integration/integration_test.go
Labels: invalid

#990 log quota error
  pkg/k8s/deployments/crud.go
Labels: no-dco

#1000 Remove dead code
  pkg/okteto/client.go
  pkg/okteto/credential.go
Labels: invalid

#1002 Support for dynamic okteto bin image tag
  Makefile
  cmd/up/up.go
  images/bin/Dockerfile
  images/bin/Makefile
  pkg/k8s/deployments/translate.go
  pkg/k8s/deployments/translate_test.go
  pkg/model/dev.go
  pkg/model/translation.go
  pkg/model/translation_test.go
Labels: no-dco

#1003 Fix .stignore path
  cmd/init/init.go
  cmd/init/init_test.go
Labels: no-dco

#1005 Default to persistent volumes
  cmd/init/init.go
  pkg/k8s/deployments/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: no-dco

#1001 upgrade to syncthing 1.8.0
  images/bin/Dockerfile
  images/bin/Makefile
  pkg/k8s/secrets/configXML.go
  pkg/model/dev.go
  pkg/syncthing/configXML.go
  pkg/syncthing/install.go
Labels: no-dco

#1006 Support for synchronizing several folders
  cmd/init/init_test.go
  cmd/up/up.go
  cmd/utils/dev_test.go
  images/bin/Makefile
  images/bin/start.sh
  okteto.yml
  pkg/cmd/status/run.go
  pkg/k8s/deployments/translate_test.go
  pkg/k8s/deployments/utils_test.go
  pkg/k8s/pods/pod.go
  pkg/k8s/secrets/configXML.go
  pkg/linguist/dev.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/translation_test.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
  pkg/okteto/client.go
  pkg/okteto/client_test.go
  pkg/syncthing/configXML.go
  pkg/syncthing/monitor.go
  pkg/syncthing/syncthing.go
Labels: no-dco

#1015 Remove context from kubeconfig on `okteto namespace delete`
  cmd/namespace/delete.go
  cmd/namespace/namespace.go
  pkg/okteto/client.go
  pkg/okteto/client_test.go
Labels: new-contributor
