Repository okteto/okteto, pull requests merged in 2020-06, with the labels that each got.

#890 share namespace
  cmd/namespace/create.go
  cmd/namespace/delete.go
  cmd/namespace/namespace.go
  pkg/okteto/client.go
  pkg/okteto/namespace.go
  pkg/okteto/namespace_test.go
Labels: no-dco

#895 block operations only if on dev env pod
  cmd/doctor.go
  cmd/status.go
  cmd/up.go
  pkg/errors/errors.go
  pkg/okteto/client.go
  pkg/okteto/client_test.go
Labels: no-dco

#894 add more info in the output when authentication fails
  pkg/okteto/auth.go
Labels: no-dco

#889 move okteto/bin and okteto/okteto to the cli repo
  .dockerignore
  Dockerfile
  images/bin/Dockerfile
  images/bin/start.sh
  okteto.yml
Labels: no-dco

#896 fail early if requirements are not fulfilled
  cmd/up.go
  pkg/model/dev.go
  pkg/model/translation_test.go
  pkg/okteto/client.go
  pkg/ssh/manager.go
  pkg/ssh/manager_test.go
Labels: no-dco

#885 Option to increase the timeouts
  cmd/down.go
  cmd/up.go
  main.go
  pkg/config/config.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/pods/pod.go
  pkg/k8s/volumes/crud.go
  pkg/log/log.go
  pkg/syncthing/syncthing.go
Labels: no-dco

#899 Set replicas to 1 on push
  cmd/push.go
  cmd/up.go
  pkg/cmd/down/run.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/services/translate.go
  pkg/model/dev.go
Labels: no-dco

#908 change condition check for unbound volume claim
  pkg/k8s/pods/pod.go
Labels: invalid, no-dco

#913 Add CI job to build dockerfile on release
  .circleci/config.yml
  Dockerfile
Labels: invalid, no-dco

#915 Fix docker build
  .circleci/config.yml
Labels: invalid

#922 Return clean on failure
  cmd/up.go
  cmd/utils/watches.go
  pkg/k8s/pods/pod.go
  pkg/syncthing/syncthing.go
Labels: no-dco

#923 add more logs to the integration logs and store them in the CI job
  .circleci/config.yml
  cmd/down.go
  integration/integration_test.go
  integration/stacks_test.go
  pkg/k8s/deployments/translate.go
Labels: invalid, no-dco

#941 Support remote for non root containers
  cmd/up.go
  images/bin/start.sh
  pkg/k8s/deployments/translate.go
  pkg/k8s/deployments/translate_test.go
  pkg/k8s/pods/pod.go
  pkg/model/dev.go
Labels: no-dco

#956 Check storageclass for generating okteto manifests
  cmd/init/init.go
  pkg/k8s/labels/labels.go
Labels: no-dco

#959 small typo in message
  cmd/init/init.go
  cmd/status.go
  cmd/up/up.go
  pkg/cmd/init/run.go
Labels: no-dco
