Repository okteto/okteto, pull requests merged in 2021-11, with the labels that each got.

#1914 update context help
  cmd/context/context.go
  cmd/context/use.go
  main.go
Labels: no-dco

#1915 update the "how it works" doc
  docs/how-does-it-work.md
  docs/okteto-architecture.png
Labels: no-dco

#1929 Youngestdev/stack progress display
  cmd/stack/deploy.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/translate.go
Labels: no-dco, new-contributor

#1938 fingerprint updated
  .circleci/config.yml
Labels: no-dco

#1939 fix compat issue with Okteto Enterprise
  pkg/okteto/secrets.go
Labels: no-dco

#1944 feat: add support for multi line env files
  go.mod
  go.sum
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: bug, new-contributor, go, feature, dependencies

#1883 Merge kubeconfig files for config
  cmd/context/update-kubeconfig.go
  integration/k8s-client.go
  pkg/config/config.go
  pkg/errors/errors.go
  pkg/k8s/kubeconfig/client.go
  pkg/k8s/kubeconfig/client_test.go
Labels: no-dco

#1866 Add stack endpoints
  cmd/stack/deploy.go
  cmd/stack/endpoints.go
  cmd/stack/stack.go
  pkg/cmd/stack/endpoints.go
  pkg/okteto/stack.go
Labels: no-dco

#1958 Revert pipeline skipifexists okteto global
  cmd/build.go
  cmd/pipeline/deploy.go
  pkg/cmd/build/build.go
  pkg/cmd/stack/translate.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
Labels: no-dco

#1967 Solves #1966. Disable HTTP/2 when a SPDY request is detected in the okteto deploy proxy
  cmd/deploy/deploy.go
  pkg/k8s/namespaces/namespace.go
Labels: no-dco

#1940 script to rollback actions
  rollback_actions.sh
Labels: no-dco

#1975 Jdm/stack healthcheck marshaling
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
Labels: no-dco

#1979 add make BuildArgs map in dockerBuildOptions
  pkg/cmd/build/build_docker.go
Labels: new-contributor

#1957 Improved error message for invalid sync path
  cmd/up/stignore.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: no-dco

#1997 add new contributors
  README.md
Labels: no-dco

#1999 add command to generate fig descriptor
  go.mod
  go.sum
  main.go
Labels: no-dco

#2000 Use https://contrib.rocks to keep track of contributors
  README.md
Labels: no-dco
