Repository okteto/okteto, pull requests merged in 2021-04, with the labels that each got.

#1364 chore: fix spelling
  pkg/cmd/stack/translate_test.go
  pkg/errors/errors.go
  pkg/k8s/labels/labels.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/stack_test.go
  pkg/registry/registry.go
  pkg/syncthing/syncthing.go
Labels: no-dco

#1372 add a parameter to accept RSA keys in the ssh config
  .circleci/config.yml
  pkg/ssh/config.go
  pkg/ssh/ssh.go
Labels: no-dco

#1371 define the timeout in the manifest
  cmd/down.go
  cmd/stack/destroy.go
  cmd/up/activate.go
  pkg/cmd/stack/destroy.go
  pkg/config/config.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/pods/pod.go
  pkg/k8s/volumes/crud.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/ssh/pool.go
  pkg/syncthing/syncthing.go
Labels: no-dco

#1402 feat(CI): add a GitHub Action to check for merge conflicts
  .github/workflows/lint.yml
Labels: invalid

#1410 Fix linter issues in bash scripts
  .github/pull_request_template.md
  images/bin/start.sh
  scripts/get-okteto.sh
  scripts/windows.sh
Labels: no-dco

#1403 Add pre-commit and the GitHub Super Linter
  .deepsource.toml
  .dockerignore
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/linter.yml
  .gitignore
  .pre-commit-config.yaml
  .typo-ci.yml
  .vscode/tasks.json
  Makefile
  README.md
  code-of-conduct.md
  contributing.md
  images/bin/Dockerfile
  super-linter.report/.keep
  update_homebrew_formula.sh
Labels: no-dco

#1422 moar linting issues
  .github/pull_request_template.md
  .github/workflows/superlinter.yml
  images/bin/start.sh
  scripts/get-okteto.sh
  scripts/windows.sh
Labels: no-dco

#1445 use deploy key for the release
  .circleci/config.yml
Labels: no-dco

#1434 Jlopezbarb/stack add volumes support
  cmd/utils/stack.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/k8s/labels/labels.go
  pkg/k8s/volumes/crud.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
Labels: no-dco

#1459 List namspaces
  cmd/list.go
  cmd/namespace/list.go
  main.go
  pkg/okteto/namespace.go
Labels: new-contributor
