Repository okteto/okteto, pull requests merged in 2021-03, with the labels that each got.

#1299 Fallback when we fail to get the name
  go.mod
  go.sum
  pkg/syncthing/syncthing.go
Labels: no-dco

#1303 Add jLopezbarb to the maintainers list
  CODEOWNERS
Labels: no-dco

#1302 Refactor dev.Namespace and dev.Context initialization in a single place
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/init/init.go
  cmd/init/init_test.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/push.go
  cmd/restart.go
  cmd/status.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  integration/integration_test.go
  pkg/cmd/init/run.go
  pkg/cmd/stack/translate.go
  pkg/k8s/client/client.go
  pkg/k8s/client/retry.go
  pkg/model/dev.go
  pkg/registry/registry.go
Labels: no-dco

#1309 Retry registry/buildkit transient errors
  pkg/analytics/analytics.go
  pkg/cmd/build/build.go
  pkg/registry/registry.go
Labels: no-dco

#1311 Refresh k8s credentials on "connection refused" error
  pkg/k8s/client/client.go
  pkg/k8s/client/retry.go
Labels: invalid, no-dco

#1300 Add init container declaration
  cmd/init/init_test.go
  cmd/up/up.go
  images/bin/Dockerfile
  images/bin/Makefile
  pkg/k8s/deployments/translate.go
  pkg/model/dev.go
  pkg/model/translation.go
  pkg/model/translation_test.go
Labels: no-dco

#1322 Jlopezbarb/split config healthchecks
  pkg/k8s/deployments/translate.go
  pkg/model/dev.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/translation.go
  pkg/model/translation_test.go
  pkg/model/volumes.go
Labels: no-dco

#1324 chore: remove whitespace, fix JSON, spelling, grammar, link and end o…
  .DEREK.yml
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/release-bin.yml
  .vscode/tasks.json
  Makefile
  README.md
  cmd/up/upgrade.go
  code-of-conduct.md
  contributing.md
  docs/how-does-it-work.md
  images/bin/start.sh
  integration/integration_test.go
  pkg/cmd/login/html.go
  scripts/get-okteto.sh
  update_homebrew_formula.sh
Labels: new-contributor

#1331 chore: fix spelling
  cmd/init/init_test.go
  cmd/pipeline/deploy.go
  cmd/up/up.go
  cmd/utils/retry.go
  cmd/utils/stack.go
Labels: invalid

#1332 Jlopezbarb/fix split error on up
  cmd/up/up.go
Labels: no-dco

#1327 Jlopezbarb/split config healthchecks
  pkg/k8s/deployments/translate.go
  pkg/k8s/labels/labels_test.go
  pkg/model/dev.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/translation.go
  pkg/model/translation_test.go
  pkg/model/volumes.go
Labels: no-dco

#1334 consider "deployed" when waiting for the pipeline
  cmd/pipeline/deploy.go
Labels: no-dco

#1345 remove mock-release from PRs
  .circleci/config.yml
Labels: no-dco

#1344 Allow users to override serviceAccountName
  pkg/k8s/deployments/translate.go
  pkg/k8s/deployments/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/translation.go
Labels: new-contributor, no-dco

#1351 generate ed25519 keys for SSH access
  cmd/exec.go
  cmd/up/up.go
  go.mod
  go.sum
  pkg/k8s/deployments/translate_test.go
  pkg/model/dev.go
  pkg/model/translation_test.go
  pkg/ssh/client.go
  pkg/ssh/key.go
  pkg/ssh/key_test.go
  pkg/ssh/ssh.go
Labels: no-dco

#1356 Revert "generate ed25519 keys for SSH access (#1351)"
  cmd/exec.go
  cmd/up/up.go
  pkg/k8s/deployments/translate_test.go
  pkg/model/dev.go
  pkg/model/translation_test.go
  pkg/ssh/client.go
  pkg/ssh/key.go
  pkg/ssh/key_test.go
  pkg/ssh/ssh.go
Labels: no-dco

#1363 Remove trailing whitespace
  .circleci/config.yml
Labels: invalid
