Repository okteto/okteto, pull requests merged in 2021-09, with the labels that each got.

#1733 Upgrading dependencies.
  go.mod
  go.sum
Labels: no-dco

#1734 Upgrade to Golang 1.17
  .circleci/config.yml
  go.mod
Labels: invalid

#1659 Jlopezbarb/autoupdate actions e2e
  .circleci/config.yml
  cmd/pipeline/deploy.go
  cmd/up/syncthing.go
  cmd/utils/dev.go
  integration/actions_test.go
  integration/integration_test.go
  pkg/okteto/pipeline.go
  update_actions.sh
Labels: no-dco

#1745 Fail CI if go.sum changes
  .circleci/config.yml
  go.sum
Labels: invalid, no-dco, new-contributor

#1753 Show build error to the user when retrying
  pkg/cmd/build/build.go
Labels: no-dco

#1761 Fix wrong init container added for jobs without volumes
  pkg/cmd/build/build.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: no-dco

#1764 Add functionality to set runAsNonRoot to disable securityContext defaults
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/translation_test.go
Labels: new-contributor

#1783 Remove several methods from App interface
  cmd/analytics.go
  cmd/down.go
  cmd/init/init.go
  cmd/push.go
  cmd/up/activate.go
  cmd/up/types.go
  cmd/up/up.go
  pkg/analytics/analytics.go
  pkg/cmd/down/run.go
  pkg/cmd/stack/deploy.go
  pkg/k8s/apps/crud.go
  pkg/k8s/apps/deployments.go
  pkg/k8s/apps/interface.go
  pkg/k8s/apps/statefulsets.go
  pkg/k8s/apps/translate.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/statefulsets/crud.go
Labels: no-dco

#1780 Jlopezbarb/fix divert and test e2e
  cmd/down.go
  cmd/up/up.go
  integration/integration_test.go
  pkg/k8s/apps/deployments.go
  pkg/k8s/apps/interface.go
  pkg/k8s/apps/statefulsets.go
  pkg/k8s/diverts/crud.go
  pkg/k8s/diverts/translate.go
Labels: no-dco

#1793 Increase tests timeout
  .circleci/config.yml
  Makefile
Labels: no-dco
