Repository okteto/okteto, pull requests merged in 2021-05, with the labels that each got.

#1469 new contributors
  README.md
Labels: no-dco

#1472 fingerprint updated
  .circleci/config.yml
Labels: new-contributor, no-dco

#1475 update deps to buildkit 0.8.3
  go.mod
  go.sum
Labels: no-dco

#1462 Added support for variables on pipeline deploy command
  cmd/pipeline/deploy.go
  pkg/okteto/client.go
  pkg/okteto/pipeline.go
Labels: new-contributor, no-dco

#1494 Upgrade ingress API from extensions to networking
  images/bin/start.sh
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/k8s/ingress/crud.go
  pkg/k8s/ingress/crud_test.go
  pkg/k8s/ingresses/crud.go
  pkg/k8s/ingresses/crud_test.go
  scripts/get-okteto.sh
  update_homebrew_formula.sh
Labels: no-dco

#1507 Set stack name to repository name if exists
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/stack/deploy.go
  cmd/utils/git.go
Labels: no-dco

#1495 Add more pre-commit hooks
  .circleci/config.yml
  .deepsource.toml
  .github/dependabot.yml
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/lint.yml
  .github/workflows/release-bin.yml
  .github/workflows/superlinter.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/tasks.json
  cmd/config/view/username.go
  cmd/config/view/view.go
  cmd/create.go
  cmd/delete.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/init/init.go
  cmd/list.go
  cmd/login.go
  cmd/namespace/create.go
  cmd/namespace/delete.go
  cmd/namespace/list.go
  cmd/namespace/namespace.go
  cmd/push.go
  cmd/restart.go
  cmd/stack/deploy.go
  cmd/status.go
  cmd/up/up.go
  cmd/utils/retry.go
  cmd/utils/stack.go
  cmd/utils/syncthing.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/down/run.go
  pkg/cmd/init/run.go
  pkg/cmd/login/login.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/status/run.go
  pkg/config/config.go
  pkg/errors/errors.go
  pkg/k8s/client/client.go
  pkg/k8s/labels/labels.go
  pkg/k8s/namespaces/crud.go
  pkg/k8s/secrets/crud.go
  pkg/k8s/services/crud.go
  pkg/k8s/volumes/crud.go
  pkg/model/dev.go
  pkg/model/stack.go
  pkg/model/translation.go
  pkg/model/utils.go
  pkg/okteto/credential.go
  pkg/registry/file.go
  pkg/registry/image.go
  pkg/registry/registry.go
  pkg/syncthing/api.go
Labels: no-dco

#1513 Update translate_test.go to fix typo
  pkg/cmd/stack/translate_test.go
Labels: no-dco

#1508 Jlopezbarb/set stack name to repo if not defined
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/stack/deploy.go
  cmd/utils/git.go
  pkg/model/stack.go
  pkg/model/utils.go
Labels: no-dco

#1517 Support for dind sidecard
  pkg/k8s/deployments/translate.go
  pkg/k8s/deployments/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/translation.go
  pkg/model/translation_test.go
Labels: invalid, no-dco

#1512 Update release-bin to use the new action
  .github/workflows/release-bin.yml
Labels: no-dco

#1520 Fix redeploy stack
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/translate.go
Labels: no-dco

#1516 Remove deprecated mountPath and subPath fields in the okteto manifest
  cmd/up/exec.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: invalid

#1519 Jlopezbarb/fix permission error on volume mount
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: no-dco

#1544 Fix windows tests
  pkg/k8s/deployments/translate.go
Labels: invalid

#1582 Check if file does not exist to init data from volume
  pkg/k8s/deployments/translate.go
  pkg/k8s/deployments/translate_test.go
Labels: invalid
