Repository okteto/okteto, pull requests merged in 2022-08, with the labels that each got.

#2956 fix: panic on non existen svc
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
Labels: release/bug-fix

#2955 fix: volumes not being deleted
  cmd/deploy/proxy.go
  cmd/deploy/proxy_test.go
Labels: release/bug-fix

#2978 fix: use a different random seed generator
  main.go
Labels: release/bug-fix

#2902 feat: ResourceEphemeralStorage
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
Labels: new-contributor, keep, release/new-feature

#2979 fix: check if resources been destroyed after destroy command
  integration/commands/deploy.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  integration/deploy/helm_test.go
  integration/deploy/k8s_manifest_test.go
  integration/deploy/manifest_test.go
  integration/deploy/pipeline_test.go
Labels: release/bug-fix

#2981 docs: pull request scope
  docs/code-review.md
Labels: no-dco, release/internal

#2971 Fix spelling
  docs/how-to-run-tests.md
Labels: release/internal

#2943 fix: redeploy service with different name
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/k8s/services/crud.go
Labels: release/bug-fix

#2989 fix: redeploy tests e2e
  integration/commands/stacks.go
  integration/deploy/compose_test.go
  pkg/cmd/stack/deploy.go
Labels: release/bug-fix

#2992 Handle bad equal quantity
  cmd/deploy/deploy.go
  cmd/deploy/validate.go
  cmd/deploy/validate_test.go
Labels: no-dco, release/internal

#2997 fix: if image is set, we should return the image
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
Labels: release/bug-fix, backport release-2.5

#2986 Jlopezbarb/link how to tests from contribution guide
  docs/code-review.md
  docs/how-to-run-tests.md
Labels: release/internal

#2998 Update help message for deploy command
  cmd/deploy/deploy.go
  cmd/pipeline/pipeline.go
Labels: release/internal

#2994 Fix race conditions at unit tests
  Makefile
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/deploy/wait.go
  cmd/destroy/destroy.go
  cmd/down.go
  cmd/exec.go
  cmd/manifest/init-v1.go
  cmd/manifest/init-v2.go
  cmd/manifest/selector.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/preview/deploy.go
  cmd/push.go
  cmd/restart.go
  cmd/status.go
  cmd/up/activate.go
  cmd/up/dependencies.go
  cmd/up/forwards.go
  cmd/up/syncthing.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/utils/git.go
  cmd/utils/spinner.go
  cmd/utils/stack.go
  go.mod
  go.sum
  pkg/cmd/init/run.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/destroy_test.go
  pkg/cmd/status/run.go
  pkg/log/log.go
  pkg/log/spinner.go
  pkg/log/tty.go
  pkg/model/const.go
  pkg/registry/file.go
Labels: release/internal

#3004 Fix resolve previous tags in release-branch
  scripts/ci/release-branch.sh
Labels: no-dco, release/internal, backport release-2.5

#3002 fix: add error message deploying compose
  cmd/deploy/deploy.go
  integration/okteto/deploy_test.go
Labels: no-dco, release/bug-fix

#2952 golang-ci-lint-fixes
  cmd/context/utils.go
  pkg/cmd/stack/translate.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
  pkg/okteto/client.go
Labels: no-dco, release/internal, enhancement

#3008 fix context checking when no manifest found
  cmd/context/utils.go
  cmd/context/utils_test.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  pkg/discovery/contextresource_test.go
  pkg/errors/errors.go
  pkg/model/manifest.go
Labels: release/bug-fix

#3016 Upgrade go to 1.18
  .circleci/config.yml
  Dockerfile
  contributing.md
  go.mod
  go.sum
Labels: new-contributor, release/internal

#3023 Add PreUpdate hook to newSpinner
  pkg/log/log.go
  pkg/log/spinner.go
Labels: release/bug-fix, backport release-2.6

#2996 Add okteto context to dockerfile build args
  cmd/build/v2/build.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/model/dev.go
Labels: new-contributor, release/new-feature

#3027 added link to blog for using okteto cli with vanilla clusters
  README.md
Labels: release/internal

#3028 fix: delete te wrong folder
  cmd/context/delete_test.go
Labels: release/bug-fix

#3021 fix: show warning msg when sanitize dev
  cmd/up/up.go
  pkg/cmd/stack/deploy.go
  pkg/model/manifest.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: no-dco, release/bug-fix

#3040 Log syncthing api error before return
  pkg/syncthing/api.go
  pkg/syncthing/syncthing.go
Labels: release/internal

#3032 fix: warn when a secret is being overridden by local-env
  cmd/context/use.go
Labels: release/bug-fix

#3033 Fix dev selector typo
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/exec_test.go
  cmd/push.go
  cmd/restart.go
  cmd/status.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
Labels: release/bug-fix

#3034 Refactor selector
  cmd/context/list.go
  cmd/context/selector.go
  cmd/context/use.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/manifest/init-v2.go
  cmd/manifest/selector.go
  cmd/namespace/use.go
  cmd/push.go
  cmd/restart.go
  cmd/status.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  cmd/utils/selector.go
  pkg/okteto/context.go
Labels: release/internal

#3036 Audit workflows
  .DEREK.yml
  .codecov.yml
  .deepsource.toml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .github/workflows/lint.yml
  .github/workflows/superlinter.yml
  .golangci.yml
  .mdlrc
  .pre-commit-config.yaml
  .typo-ci.yml
  .yaml-lint.yml
  Makefile
  codespell.txt
  contributing.md
  docs/how-does-it-work.md
  scripts/ci/pre-commit/sort-codespell-wordlist.sh
  super-linter.report/.keep
Labels: release/internal
