Repository okteto/okteto, pull requests merged in 2022-03, with the labels that each got.

#2304 Discard reverse port if collision detected
  pkg/cmd/init/run.go
  pkg/cmd/init/run_test.go
  pkg/okteto/context_test.go
Labels: no-dco, new-contributor

#2340 feat: tty without collapsing
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/stack/deploy.go
  cmd/utils/displayer/collapse_tty.go
  cmd/utils/displayer/tty.go
  cmd/utils/executor/executor.go
  pkg/log/plain.go
Labels: no-dco

#2319 Metrics Fixes
  cmd/deploy/deploy.go
  cmd/up/up.go
  pkg/analytics/track.go
  pkg/config/config.go
  pkg/model/const.go
  pkg/okteto/context.go
  pkg/okteto/pipeline.go
  pkg/okteto/preview.go
Labels: no-dco

#2349 BUG: Added identitiesOnly key to SSH configuration
  pkg/ssh/config.go
  pkg/ssh/ssh.go
Labels: new-contributor

#2350 Update links to docs v2
  README.md
  cmd/context/create.go
  cmd/context/update-kubeconfig.go
  cmd/context/use-namespace.go
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/login.go
  cmd/namespace/namespace.go
  cmd/namespace/use.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/pipeline/pipeline.go
  cmd/push.go
  cmd/stack/destroy.go
  cmd/stack/stack.go
  pkg/cmd/login/login.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
Labels: no-dco

#2383 fix: add deploy flag to support compose file
  pkg/model/manifest.go
Labels: no-dco

#2357 fix manifest init
  cmd/context/utils.go
  cmd/init.go
  cmd/manifest/init-v1.go
  cmd/manifest/init-v1_test.go
  cmd/manifest/init-v2.go
  cmd/manifest/selector.go
  cmd/up/stignore.go
  cmd/up/up.go
  cmd/utils/dev.go
  main.go
  pkg/cmd/init/run.go
  pkg/k8s/apps/crud.go
  pkg/linguist/dev.go
  pkg/model/dev.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/registry/registry.go
Labels: no-dco

#2415 Update info messages about global registry
  cmd/build.go
  cmd/deploy/deploy.go
Labels: no-dco, invalid
