Repository okteto/okteto, pull requests merged in 2022-01, with the labels that each got.

#2093 Add context improvement
  cmd/context/context.go
  cmd/context/create.go
Labels: stale

#2088 autocreate fail if app with the same name exists
  cmd/up/activate.go
Labels: stale

#2121 update stale.yml
  .github/workflows/stale.yml
Labels: no-dco, invalid

#2136 fix: use "go test -c" at "make build-integration"
  Makefile
Labels: bug

#2044 Youngestdev/compose env
  cmd/stack/deploy.go
  cmd/stack/deploy_test.go
  pkg/model/const.go
Labels: no-dco
