Repository okteto/okteto, pull requests merged in 2022-04, with the labels that each got.

#2398 add json/yaml outputs for okteto ctx list
  cmd/context/list.go
  main.go
  pkg/okteto/context.go
Labels: no-dco

#2484 Remove DinD sidecard support
  cmd/up/activate.go
  cmd/up/exec.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/devrc.go
  pkg/model/translation.go
  pkg/model/translation_test.go
Labels: no-dco

#2400 test: add tests checking deploy output
  integration/deploy_manifest_test.go
  integration/utils_test.go
Labels: stale

#2527 Update okteto logo in login static page
  pkg/cmd/login/html.go
Labels: no-dco

#2526 Build with context
  cmd/build.go
  pkg/cmd/build/build.go
  pkg/model/manifest.go
Labels: no-dco

#2539 fix: syncthing was killing parent process
  integration/up_test.go
  pkg/syncthing/syncthing.go
Labels: no-dco

#2563 Fix #2505. Fix okteto deploy command within other okteto deploy execution
  cmd/deploy/deploy.go
  cmd/deploy/proxy.go
  cmd/destroy/destroy.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  integration/deploy_test.go
Labels: no-dco

#2570 fix: use 'okteto.dev' registry when image tagging to avoid authorizat…
  pkg/cmd/stack/translate.go
Labels: new-contributor

#2503 refactor: build command
  cmd/build.go
  cmd/build/builder.go
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v1/build.go
  cmd/build/v1/build_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/environment.go
  cmd/build/v2/environment_test.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/destroy.go
  cmd/manifest/init-v2.go
  cmd/push.go
  cmd/up/activate.go
  cmd/up/up.go
  integration/build_test.go
  integration/deploy_manifest_test.go
  integration/stacks_test.go
  internal/test/build.go
  main.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_docker.go
  pkg/cmd/build/build_test.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/errors/errors.go
  pkg/model/dev.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/stack.go
  pkg/registry/file.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/types/build.go
Labels: no-dco

#2578 feat: add support envvars when okteto up
  cmd/up/up.go
  cmd/up/up_test.go
  pkg/errors/errors.go
Labels: new-contributor
