Repository okteto/okteto, pull requests merged in 2022-02, with the labels that each got.

#2223 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: no-dco

#2230 add docker stage target to buildkit dockerBuildOptions.Target
  pkg/cmd/build/build_docker.go
Labels: new-contributor

#2216 Hide secrets and deploy vars in output
  cmd/context/use.go
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  pkg/log/log.go
  pkg/log/log_test.go
Labels: no-dco

#2245 refactor: fix pipeline opts.Branchs check
  cmd/pipeline/deploy.go
  pkg/okteto/pipeline.go
Labels: invalid

#2267 deprecate stack in favour of deploy
  cmd/stack/deploy.go
  cmd/stack/destroy.go
  cmd/stack/endpoints.go
  cmd/stack/stack.go
  main.go
Labels: no-dco

#2240 updating the contributing doc
  CODE_OF_CONDUCT.md
  contributing.md
Labels: no-dco

#2287 Review messages and help info
  cmd/deploy/deploy.go
  cmd/preview/deploy.go
  cmd/up/stignore.go
  cmd/up/up.go
  cmd/utils/dev.go
  pkg/model/dev.go
Labels: no-dco
