Repository okteto/okteto, pull requests merged in 2022-11, with the labels that each got.

#3199 Code cleanup in pkg/okteto/context.go
  pkg/okteto/context.go
Labels: release/internal

#3192 Make AskYesNo function support default answers
  cmd/manifest/init-v2.go
  cmd/up/stignore.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  cmd/utils/okteto.go
Labels: new-contributor, release/new-feature

#3198 Fix divert at scale
  pkg/errors/errors.go
  pkg/k8s/diverts/divert.go
  pkg/k8s/diverts/translate.go
  pkg/k8s/diverts/translate_test.go
  pkg/model/const.go
Labels: release/bug-fix, echoes/effort: M, echoes/intent: fix

#3193 Fix error logging crash on context load failure
  cmd/up/up.go
Labels: new-contributor, release/bug-fix

#3207 Hold "okteto up" if the cluster is scaling up
  cmd/up/activate.go
Labels: release/new-feature, echoes/effort: M, echoes/intent: grow

#3208 Upload static files on pushes to master
  .circleci/config.yml
Labels: no-dco, release/internal, echoes/intent: fix

#3206 Remove "github.com/ibuildthecloud/finalizers" as dependency
  go.mod
  go.sum
  pkg/k8s/namespaces/namespace.go
Labels: release/internal

#3202 Jlopezbarb/syncthing removing console instead of okteto process e2e
  cmd/up/forwards.go
  cmd/up/pid.go
  cmd/up/pid_test.go
  cmd/up/types.go
  cmd/up/up.go
  go.mod
  go.sum
  pkg/syncthing/syncthing.go
Labels: release/bug-fix, echoes/intent: fix

#3219 Changes to print error message in main.go when the error is returned by the command executed and avoid duplicated messages
  cmd/deploy/deploy.go
  cmd/pipeline/deploy.go
  cmd/preview/deploy.go
  main.go
  pkg/log/json.go
  pkg/log/log.go
Labels: release/bug-fix, echoes/intent: fix

#3222 Fix clone http
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
Labels: release/bug-fix, echoes/intent: fix

#3225 Revert "Changes to print error message in main.go when the error is returned by the command executed and avoid duplicated messages"
  cmd/deploy/deploy.go
  cmd/pipeline/deploy.go
  cmd/preview/deploy.go
  main.go
  pkg/log/json.go
  pkg/log/log.go
Labels: no-dco, release/internal, echoes/intent: fix

#3227 Add errors related to EOF to our retry logic
  pkg/errors/errors.go
Labels: release/bug-fix, echoes/intent: fix

#2120 Add logs command
  cmd/logs/logs.go
  cmd/logs/stern.go
  go.mod
  go.sum
  main.go
  pkg/analytics/track.go
Labels: release/new-feature, echoes/intent: grow

#3230 Empty cfgmap repository if not valid repo schema
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  pkg/cmd/pipeline/translate.go
Labels: release/bug-fix, echoes/intent: fix

#3216 Documentation grammar fixes
  cmd/utils/args.go
  pkg/discovery/contextresource.go
  pkg/k8s/apps/crud.go
Labels: release/internal

#3239 Revert "update init container logs (#3127)"
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: release/internal, echoes/intent: fix

#3224 fix: private ingress annotations
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/bug-fix, echoes/intent: fix

#3245 Check last stage instead of last line in the output tests to know if the log has finished
  integration/okteto/deploy_test.go
Labels: release/internal, echoes/intent: run

#3244 fix: show info if context is initialized by env vars
  cmd/context/options.go
  cmd/context/use.go
Labels: release/new-feature, echoes/intent: grow

#3214 Sanitize name for deploy and destroy name
  cmd/build/v2/services.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/proxy.go
  cmd/destroy/destroy.go
  cmd/logs/stern.go
  pkg/cmd/build/build.go
  pkg/cmd/pipeline/crud.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/format/format.go
  pkg/format/format_test.go
  pkg/k8s/diverts/translate.go
  pkg/k8s/ingresses/translate.go
  pkg/k8s/ingresses/translate_test.go
Labels: release/bug-fix, echoes/initiative: git-catalog

#3246 fix: e2e test
  cmd/context/use.go
Labels: release/bug-fix, echoes/intent: fix

#3252 Added ExportCache to build options
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.10

#3255 Made changes for better readability
  cmd/utils/dev.go
Labels: release/internal

#3251 feat: add dependencies stage
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
Labels: release/new-feature, echoes/intent: grow
