Repository okteto/okteto, pull requests merged in 2022-12, with the labels that each got.

#3258 Include 'destroy-error' status as a failure in WaitForActionToFinish function. This was provoking that if the pipeline fails, we don't indicate the error in the CLI
  pkg/okteto/action.go
Labels: release/bug-fix, echoes/intent: fix

#3261 Fix inline export when image tag and cache tag are the same
  pkg/cmd/build/buildkit.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.10

#3195 Add namespace for ctxOptions in UseContext() method
  cmd/context/create.go
  pkg/k8s/namespaces/namespace.go
Labels: release/bug-fix, echoes/intent: fix

#3271 Create a single divert CRD and modify ingress on the client side
  .github/workflows/lint.yml
  cmd/deploy/deploy.go
  pkg/cmd/stack/deploy.go
  pkg/k8s/diverts/divert.go
  pkg/k8s/diverts/translate.go
  pkg/k8s/diverts/translate_test.go
  pkg/model/const.go
  pkg/textblock/doc.go
  pkg/textblock/error.go
  pkg/textblock/textblock.go
  pkg/textblock/textblock_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow, backport release-2.10

#3264 Fix infer name for "okteto logs"
  cmd/logs/logs.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.10

#3275 Set "Ingress.Value" to properly initialize the HeaderID based on the …
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/divert.go
  pkg/cmd/stack/divert_test.go
  pkg/k8s/diverts/divert.go
  pkg/k8s/diverts/translate.go
  pkg/k8s/diverts/translate_test.go
  pkg/k8s/ingresses/crud.go
  pkg/k8s/ingresses/crud_test.go
  pkg/model/const.go
Labels: release/bug-fix, echoes/intent: fix

#3279 Don't apply divert transformation if old service was autocreate/headless
  pkg/cmd/stack/divert.go
  pkg/cmd/stack/divert_test.go
Labels: release/bug-fix, echoes/intent: fix

#3285 Ignore concurrent errors when setting divert
  pkg/k8s/diverts/divert.go
Labels: release/bug-fix, echoes/intent: fix

#3259 Jlopezbarb/fix last updated not being updated
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/pipeline/translate_test.go
  pkg/model/const.go
Labels: bug, release/bug-fix, echoes/intent: fix

#3263 Fix sanitize name for stacks
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/kubeconfig.go
  cmd/pipeline/deploy.go
  cmd/utils/manifest.go
  integration/commands/deploy.go
  integration/deploy/helm_test.go
  integration/okteto/deploy_test.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/endpoints.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/constants/constants.go
  pkg/k8s/ingresses/translate_test.go
  pkg/k8s/pods/pod.go
  pkg/model/manifest.go
  pkg/model/stack.go
  pkg/model/utils.go
  pkg/model/utils_test.go
Labels: release/bug-fix, echoes/intent: fix, echoes/initiative: git-catalog, backport release-2.10

#3248 feat: add namespace to dependencies
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/preview/deploy.go
  integration/actions/pipeline_test.go
  integration/okteto/dependencies_test.go
  internal/test/client/pipeline.go
  pkg/model/manifest.go
  pkg/okteto/action.go
  pkg/okteto/pipeline.go
  pkg/types/gitdeploy.go
  pkg/types/interface.go
Labels: release/new-feature, echoes/intent: grow

#3288 Refactor divert weaver implementation
  cmd/deploy/deploy.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/divert.go
  pkg/cmd/stack/divert_test.go
  pkg/divert/driver.go
  pkg/divert/weaver/cache.go
  pkg/divert/weaver/cache_test.go
  pkg/divert/weaver/crd.go
  pkg/divert/weaver/crd_test.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/divert_test.go
  pkg/divert/weaver/endpoints.go
  pkg/divert/weaver/endpoints_test.go
  pkg/divert/weaver/ingresses.go
  pkg/divert/weaver/ingresses_test.go
  pkg/divert/weaver/services.go
  pkg/divert/weaver/services_test.go
  pkg/k8s/diverts/client.go
  pkg/k8s/diverts/divert.go
  pkg/k8s/diverts/translate.go
  pkg/k8s/diverts/translate_test.go
Labels: release/internal, echoes/intent: run

#3297 update file permission for bin image
  cmd/up/stignore.go
  integration/up/autocreate_test.go
  pkg/model/dev.go
Labels: release/bug-fix, echoes/intent: fix

#3299 Default to watch for logs
  cmd/logs/logs.go
  cmd/logs/stern.go
Labels: release/bug-fix, echoes/intent: fix

#3249 Log stream refactor
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/pipeline/destroy.go
  cmd/pipeline/destroy_test.go
  cmd/preview/deploy.go
  cmd/preview/deploy_test.go
  internal/test/client/okteto_client.go
  internal/test/client/pipeline.go
  internal/test/client/stream.go
  pkg/okteto/action.go
  pkg/okteto/client.go
  pkg/okteto/pipeline.go
  pkg/okteto/stream.go
  pkg/stream/stream.go
  pkg/types/interface.go
Labels: release/internal, echoes/intent: grow

#3298 add external resource parsing
  cmd/context/utils_test.go
  pkg/externalresource/external_resource.go
  pkg/externalresource/external_resource_test.go
  pkg/externalresource/serializer.go
  pkg/externalresource/serializer_test.go
  pkg/model/manifest.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: no-dco, release/internal, echoes/intent: grow

#3304 Fix endpoints name in compose
  integration/deploy/endpoints_test.go
  pkg/k8s/ingresses/translate.go
  pkg/model/stack.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.10

#3301 Okteto namespace delete use destroy all job
  cmd/destroy/destroy.go
  cmd/namespace/delete.go
  cmd/namespace/delete_test.go
  cmd/namespace/errors.go
  cmd/namespace/namespace.go
  internal/test/client/namespace.go
  pkg/errors/errors.go
  pkg/okteto/namespace.go
Labels: release/internal, echoes/intent: grow

#3309 remove temporarily failing test
  integration/up/autocreate_test.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3312 Remove force param from delete mutation
  pkg/okteto/namespace.go
Labels: release/internal, echoes/intent: run

#3303 add deploy external resource with okteto deploy cmd
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/pipeline/translate_test.go
  pkg/constants/constants.go
  pkg/externalresource/control.go
  pkg/externalresource/control_test.go
  pkg/externalresource/external_resource.go
  pkg/externalresource/external_resource_test.go
  pkg/externalresource/k8s/client.go
  pkg/externalresource/k8s/fake/fake_external_resource.go
  pkg/externalresource/k8s/fake/fake_external_resource_client.go
  pkg/externalresource/k8s/interface.go
  pkg/externalresource/k8s/types.go
  pkg/externalresource/serializer.go
  pkg/externalresource/serializer_test.go
  pkg/k8s/apps/crud.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/model/stack.go
Labels: no-dco, release/internal, echoes/intent: grow

#3315 refactor: use client provider instead of get client
  cmd/namespace/delete.go
  cmd/namespace/delete_test.go
  cmd/namespace/namespace.go
Labels: release/bug-fix, echoes/intent: fix

#3316 fix e2e when call deploy from up cmd e2e
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3314 feat: add external endpoints when retrieving endpoints
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  pkg/externalresource/control.go
  pkg/externalresource/control_test.go
  pkg/externalresource/k8s/fake/fake_external_resource.go
  pkg/externalresource/k8s/fake/fake_external_resource_client.go
  pkg/externalresource/k8s/interface.go
Labels: release/new-feature, echoes/intent: grow
