Repository okteto/okteto, pull requests merged in 2022-06, with the labels that each got.

#2727 Release Channels
  .circleci/config.yml
  .github/release.yml
  .github/workflows/required-labels.yml
  .pre-commit-config.yaml
  .prettierignore
  cmd/utils/upgrade.go
  scripts/ci/push-image.sh
  scripts/ci/release-branch.sh
  scripts/ci/release.sh
  scripts/get-okteto-beta.sh
  scripts/get-okteto.sh
Labels: no-dco, release/internal

#2760 use default temp dir in tests
  pkg/k8s/apps/translate_test.go
  pkg/model/dev_test.go
Labels: no-dco, release/internal

#2743 Release docs
  .prettierignore
  docs/RELEASE.md
  docs/release-labels.png
Labels: no-dco, release/internal

#2769 use OKTETO_VERSION in get-okteto.sh if provided
  README.md
  cmd/utils/upgrade.go
  docs/RELEASE.md
  docs/how-to-install-okteto-cli.md
  scripts/get-okteto-beta.sh
  scripts/get-okteto.sh
Labels: no-dco, release/internal

#2776 Update bad link to installation guide
  README.md
Labels: no-dco, invalid, release/internal

#2777 Replace imageref in Okteto Registry by their sha to enforce redeploym…
  pkg/cmd/stack/deploy.go
  pkg/registry/client.go
  pkg/registry/registry.go
Labels: release/bug-fix

#2763 test: use `T.TempDir` to create temporary test directory
  cmd/build/v1/build_test.go
  cmd/build/v2/build_test.go
  cmd/context/context_test.go
  cmd/manifest/init-v1_test.go
  cmd/pipeline/deploy_test.go
  cmd/utils/git_test.go
  cmd/utils/stack_test.go
  integration/actions_test.go
  pkg/analytics/config_test.go
  pkg/analytics/track_test.go
  pkg/config/config_test.go
  pkg/linguist/linguist_test.go
  pkg/model/dev_test.go
  pkg/model/utils.go
  pkg/model/utils_test.go
  pkg/ssh/config_test.go
  pkg/ssh/key_test.go
  pkg/ssh/ssh_test.go
  pkg/syncthing/syncthing_test.go
Labels: release/internal

#2781 fix: could not detect manifest error
  cmd/build/command.go
  cmd/build/command_test.go
  go.mod
  go.sum
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/stack.go
Labels: release/bug-fix

#2782 fix: integration tests
  .circleci/config.yml
Labels: release/internal

#2780 Release Improvements
  .circleci/config.yml
  scripts/ci/push-image.sh
  scripts/ci/release.sh
Labels: no-dco, release/internal

#2779 Run e2e tests in staging
  .circleci/config.yml
  integration/actions_test.go
  integration/auto-wake_test.go
  integration/build_test.go
  integration/deploy_manifest_test.go
  integration/deploy_test.go
  integration/push_test.go
  integration/stacks_test.go
  integration/up_test.go
Labels: release/internal

#2787 update release.sh
  scripts/ci/release.sh
Labels: no-dco, release/internal

#2796 [2.4] Release fixes
  .circleci/config.yml
  scripts/ci/push-image.sh
  scripts/ci/release.sh
Labels: no-dco, release/internal

#2802 Update build retry conditions
  pkg/registry/errors.go
Labels: release/bug-fix

#2800 Automatically backport Pull Requests
  .DEREK.yml
  .github/workflows/backport.yml
Labels: no-dco, release/internal

#2806 Run release after pushing the docker image
  .circleci/config.yml
Labels: no-dco, release/internal, backport release-2.4

#2808 fix: compose flag on okteto up (#2804)
  pkg/model/dev.go
  pkg/model/translation_test.go
Labels: release/bug-fix

#2764 creating manifest if deploy fails
  cmd/build/v1/build.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/errors/errors.go
Labels: no-dco, release/bug-fix

#2818 Use seconds instead of miliseconds to build the test name for the autowake, this is a quick fix to fix the tests
  integration/auto-wake_test.go
Labels: release/internal

#2784 Run windows tests in staging
  .circleci/config.yml
Labels: release/internal

#2817 Fix condition to force autocreate
  cmd/up/up.go
Labels: release/bug-fix

#2771 feat: support global forwarding
  cmd/up/activate.go
  cmd/up/forwards.go
  cmd/up/forwards_test.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/up/up_test.go
  integration/up_test.go
  pkg/cmd/doctor/run.go
  pkg/cmd/init/run.go
  pkg/cmd/init/run_test.go
  pkg/cmd/stack/deploy.go
  pkg/errors/errors.go
  pkg/k8s/forward/manager.go
  pkg/k8s/forward/manager_test.go
  pkg/linguist/dev.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/devrc.go
  pkg/model/forward/forward.go
  pkg/model/forward/forward_serializer.go
  pkg/model/forward/forward_serializer_test.go
  pkg/model/forward/forward_test.go
  pkg/model/forward/global_forward.go
  pkg/model/forward/global_forward_serializer.go
  pkg/model/forward/global_forward_serializer_test.go
  pkg/model/forward/global_forward_test.go
  pkg/model/manifest.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/ssh/manager.go
  pkg/ssh/manager_test.go
Labels: release/new-feature

#2831 Added prefix to ignore at remote .stignore
  cmd/up/stignore.go
  cmd/up/stignore_test.go
Labels: release/bug-fix, backport release-2.4

#2836 Rephrase "managed by Okteto" with "Okteto installed"
  cmd/build/v2/build.go
  cmd/build/v2/services.go
  cmd/deploy/deploy.go
  pkg/errors/errors.go
Labels: release/internal

#2707 Mario/build context default
  cmd/manifest/init-v1_test.go
  cmd/up/up.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
Labels: no-dco, release/bug-fix

#2838 Update .DEREK.yml
  .DEREK.yml
Labels: no-dco, invalid, release/internal, backport release-2.4

#2833 Github Actions Release
  .circleci/config.yml
  scripts/ci/release-github-actions.sh
  scripts/set_latest_actions.sh
  scripts/update_actions.sh
Labels: no-dco, release/internal

#2840 [Backport release-2.4] Github actions release (#2833)
  .circleci/config.yml
  scripts/ci/release-github-actions.sh
  scripts/set_latest_actions.sh
  scripts/update_actions.sh
Labels: no-dco, release/internal

#2845 use main branch for github actions
  integration/actions_test.go
Labels: no-dco, release/internal

#2844 fix: remove parallel test when writing in map
  cmd/up/forwards_test.go
Labels: release/bug-fix

#2842 added file closure to delete it with windows
  pkg/cmd/build/build_test.go
Labels: no-dco, release/bug-fix

#2850 use master branch from movies
  .circleci/config.yml
  integration/actions_test.go
Labels: no-dco, invalid, release/internal

#2862 Handle jobs "completed" status properly for the "--wait" flag
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/preview/deploy.go
  integration/actions_test.go
  pkg/okteto/namespace.go
Labels: release/bug-fix, backport release-2.4
