Repository okteto/okteto, pull requests merged in 2022-10, with the labels that each got.

#3139 Inject OKTETO_TOKEN in okteto deploy
  cmd/deploy/command_configuration.go
  pkg/model/const.go
Labels: release/new-feature

#3125 If insecure-skip-tls-verify set in context, don't put certificate-authority-data in temporal kubeconfig
  cmd/deploy/kubeconfig.go
Labels: release/new-feature

#3144 Add "okteto@" as a prefix in OKTETO_BUILD_XXX_SHA
  cmd/build/v2/build_test.go
  cmd/build/v2/environment.go
  cmd/build/v2/environment_test.go
  pkg/model/manifest.go
Labels: release/bug-fix

#3142 added error status when destroying to the manifest
  cmd/destroy/cfghandler.go
  cmd/destroy/destroy.go
Labels: no-dco, release/bug-fix

#3153 Removing the docker version pin for setup_remote_docker in ci.
  .circleci/config.yml
Labels: release/internal

#3154 Update message for untrusted certificates
  pkg/errors/errors.go
Labels: release/bug-fix

#3158 fix build when is buildv1 but dockerfile need to be inferred
  cmd/build/command.go
  integration/build/build_test.go
Labels: release/bug-fix, backport release-2.7

#3163 backport 3157 to release-2.8
  cmd/build/command.go
  integration/build/build_test.go
Labels: release/bug-fix, echoes/effort: S, echoes/intent: fix

#3164 fix patch in release-branch (#2961)
  scripts/ci/release-branch.sh
Labels: no-dco, release/internal, backport release-2.7, echoes/intent: fix

#3166 Backport #3164 to release-2.8
  scripts/ci/release-branch.sh
Labels: release/internal, echoes/intent: fix

#3159 Add option to display message if build section is not defined in okte…
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
Labels: new-contributor, release/internal

#3169 fix: panic on pipeline fallback to preview
  integration/commands/pipeline.go
  pkg/okteto/client.go
  pkg/okteto/pipeline.go
Labels: release/bug-fix, echoes/effort: S, echoes/intent: fix, backport release-2.8

#3172 fix: use the correct param on the API call
  cmd/preview/deploy.go
  cmd/preview/deploy_utils.go
  cmd/preview/deploy_utils_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.8

#3176 Revert "fix: volumes not being deleted (#2955)"
  cmd/deploy/proxy.go
  cmd/deploy/proxy_test.go
Labels: release/bug-fix, backport release-2.7, echoes/effort: XS, echoes/intent: fix, backport release-2.8

#3184 logs: add logs to syncthing terminating process
  pkg/config/config.go
  pkg/syncthing/syncthing.go
Labels: release/internal, echoes/effort: XS, echoes/intent: run, backport release-2.8

#3191 Updated error messaging when ctx use/update is used for vanilla clusters
  cmd/context/delete.go
Labels: new-contributor, release/bug-fix, echoes/effort: S, echoes/intent: fix

#3189 fix: add error on init container volume full
  cmd/up/activate.go
Labels: release/bug-fix, echoes/intent: fix

#3201 Make the channel setting configurable with an environment variable
  scripts/get-okteto.sh
Labels: release/new-feature, echoes/effort: S, echoes/intent: grow
