Repository okteto/okteto, pull requests merged in 2022-09, with the labels that each got.

#3054 chore: fix template for pull request
  .github/pull_request_template.md
Labels: release/internal

#3050 TrackReconnect new param to track dev pod recreation
  cmd/up/activate.go
  pkg/analytics/track.go
Labels: release/internal

#3037 allow okteto destroy on deploy cmd
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/kubeconfig.go
  cmd/destroy/cfghandler.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  integration/deploy/manifest_test.go
Labels: release/new-feature

#3069 fix: visual bug
  cmd/utils/selector.go
Labels: release/bug-fix

#3053 Okteto down and exec selector only active options
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/exec_test.go
  cmd/push.go
  cmd/restart.go
  cmd/status.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  pkg/k8s/apps/crud.go
  pkg/k8s/apps/crud_test.go
  pkg/model/manifest.go
Labels: release/internal

#3070 Fix TestListDevModeOn
  pkg/k8s/apps/crud.go
  pkg/k8s/apps/crud_test.go
Labels: release/internal

#3072 feat: update syncthing to 1.21.0
  pkg/model/dev.go
  pkg/syncthing/install.go
Labels: release/internal

#3079 show warning only when secret value is different
  cmd/context/use.go
Labels: release/bug-fix, backport release-2.7

#3087 Fix static analysis style issues
  cmd/analytics.go
  cmd/context/delete.go
  cmd/context/list.go
  cmd/context/update-kubeconfig_test.go
  cmd/context/utils.go
  cmd/deploy/proxy.go
  cmd/namespace/create.go
  cmd/namespace/namespace.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/pipeline/pipeline.go
  cmd/preview/preview.go
  cmd/stack/destroy.go
  cmd/stack/stack.go
  cmd/update.go
  cmd/utils/stack.go
  cmd/utils/warnings.go
  cmd/version.go
  integration/okteto.go
  internal/test/client/namespace.go
  internal/test/client/preview.go
  internal/test/client/user.go
  pkg/cmd/doctor/run.go
  pkg/cmd/pipeline/translate.go
  pkg/k8s/apps/translate.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/diverts/divert.go
  pkg/k8s/diverts/types.go
  pkg/k8s/ingresses/crud.go
  pkg/k8s/jobs/crud.go
  pkg/k8s/kubeconfig/client.go
  pkg/k8s/pods/pod.go
  pkg/k8s/statefulsets/crud.go
  pkg/log/format.go
  pkg/log/json.go
  pkg/log/log.go
  pkg/log/plain.go
  pkg/log/tty.go
  pkg/model/dev.go
  pkg/model/stack.go
  pkg/model/utils.go
  pkg/model/volumes.go
  pkg/okteto/client.go
  pkg/okteto/namespace.go
  pkg/okteto/secrets.go
  pkg/syncthing/completion.go
  pkg/syncthing/syncthing.go
  pkg/types/action.go
  pkg/types/build.go
  pkg/types/gitdeploy.go
  pkg/types/namespace.go
  pkg/types/okteto_client.go
  pkg/types/preview.go
  pkg/types/secret.go
Labels: release/internal

#3090 Added BuildSecrets to build manifest
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/model/dev.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/new-feature, need documentation

#3088 feat: add keep annotation
  integration/deploy/compose_test.go
  pkg/k8s/namespaces/namespace.go
  pkg/k8s/namespaces/namespace_test.go
Labels: release/new-feature, need documentation

#3073 Show pipeline deploy and destroy logs when running the command with `--wait` flag
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/pipeline/destroy.go
  cmd/pipeline/destroy_test.go
  internal/test/client/pipeline.go
  pkg/okteto/client.go
  pkg/okteto/pipeline.go
  pkg/types/interface.go
Labels: release/new-feature

#3057 Change logic for which images to build when deploying
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/model/manifest.go
  pkg/model/stack.go
Labels: no-dco, release/bug-fix, backport release-2.7

#3081 Show `preview deploy` logs when running the command with `--wait` flag
  cmd/context/create_test.go
  cmd/namespace/create_test.go
  cmd/namespace/delete_test.go
  cmd/namespace/list_test.go
  cmd/namespace/use_test.go
  cmd/preview/deploy.go
  cmd/preview/preview.go
  cmd/utils/okteto_test.go
  internal/test/client/preview.go
  pkg/okteto/pipeline.go
  pkg/okteto/preview.go
  pkg/types/interface.go
Labels: release/new-feature

#3092 Return clear error when docker compose doesn't have dev section
  cmd/up/up.go
Labels: no-dco, release/bug-fix

#3098 fix: deploy with build flag
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
Labels: release/bug-fix, backport release-2.7

#3100 Fix deploy build with compose: extra touches
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
Labels: release/internal, enhancement

#3099 fix antipatterns deepsource
  cmd/deploy/deploy.go
  cmd/manifest/init-v2.go
  cmd/manifest/selector.go
  internal/test/client/pipeline.go
  pkg/k8s/jobs/crud_test.go
  pkg/log/json.go
  pkg/model/stack_test.go
Labels: release/internal

#3095 Fix security issues deep source
  cmd/build/command_test.go
  cmd/build/v1/build_test.go
  cmd/build/v2/build_test.go
  cmd/deploy/command_configuration.go
  cmd/up/pid.go
  cmd/up/stignore.go
  cmd/up/stignore_test.go
  cmd/utils/git.go
  cmd/utils/git_test.go
  cmd/utils/stack_test.go
  cmd/utils/warnings.go
  integration/actions/apply_test.go
  integration/actions/build_test.go
  integration/actions/stacks_test.go
  integration/build/build_test.go
  integration/deploy/compose_test.go
  integration/deploy/deploy_test.go
  integration/deploy/endpoints_test.go
  integration/deploy/helm_test.go
  integration/deploy/manifest_test.go
  integration/deploy/pipeline_test.go
  integration/deprecated/push/push_test.go
  integration/deprecated/stack/compose_test.go
  integration/okteto/autowake_test.go
  integration/okteto/deploy_test.go
  integration/up/compose_test.go
  integration/up/up_test.go
  pkg/cmd/build/build_docker.go
  pkg/cmd/doctor/run.go
  pkg/cmd/login/login.go
  pkg/config/config.go
  pkg/discovery/compose_test.go
  pkg/discovery/contextresource_test.go
  pkg/discovery/helm_test.go
  pkg/discovery/k8s_test.go
  pkg/discovery/manifest_test.go
  pkg/discovery/pipeline_test.go
  pkg/filesystem/file.go
  pkg/k8s/pods/pod.go
  pkg/linguist/linguist.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest_test.go
  pkg/model/port.go
  pkg/model/port_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer_test.go
  pkg/registry/file.go
  pkg/ssh/exec.go
  pkg/ssh/forward.go
  pkg/ssh/manager.go
  pkg/ssh/manager_test.go
  pkg/ssh/reverse.go
  pkg/ssh/ssh.go
  pkg/syncthing/syncthing.go
Labels: release/internal

#3085 deprecate manifestv1
  cmd/up/up.go
  pkg/analytics/track.go
  pkg/model/manifest.go
  pkg/model/serializer_test.go
Labels: release/internal

#3071 fix: improve tokern error message inside non ctx cmd
  cmd/context/use.go
  pkg/errors/errors.go
Labels: release/bug-fix

#3114 Deepsource style doc
  cmd/build/v2/services_test.go
  cmd/context/context.go
  cmd/context/create.go
  cmd/pipeline/deploy.go
  integration/okteto/preview_test.go
  integration/up/globalforward_test.go
  main.go
  pkg/analytics/track.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/stack/destroy.go
  pkg/config/config.go
  pkg/errors/errors.go
  pkg/k8s/apps/interface.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/exec/exec.go
  pkg/log/format.go
  pkg/log/log.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/okteto/errors.go
  pkg/okteto/pipeline.go
  pkg/ssh/exec.go
  pkg/ssh/manager.go
  pkg/syncthing/syncthing.go
Labels: release/internal

#3108 Context store may just be non-existent rather than corrupt
  cmd/context/list.go
Labels: new-contributor, release/bug-fix

#3110 Add pr merge docs
  docs/code-review.md
Labels: no-dco, release/internal

#3109 redeploy stack with 0 downtime
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/model/const.go
Labels: release/bug-fix, need documentation

#3120 Update direct dependencies
  go.mod
  go.sum
Labels: release/internal

#3119 Fix secret copy
  integration/build/build_test.go
  integration/commands/build.go
  pkg/cmd/build/build.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: release/bug-fix

#3121 refactor: rewrite error message
  pkg/cmd/login/login.go
Labels: release/bug-fix

#3122 Deepsource bug risk
  .golangci.yml
  cmd/context/delete.go
  cmd/context/delete_test.go
  cmd/context/list.go
  cmd/context/update-kubeconfig.go
  cmd/context/update-kubeconfig_test.go
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy_test.go
  cmd/exec.go
  cmd/manifest/init-v2.go
  cmd/stack/deploy.go
  cmd/stack/endpoints.go
  cmd/status.go
  cmd/up/stignore.go
  cmd/up/syncthing.go
  cmd/utils/displayer/tty.go
  cmd/utils/git.go
  cmd/utils/progress_test.go
  internal/test/client/namespace.go
  internal/test/k8s_provider.go
  internal/test/login.go
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/build_docker.go
  pkg/cmd/init/run.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/endpoints.go
  pkg/cmd/status/run.go
  pkg/k8s/diverts/interface.go
  pkg/k8s/ingresses/crud.go
  pkg/log/json.go
  pkg/model/dev.go
  pkg/model/manifest.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
  pkg/okteto/k8s.go
  pkg/registry/registry.go
  pkg/ssh/config.go
  pkg/ssh/key.go
  pkg/ssh/key_test.go
  pkg/ssh/manager_test.go
  pkg/ssh/pool.go
  pkg/ssh/reverse.go
  pkg/ssh/ssh.go
  pkg/ssh/ssh_test.go
  pkg/syncthing/completion.go
  pkg/syncthing/syncthing.go
Labels: release/internal

#3126 Interrupt command deploy
  cmd/deploy/deploy.go
Labels: release/bug-fix

#3096 Different PV default sizes between cloud/staging and others
  pkg/k8s/volumes/crud.go
  pkg/k8s/volumes/crud_test.go
  pkg/model/const.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: no-dco, release/new-feature

#3128 Followup unit test for secrets
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/internal

#3106 add e2e test to check if build cmd replace secrets properly
  integration/okteto/build_test.go
Labels: release/internal

#3127 update init container logs
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: release/internal

#3133 Review info messages shown at the beginning of each command
  cmd/build/v1/build.go
  cmd/build/v2/build.go
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/preview/deploy.go
  cmd/preview/destroy.go
  cmd/up/up.go
Labels: no-dco, release/new-feature

#3115 add build variables as env vars for buildArgs
  cmd/build/v2/build.go
  cmd/context/utils_test.go
  cmd/deploy/deploy.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/stack_serializer.go
Labels: release/new-feature, need documentation
