Repository okteto/okteto, pull requests merged in 2022-07, with the labels that each got.

#2848 Add debug logs to help troubleshoot "--wait" flag
  cmd/pipeline/deploy.go
  pkg/model/const.go
  pkg/okteto/pipeline.go
  pkg/okteto/pipeline_test.go
  pkg/okteto/preview.go
Labels: release/new-feature

#2865 [release-2.4] fix github actions release script
  scripts/ci/release-github-actions.sh
Labels: no-dco, release/internal

#2866 Release fixes
  .circleci/config.yml
  integration/actions_test.go
  scripts/ci/release-github-actions.sh
Labels: no-dco, release/internal

#2880 Check more status in the `--wait` flag
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  integration/actions_test.go
  pkg/okteto/namespace.go
Labels: release/bug-fix

#2881 Adding information on PR labels to the contibution guide.
  contributing.md
Labels: no-dco, release/internal

#2882 Fix condition to force autocreate to false
  cmd/up/up.go
Labels: release/bug-fix

#2878 Use multi-platform okteto/bin image to support ARM clusters
  pkg/model/dev.go
Labels: release/new-feature

#2814 Jlopezbarb/fix up file flag compose
  pkg/model/manifest.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: release/bug-fix

#2891 Revert "Jlopezbarb/fix up file flag compose (#2814)"
  pkg/model/manifest.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: release/bug-fix

#2879 Update possible k8s manifest names
  pkg/model/manifest.go
Labels: new-contributor, release/new-feature

#2893 Jlopezbarb/fix up file flag compose
  pkg/model/manifest.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: release/bug-fix

#2864 fix configmap filename file path
  cmd/context/utils_test.go
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/manifest/init-v2.go
  cmd/up/activate.go
  cmd/up/exec.go
  cmd/up/syncthing.go
  cmd/up/up.go
  pkg/cmd/pipeline/translate.go
  pkg/model/file.go
  pkg/model/file_test.go
  pkg/model/manifest.go
  pkg/path/path.go
  pkg/path/path_test.go
Labels: release/bug-fix, backport release-2.4

#2883 Warning two dockerfiles fixed
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: no-dco, release/bug-fix

#2906 Fix github actions latest release
  scripts/ci/release-github-actions.sh
Labels: no-dco, release/internal, backport release-2.4

#2904 Fix to show endpoints after "okteto deploy"
  cmd/deploy/deploy.go
Labels: release/bug-fix

#2897 fix: forward request to cluster if invalid resource spec
  cmd/deploy/proxy.go
  cmd/deploy/proxy_test.go
Labels: release/bug-fix

#2915 Use GetKubernetesTimeout to configure our k8s proxy timeouts
  cmd/deploy/proxy.go
  pkg/model/const.go
  pkg/okteto/k8s.go
  pkg/ssh/client.go
Labels: release/bug-fix

#2922 fix: pipeline test
  integration/actions/pipeline_test.go
Labels: release/bug-fix

#2910 Load context resource only instead of the whole file while loading ctx
  cmd/context/create.go
  cmd/context/utils.go
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/manifest/init-v1.go
  cmd/up/stignore.go
  cmd/utils/dev.go
  cmd/utils/stack.go
  pkg/cmd/build/build.go
  pkg/cmd/doctor/run.go
  pkg/config/config.go
  pkg/discovery/compose.go
  pkg/discovery/compose_test.go
  pkg/discovery/contextresource.go
  pkg/discovery/contextresource_test.go
  pkg/discovery/errors.go
  pkg/discovery/helm.go
  pkg/discovery/helm_test.go
  pkg/discovery/k8s.go
  pkg/discovery/k8s_test.go
  pkg/discovery/manifest.go
  pkg/discovery/manifest_test.go
  pkg/discovery/pipeline.go
  pkg/discovery/pipeline_test.go
  pkg/errors/errors.go
  pkg/filesystem/file.go
  pkg/filesystem/file_test.go
  pkg/filesystem/workdir.go
  pkg/filesystem/workdir_test.go
  pkg/model/context.go
  pkg/model/contextresource.go
  pkg/model/contextresource_test.go
  pkg/model/file_test.go
  pkg/model/manifest.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/model/utils.go
  pkg/model/utils_test.go
  pkg/okteto/context.go
  pkg/ssh/key.go
  pkg/syncthing/install.go
Labels: release/bug-fix

#2892 docs: add code review guidelines
  docs/code-review.md
Labels: no-dco, release/internal

#2911 fix: wrong behaviour when okteto down --all
  cmd/down.go
Labels: release/bug-fix

#2923 login error page
  pkg/cmd/login/browser.go
  pkg/cmd/login/html.go
  pkg/cmd/login/html/email_error.go
  pkg/cmd/login/html/html.go
  pkg/cmd/login/html/login_fail.go
  pkg/cmd/login/html/login_success.go
  pkg/cmd/login/html/template.go
  pkg/cmd/login/login.go
  pkg/okteto/auth.go
  pkg/okteto/errors.go
Labels: no-dco, release/new-feature

#2938 add error auth page
  pkg/cmd/login/html/login_fail.go
  pkg/cmd/login/html/login_success.go
Labels: release/bug-fix

#2937 added condition to avoid dockerfile with "."
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: no-dco, release/bug-fix

#2939 fix: manifest deploying a compose
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  integration/deploy/compose_test.go
  integration/deploy/deploy_test.go
  pkg/cmd/build/build.go
Labels: release/bug-fix

#2940 Account for previous versions in release-branch
  scripts/ci/release-branch.sh
Labels: no-dco, release/internal

#2949 fix: vanilla clusters
  cmd/build/v2/services.go
  pkg/cmd/stack/deploy.go
Labels: release/bug-fix

#2950 fix: vanilla clusters (#2949)
  cmd/build/v2/services.go
  pkg/cmd/stack/deploy.go
Labels: release/bug-fix

#2944 Fix release notes (#2942)
  scripts/ci/release.sh
Labels: no-dco, release/internal

#2954 Fallback to Preview endpoint for waiting for dependencies
  cmd/preview/deploy.go
  integration/okteto/pipeline_test.go
  integration/okteto/preview_test.go
  pkg/okteto/pipeline.go
  pkg/okteto/preview.go
Labels: release/bug-fix

#2941 Account for previous versions in release-branch (#2940)
  scripts/ci/release-branch.sh
Labels: no-dco, release/internal

#2959 Remove paragraph in error template
  pkg/cmd/login/html/email_error.go
Labels: new-contributor, release/bug-fix

#2961 fix patch in release-branch
  scripts/ci/release-branch.sh
Labels: no-dco, invalid, release/internal

#2875 consider the context when calculating the path of the Dockerfile
  cmd/up/activate.go
  cmd/up/up.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: no-dco, release/bug-fix

#2962 Fix release-branch workflow
  .circleci/config.yml
Labels: no-dco, release/internal, backport release-2.5

#2969 Fix okteto destroy manifest not found with k8s.yml
  cmd/context/utils.go
  cmd/destroy/destroy.go
  cmd/up/up.go
  pkg/discovery/contextresource.go
Labels: release/bug-fix, backport release-2.5

#2918 Enable endpoints at okteto manifest
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/kubeconfig.go
  cmd/deploy/proxy.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/k8s/ingresses/crud.go
  pkg/k8s/ingresses/translate.go
  pkg/k8s/ingresses/translate_test.go
  pkg/model/manifest.go
Labels: release/new-feature
