Repository okteto/okteto, pull requests merged in 2023-12, with the labels that each got.

#4077 makefile: add lint-fix
  Makefile
Labels: release/internal, echoes/intent: run

#4079 Fix codespell in comments
  cmd/context/create.go
  docs/code-style.md
  pkg/http/transport.go
  pkg/model/const.go
  pkg/okteto/auth.go
  scripts/ci/push-image.sh
Labels: release/internal, echoes/intent: run

#4073 remove okteto cloud as context option
  cmd/context/selector.go
  cmd/context/use.go
  cmd/context/utils.go
  pkg/registry/client_test.go
Labels: release/internal, echoes/intent: run, run-e2e, backport release-2.23

#4082 [Backport release-2.23] Fix panic in `okteto init --deploy`
  cmd/build/v2/build.go
  cmd/init.go
  cmd/manifest/init-v1.go
  cmd/manifest/init-v2.go
  main.go
Labels: release/bug-fix, echoes/intent: fix

#4080 Fix: detect top level git rep dir to set `OKTETO_GIT_BRANCH` and `OKTETO_GIT_COMMIT` properly when service is nested
  cmd/build/v2/build.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/repository.go
Labels: release/bug-fix, echoes/intent: fix, run-e2e, backport release-2.23

#4085 [Backport release-2.23] Fix: detect top level git rep dir to set `OKTETO_GIT_BRANCH` and `OKT…
  cmd/build/v2/build.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/repository.go
Labels: release/bug-fix, echoes/intent: fix

#4070 refactor: remove okteto context global var use in okteto build command
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/remote/build.go
  cmd/build/remote/build_test.go
  cmd/build/v1/build.go
  cmd/build/v1/build_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/environment_test.go
  cmd/build/v2/imagechecker_test.go
  cmd/build/v2/services.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  cmd/context/use.go
  cmd/deploy/deploy_test.go
  cmd/namespace/namespace.go
  cmd/utils/okteto.go
  internal/test/build.go
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_docker.go
  pkg/cmd/build/build_test.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/context.go
  pkg/cmd/build/file.go
  pkg/cmd/build/file_test.go
  pkg/okteto/client.go
  pkg/okteto/config.go
  pkg/okteto/context.go
  pkg/okteto/context_stateless.go
  pkg/okteto/context_test.go
  pkg/okteto/registry_credentials.go
  pkg/registry/client_test.go
  pkg/registry/image.go
  pkg/registry/registry_test.go
Labels: no-dco, release/internal, echoes/intent: grow, echoes/intent: run, run-e2e

#4086 Update builkit client to v0.11.6
  go.mod
  go.sum
  pkg/cmd/build/build_docker.go
  pkg/cmd/build/buildkit.go
Labels: release/internal, run-e2e

#4088 chore: update syncthing version to 1.27.1
  pkg/model/dev.go
  pkg/syncthing/install.go
Labels: no-dco, release/internal, echoes/intent: grow

#4093 refactor: set deploy image tag as buildopt in deploy pkg
  cmd/deploy/remote.go
  pkg/cmd/build/build.go
Labels: release/internal

#4083 feat: use git commit instead of git tree hash
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/hasher.go
  cmd/build/v2/hasher_test.go
  cmd/build/v2/tagger_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#4091 improve err response for expired tokens
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/context/options.go
  cmd/context/options_test.go
  pkg/errors/errors.go
  pkg/okteto/client.go
  pkg/okteto/secrets_test.go
Labels: release/internal

#4095 update kubectl helm and kustomize versions
  Dockerfile
Labels: release/internal

#4090 Fix panic when parsing empty service sections (dev & build)
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/bug-fix, run-e2e

#4097 Revert "refactor: set deploy image tag as buildopt in deploy pkg (#40…
  cmd/deploy/remote.go
  pkg/cmd/build/build.go
Labels: release/internal

#4087 Update k8s client to `v0.28.4`
  cmd/logs/stern.go
  cmd/registrytoken/registrytoken.go
  go.mod
  go.sum
  pkg/cmd/build/buildkit.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/divert/weaver/divert_test.go
  pkg/divert/weaver/endpoints_test.go
  pkg/k8s/apps/deployments.go
  pkg/k8s/apps/statefulsets.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/jobs/crud_test.go
  pkg/k8s/namespaces/namespace.go
  pkg/k8s/pods/pod.go
  pkg/k8s/statefulsets/crud.go
  pkg/model/dev.go
  pkg/model/stack_serializer_test.go
  pkg/model/translation_test.go
Labels: no-dco, release/internal, run-e2e

#4099 fix: do not fail if error retrieving envs from image
  cmd/up/exec.go
  cmd/up/exec_test.go
Labels: release/bug-fix, backport release-2.23

#4103 Fix Golang version in contributing guide
  contributing.md
Labels: release/internal

#4102 Fix preview URL to not use hash pathname
  cmd/preview/deploy_utils.go
  cmd/preview/deploy_utils_test.go
Labels: release/bug-fix

#4105 Lax Codecov threshold on project delta
  .codecov.yml
Labels: release/internal
