Repository okteto/okteto, pull requests merged in 2023-07, with the labels that each got.

#3753 Always sync okteto manifest
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/discovery/compose.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/helm.go
  pkg/discovery/k8s.go
  pkg/discovery/manifest.go
  pkg/discovery/pipeline.go
  pkg/filesystem/file.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: no-dco, release/internal, echoes/intent: fix

#3779 Update go to 1.20
  .circleci/config.yml
  .golangci.yml
  Dockerfile
  Makefile
  contributing.md
  go.mod
Labels: release/internal, echoes/intent: run

#3766 add implementation to retrieve cmap variables when running in remote
  cmd/deploy/cfghandler.go
  integration/commands/deploy.go
  integration/okteto/deploy_test.go
Labels: release/bug-fix, echoes/intent: fix

#3784 feat(build): expand image before build
  cmd/build/v1/build.go
  cmd/build/v1/build_test.go
  pkg/model/dev_test.go
Labels: release/new-feature, echoes/intent: grow

#3787 Compute hash for divert annotation to limit the size of the annotation
  pkg/constants/constants.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/istio/virtualservices_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.17

#3790 reduce namespace name
  integration/okteto/deploy_test.go
Labels: release/internal, echoes/intent: fix

#3771 add dev mode annotation (sync or hybrid)
  pkg/constants/constants.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/internal, echoes/intent: run

#3755 Mount ssh agent in remote deploy
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/cmd/build/buildkit.go
  pkg/types/build.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3721 Execute `okteto destroy --remote` successfully when there is no okteto manifest found
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  cmd/destroy/remote.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/bug-fix, echoes/intent: fix

#3570 feat: add okteto preview `sleep|wake` command
  cmd/namespace/create_test.go
  cmd/namespace/delete_test.go
  cmd/namespace/namespace_test.go
  cmd/namespace/sleep_test.go
  cmd/namespace/wake_test.go
  cmd/preview/errors.go
  cmd/preview/preview.go
  cmd/preview/sleep.go
  cmd/preview/wake.go
  internal/test/client/preview.go
Labels: no-dco, new-contributor, release/new-feature, echoes/intent: grow

#3798 fix: context switch regression
  cmd/context/create.go
  cmd/context/create_test.go
  internal/test/client/user.go
  pkg/errors/errors.go
Labels: release/bug-fix, echoes/intent: fix

#3809 Fix win e2e
  .circleci/config.yml
Labels: release/bug-fix, echoes/intent: fix

#3802 fix publish okteto release for windows
  scripts/ci/release.sh
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3803 Initialize registrytoken command as docker credentials helper
  cmd/registrytoken/registrytoken.go
  main.go
  pkg/auth/dockercredentials/helper.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3799 Add cluster private credentials to build and deploy remote
  cmd/registrytoken/registrytoken.go
  internal/test/client/user.go
  main.go
  pkg/auth/dockercredentials/helper.go
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/okteto/config.go
  pkg/okteto/registry_credentials.go
  pkg/okteto/registry_credentials_test.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/registry/client.go
  pkg/registry/client_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/types/build.go
  pkg/types/interface.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3814 fix(up): skip deploy properly if deploy and depencencies are empty
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/up/up.go
  pkg/errors/errors.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/bug-fix, echoes/intent: fix

#3818 Add docker-credential-okteto to cli image
  Dockerfile
  docker-credential-okteto
Labels: no-dco, release/new-feature, echoes/intent: grow

#3819 Add dockerconfig in remote commands
  cmd/deploy/remote.go
  cmd/destroy/remote.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3804 feat: add `--output` flag for `okteto preview list`
  cmd/preview/list.go
  cmd/preview/list_test.go
Labels: release/bug-fix, echoes/intent: fix

#3831 fix: show context message on okteto build
  cmd/build/command.go
Labels: release/bug-fix

#3822 fix:infer name with default okteto manifest
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  pkg/devenvironment/name.go
  pkg/devenvironment/name_test.go
Labels: release/bug-fix, echoes/intent: fix

#3832 fix: command unmarshal wrapping command
  cmd/up/exec_unix.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, echoes/intent: fix

#3844 Added gracefull fail in case of malformed docker-compose.yml
  pkg/errors/errors.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3704 Fix context cancelled with reading git status operation
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
Labels: release/bug-fix, echoes/intent: fix

#3843 fix: build args flags populated into buildkit
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/bug-fix, echoes/intent: fix
