Repository okteto/okteto, pull requests merged in 2023-03, with the labels that each got.

#3412 fixes remote feature
  cmd/deploy/local.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/constants/constants.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.13

#3421 Jlopezbarb/add remote deploy unit test
  cmd/build/remote/build.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  cmd/manifest/init-v2.go
  cmd/pipeline/pipeline.go
  cmd/up/up.go
  pkg/filesystem/fake/temporal.go
  pkg/filesystem/fake/temporal_test.go
  pkg/filesystem/fake/wd.go
  pkg/filesystem/fake/wd_test.go
  pkg/filesystem/temporal.go
  pkg/filesystem/temporal_test.go
  pkg/filesystem/wd.go
  pkg/filesystem/wd_test.go
Labels: release/internal, echoes/intent: run

#3427 e2e: fix naming convention
  integration/actions/apply_test.go
  integration/actions/build_test.go
  integration/actions/namespace_test.go
  integration/actions/pipeline_test.go
  integration/actions/preview_test.go
  integration/actions/push_test.go
  integration/actions/stacks_test.go
Labels: release/internal, echoes/intent: fix

#3418 fix(cli): broken docs urls
  cmd/login.go
  cmd/manifest/init-v2.go
  cmd/stack/stack.go
  pkg/cmd/login/login.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: new-contributor, release/internal

#3423 Remove weaver CRD dependency from Okteto CLI
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/divert/driver.go
  pkg/divert/weaver/cache.go
  pkg/divert/weaver/cache_test.go
  pkg/divert/weaver/crd.go
  pkg/divert/weaver/crd_test.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/divert_test.go
  pkg/divert/weaver/endpoints.go
  pkg/divert/weaver/endpoints_test.go
  pkg/divert/weaver/ingresses.go
  pkg/divert/weaver/ingresses_test.go
  pkg/divert/weaver/services.go
  pkg/divert/weaver/services_test.go
  pkg/k8s/diverts/client.go
  pkg/k8s/diverts/interface.go
  pkg/k8s/diverts/register.go
  pkg/k8s/diverts/types.go
  pkg/k8s/ingresses/crud.go
  pkg/k8s/ingresses/crud_test.go
  pkg/model/const.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3436 fix: avoid panic when removing a deployment that does not exist…
  cmd/utils/dev.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/deployments/crud_test.go
Labels: release/bug-fix

#3432 fix destroy image envsub
  cmd/destroy/destroy.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/model/manifest.go
Labels: release/internal, echoes/intent: fix

#3447 interface defaults to localhost
  pkg/model/dev.go
  pkg/model/manifest_test.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, echoes/intent: fix

#3438 Ignore OKTETO_TOKEN warning if OKTETO_TOKEN is the one in the current…
  cmd/context/options.go
Labels: new-contributor, release/bug-fix, echoes/intent: fix

#3449 Jlopezbar/fix e2e tests
  cmd/context/options.go
  cmd/context/options_test.go
Labels: release/bug-fix, echoes/intent: fix

#3454 Jlopezbar/fix e2e tests
  cmd/context/options.go
Labels: no-dco, release/internal

#3458 Jlopezbarb/add actions graphql tests
  pkg/okteto/action.go
  pkg/okteto/action_test.go
  pkg/okteto/client.go
  pkg/okteto/client_test.go
  pkg/okteto/errors.go
  pkg/okteto/pipeline.go
  pkg/okteto/secrets.go
Labels: release/internal, echoes/intent: run

#3465 fix: remote deploy with name multiple words
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3455 fix(deploy): wait if dependency is being deployed
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy_test.go
  go.mod
  pkg/errors/errors.go
  pkg/k8s/configmaps/crud.go
  pkg/k8s/configmaps/crud_test.go
Labels: release/bug-fix, echoes/intent: run

#3441 Update dependencies and add spinner to check whether images needs to be built
  cmd/build/v2/services.go
  go.mod
  go.sum
Labels: no-dco, new-contributor, echoes/intent: fix

#3468 tests: remove unused file credential.go
  pkg/okteto/credential.go
Labels: release/internal, echoes/intent: run

#3404 Implement `kubetoken` command for k8s client authentication
  cmd/kubetoken/kubetoken.go
  main.go
  pkg/okteto/client.go
  pkg/okteto/kubetoken_client.go
  pkg/okteto/kubetoken_client_test.go
Labels: release/new-feature, echoes/intent: grow

#3471 add pipeline gql tests
  cmd/pipeline/deploy.go
  pkg/devenvironment/name.go
  pkg/okteto/client.go
  pkg/okteto/client_test.go
  pkg/okteto/pipeline.go
  pkg/okteto/pipeline_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/internal, echoes/intent: run

#3472 tests: add ns gql test
  pkg/okteto/namespace.go
  pkg/okteto/namespace_test.go
Labels: release/internal, echoes/intent: run

#3477 fix: destroy command should expand env vars
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/bug-fix, echoes/intent: fix

#3473 tests: add auth unit test
  pkg/cmd/login/browser.go
  pkg/okteto/auth.go
  pkg/okteto/auth_test.go
  pkg/okteto/client.go
  pkg/okteto/context.go
  pkg/okteto/pipeline.go
  pkg/okteto/preview.go
  pkg/okteto/secrets.go
Labels: release/internal, echoes/intent: run

#3480 Fixed issue where okteto doesnt accept 'Y' as option
  cmd/utils/dev.go
  cmd/utils/dev_test.go
Labels: new-contributor

#3409 Okteto kubeconfig will use kubetoken client auth if available on okteto server
  .circleci/config.yml
  Makefile
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/namespace/create_test.go
  integration/actions/apply_test.go
  integration/commands/preview.go
  integration/commands/push.go
  integration/commands/stacks.go
  pkg/okteto/client.go
  pkg/okteto/context.go
  pkg/okteto/context_test.go
  pkg/types/credential.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3490 Revert "Okteto kubeconfig will use kubetoken client auth if available on okteto server"
  .circleci/config.yml
  Makefile
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/namespace/create_test.go
  integration/actions/apply_test.go
  integration/commands/preview.go
  integration/commands/push.go
  integration/commands/stacks.go
  pkg/okteto/client.go
  pkg/okteto/context.go
  pkg/okteto/context_test.go
  pkg/types/credential.go
Labels: no-dco, release/internal, echoes/intent: run

#3475 don't initialize okteto client if not using okteto cloud
  cmd/destroy/destroy.go
  cmd/pipeline/pipeline.go
Labels: new-contributor

#3489 inject OKTETO_ACTION_NAME in remote
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3494 chore(destroy): better error message when image not accessible
  cmd/destroy/destroy.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
Labels: release/internal, echoes/intent: fix, backport release-2.14

#3493 fix: add remote build image building
  cmd/build/v2/services.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/destroy/destroy.go
  docs/code-style.md
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3504 fix destroy remote when adding envs with blank values
  cmd/deploy/remote.go
  cmd/destroy/remote.go
Labels: release/internal, echoes/intent: fix, backport release-2.14

#3496 remove external resource validation
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/local.go
  pkg/externalresource/control.go
  pkg/externalresource/control_test.go
Labels: release/internal, echoes/intent: fix, backport release-2.14

#3511 [Backport release-2.14] fix destroy remote when adding envs with blank values
  cmd/deploy/remote.go
  cmd/destroy/remote.go
Labels: release/internal, echoes/intent: fix

#3507 fix: extra step internal server error on remote
  cmd/deploy/local.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/errors.go
  pkg/cmd/build/logger.go
Labels: no-dco, release/bug-fix, echoes/intent: fix, backport release-2.14

#3518 fix: e2e test for cmd output
  integration/okteto/deploy_test.go
Labels: release/bug-fix, echoes/intent: fix

#3513 infer dev name before create remote image
  cmd/destroy/destroy.go
  cmd/destroy/local.go
  integration/deploy/manifest_test.go
Labels: release/internal, echoes/intent: fix, backport release-2.14

#3523 fix: destroy with multiple words
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3525 fix: deploy with invalid image on remote
  pkg/cmd/build/buildkit.go
Labels: release/bug-fix, echoes/intent: fix

#3526 fix: remote deploy/destroy with no pull access image
  cmd/deploy/remote.go
  cmd/destroy/remote.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14
