Repository okteto/okteto, pull requests merged in 2023-05, with the labels that each got.

#3580 fix git pull approach
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/imagechecker_test.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  pkg/cmd/build/buildkit.go
  pkg/model/dev.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.15

#3587 fix git pull approach (#3580)
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/imagechecker_test.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  pkg/cmd/build/buildkit.go
  pkg/model/dev.go
Labels: release/bug-fix, echoes/intent: fix

#3343 default OKTETO_NAMESPACE to space param in credentials query
  cmd/context/create.go
  cmd/preview/deploy.go
  cmd/preview/destroy.go
  cmd/preview/endpoints.go
  internal/test/client/user.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/types/interface.go
Labels: no-dco, keep, release/bug-fix, echoes/intent: fix

#3586 Add external resources to preview endpoints
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
Labels: no-dco, release/bug-fix, echoes/intent: run

#3591 doc: add more context on errors
  cmd/pipeline/deploy.go
  pkg/okteto/action.go
  pkg/okteto/pipeline.go
Labels: release/internal, echoes/intent: run, backport release-2.15

#3556 Add replicas field in Services to specify the required replicas for services and scale back the original deployment after okteto down
  pkg/cmd/down/run.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: release/bug-fix, echoes/intent: fix

#3600 Remove behaviour of setting service replicas one, if deployment replicas is zero
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
Labels: release/bug-fix, echoes/intent: fix

#3602 Handle defaults in okteto kubetoken
  cmd/kubetoken/kubetoken.go
Labels: release/internal

#3598 Modify okteto namespace delete command to delete current namespace if no argument is passed
  cmd/namespace/delete.go
Labels: release/new-feature

#3619 remove server-name shorthand
  main.go
Labels: release/internal

#3610 feat: improve `.gitignore`
  .gitignore
Labels: new-contributor, release/internal

#3605 feat: add test cases for `namespace sleep|wake`
  cmd/namespace/sleep_test.go
  cmd/namespace/wake_test.go
  internal/test/client/namespace.go
Labels: new-contributor, release/internal

#3614 Deploy command works even if only dependencies are specified in manifest
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/errors/errors.go
  pkg/model/serializer.go
Labels: release/bug-fix, echoes/intent: fix

#3631 fix: panic on e2e tests
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/local.go
  cmd/deploy/wait.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  integration/actions/preview_test.go
  integration/commands/deploy.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  pkg/repository/git.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.15, backport release-2.16

#3636 [Backport release-2.15] fix: panic on e2e tests
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/local.go
  cmd/deploy/wait.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  integration/actions/preview_test.go
  integration/commands/deploy.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  pkg/repository/git.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
Labels: release/bug-fix, echoes/intent: fix

#3626 Use chart runner and installer images for remote deploy/destroy
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/constants/constants.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/types/cluster_metadata.go
Labels: release/bug-fix, echoes/intent: fix

#3571 support hybrid development
  cmd/deploy/local.go
  cmd/destroy/destroy.go
  cmd/exec.go
  cmd/up/activate.go
  cmd/up/exec.go
  cmd/up/exec_test.go
  cmd/up/stignore.go
  cmd/up/syncthing.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/up/up_test.go
  cmd/utils/executor/executor.go
  go.mod
  go.sum
  integration/commands/dev.go
  integration/up/hybridmode_test.go
  internal/test/client/user.go
  pkg/analytics/track.go
  pkg/constants/constants.go
  pkg/model/dev.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/registry/image.go
  pkg/registry/registry.go
  pkg/types/interface.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3657 fix: buil args expansion
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.15, backport release-2.16

#3658 fix(build): vanilla cluster should not reach out to okteto registry
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
Labels: release/bug-fix, echoes/intent: fix

#3669 fix windows e2e hybrid development
  cmd/up/exec.go
  integration/up/hybridmode_test.go
  pkg/model/dev.go
Labels: release/internal, echoes/intent: fix

#3635 remove secret content from build hash
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  pkg/model/dev.go
Labels: new-contributor

#3666 add local envs for hybrid command
  cmd/up/exec.go
  cmd/up/exec_test.go
Labels: release/bug-fix, echoes/intent: fix

#3648 fix: performance issues on `git status`
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3584 Fixes wrong spinner on okteto deploy --remote
  cmd/destroy/remote.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/logger.go
Labels: release/bug-fix, backport release-2.16

#3671 [Backport release-2.16] incorrect remote spinner
  cmd/destroy/remote.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/logger.go
Labels: release/bug-fix, echoes/intent: fix

#3515 Restore "Okteto kubeconfig will use kubetoken client auth if available on okteto server""
  .circleci/config.yml
  Makefile
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/namespace/create_test.go
  go.mod
  go.sum
  integration/actions/apply_test.go
  integration/commands/preview.go
  integration/commands/push.go
  integration/commands/stacks.go
  pkg/model/port.go
  pkg/okteto/client.go
  pkg/okteto/context.go
  pkg/okteto/context_test.go
  pkg/types/credential.go
Labels: no-dco, release/breaking-change, echoes/intent: grow

#3675 Add os environ to RunOktetoEndpoints
  integration/commands/endpoints.go
Labels: release/internal

#3677 fix send on closed channel panic in isClean
  pkg/repository/git.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
Labels: no-dco, release/bug-fix, echoes/intent: fix, backport release-2.16

#3595 Modify okteto ns create command to prevent selecting the new namespace as current namespace
  cmd/context/options.go
  cmd/namespace/create.go
Labels: no-dco, release/new-feature
