Repository okteto/okteto, pull requests merged in 2023-09, with the labels that each got.

#3957 docs: update PR template
  .github/pull_request_template.md
  docs/code-review.md
Labels: release/internal, echoes/intent: grow

#3960 chore: update codecov
  .codecov.yml
Labels: release/internal, echoes/intent: run

#3961 Basic golangci lint
  .circleci/config.yml
  .github/pull_request_template.md
  .github/workflows/run-circleci-from-label.yml
  .gitignore
  .golangci.yml
  contributing.md
  docs/code-review.md
  docs/how-to-run-tests.md
  scripts/get-okteto.sh
Labels: release/internal, echoes/intent: run

#3965 [golangci-lint] Enable errcheck
  .golangci.yml
  cmd/build/v2/config_test.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local_test.go
  cmd/deploy/remote.go
  cmd/destroy/destroy_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  cmd/manifest/init-v1_test.go
  cmd/manifest/init-v2.go
  cmd/pipeline/deploy_test.go
  cmd/up/up.go
  cmd/up/up_test.go
  cmd/utils/displayer/collapse_tty.go
  cmd/utils/selector.go
  cmd/utils/upgrade_test.go
  integration/commands/dev.go
  integration/k8s-client.go
  main.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_docker.go
  pkg/cmd/build/build_test.go
  pkg/cmd/build/file.go
  pkg/cmd/doctor/run.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/pipeline/translate_test.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/devenvironment/name_test.go
  pkg/divert/istio/virtualservices_test.go
  pkg/divert/weaver/cache_test.go
  pkg/divert/weaver/divert_test.go
  pkg/divert/weaver/services_test.go
  pkg/externalresource/external_resource_test.go
  pkg/externalresource/k8s/fake/fake_external_resource_client.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/configmaps/crud_test.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/jobs/crud_test.go
  pkg/k8s/statefulsets/crud.go
  pkg/log/json.go
  pkg/log/json_test.go
  pkg/log/spinner.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/stack_serializer_test.go
  pkg/model/translation_test.go
  pkg/okteto/context.go
  pkg/remote/remote_test.go
  pkg/ssh/manager_test.go
Labels: release/internal, echoes/intent: run

#3966 [golangci-lint] Enable gosimple
  .golangci.yml
  cmd/namespace/create.go
  integration/commands/dev.go
Labels: release/internal, echoes/intent: run

#3956 expand branch value if comes from variable
  cmd/deploy/deploy.go
  cmd/up/exec.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.20

#3974 chore: remove PR annotations
  .codecov.yml
Labels: release/internal, echoes/intent: run

#3969 chore: update syncthing to 1.24.0
  pkg/model/dev.go
  pkg/model/serializer_test.go
  pkg/syncthing/install.go
Labels: release/internal, echoes/intent: grow

#3977 Generic invalid license error
  cmd/context/create.go
  pkg/errors/errors.go
  pkg/okteto/auth.go
  pkg/okteto/auth_test.go
  pkg/okteto/client.go
Labels: no-dco, release/internal, echoes/intent: grow

#3964 feat: add support for labels when deploying a pipeline
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  pkg/okteto/pipeline.go
  pkg/okteto/pipeline_test.go
  pkg/types/gitdeploy.go
Labels: release/new-feature, echoes/intent: grow

#3972 [golangci-lint] enable govet ineffassign staticcheck
  .golangci.yml
  cmd/context/create_test.go
  cmd/deploy/proxy.go
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  cmd/utils/okteto.go
  main.go
  pkg/divert/driver.go
  pkg/divert/istio/divert.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/weaver/divert.go
  pkg/model/volumes.go
Labels: release/internal, echoes/intent: run

#3970 Fix preview list output
  cmd/preview/list.go
  cmd/preview/list_test.go
Labels: release/bug-fix, echoes/intent: fix, echoes/intent: grow

#3853 feat: add `remote` field in okteto manifest
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  cmd/destroy/local.go
  cmd/destroy/remote.go
  pkg/constants/constants.go
  pkg/discovery/pipeline.go
  pkg/model/manifest.go
Labels: no-dco, release/new-feature

#3976 [golangci-lint] Enable lint unused unparam
  .circleci/config.yml
  .golangci.yml
  cmd/build/command_test.go
  cmd/build/remote/build_test.go
  cmd/build/v1/build_test.go
  cmd/build/v2/build_test.go
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  cmd/destroy/remote_test.go
  cmd/exec.go
  cmd/manifest/init-v2.go
  cmd/up/exec.go
  internal/test/client/user.go
  internal/test/k8s_provider.go
  pkg/cache/constants.go
  pkg/cmd/init/run.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/services.go
  pkg/divert/weaver/services_test.go
  pkg/model/stack.go
  pkg/registry/registry_test.go
  pkg/repository/repository_test.go
  pkg/ssh/manager.go
Labels: release/internal, echoes/intent: run

#3971 feat: add pipeline list cmd
  cmd/pipeline/list.go
  cmd/pipeline/list_test.go
  cmd/pipeline/pipeline.go
  pkg/constants/constants.go
  pkg/k8s/configmaps/crud_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3943 link kubetoken docs when using static tokens
  cmd/context/update-kubeconfig.go
Labels: release/internal, echoes/intent: run

#3995 fix panic deploying dependencies in vanilla
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
Labels: release/internal, echoes/intent: fix

#3984 fix: high resources panic
  pkg/k8s/deployments/crud.go
  pkg/k8s/deployments/crud_test.go
Labels: release/bug-fix, echoes/intent: fix

#3985 New option `--reuse-params` at `okteto pipeline deploy`
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  integration/commands/pipeline.go
  integration/okteto/pipeline_test.go
  internal/test/client/pipeline.go
Labels: release/new-feature, echoes/intent: grow

#3982 Panic secret not valid
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/bug-fix, echoes/intent: fix
