Repository okteto/okteto, pull requests merged in 2023-10, with the labels that each got.

#3886 Add support for deleting multiple context
  cmd/context/delete.go
  cmd/context/delete_test.go
  go.mod
  go.sum
  pkg/analytics/track.go
Labels: release/new-feature, contributor

#3930 fix: show error for `okteto deploy` when no manifest file exists using `-f` flag
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
Labels: release/bug-fix, contributor

#4008 Remove file after test
  cmd/deploy/deploy_test.go
Labels: release/internal, echoes/intent: fix

#4003 Deploy remote extra hosts
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/cmd/build/buildkit.go
  pkg/types/build.go
Labels: no-dco, release/bug-fix, echoes/intent: run

#4018 ci: add tenv linter
  .golangci.yml
  cmd/context/use_test.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote_test.go
  cmd/stack/deploy_test.go
  cmd/utils/stack_test.go
  integration/actions/pipeline_test.go
  pkg/analytics/track_test.go
  pkg/config/config_test.go
  pkg/model/contextresource_test.go
  pkg/model/dev_test.go
  pkg/model/manifest_test.go
  pkg/model/serializer_test.go
  pkg/model/stack_serializer_test.go
  pkg/model/stack_test.go
  pkg/model/utils_test.go
  pkg/okteto/client_test.go
  pkg/ssh/ssh_test.go
  pkg/syncthing/install_test.go
  pkg/syncthing/syncthing_test.go
Labels: release/internal, echoes/intent: run, run-e2e

#4012 chore: fix an error message on deploying ingress with same name (fix #3827)
  pkg/cmd/stack/deploy.go
Labels: new-contributor, release/internal

#4020 [CLI Quality][Lint] add tparallel lint and fix errors
  .golangci.yml
  cmd/build/command_test.go
  cmd/context/create_test.go
  cmd/deploy/proxy_test.go
  cmd/up/forwards_test.go
  pkg/cmd/build/build_test.go
Labels: release/internal, echoes/intent: run

#4021 fix: e2e tests
  integration/actions/pipeline_test.go
Labels: release/internal, echoes/intent: fix, run-e2e

#4001 Implement new event ImageBuild
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/environment_test.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/imagechecker_test.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/destroy/destroy.go
  cmd/manifest/init-v1.go
  cmd/manifest/init-v2.go
  cmd/stack/deploy.go
  cmd/stack/stack.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/up/up_test.go
  main.go
  pkg/analytics/hasher.go
  pkg/analytics/hasher_test.go
  pkg/analytics/imagebuild.go
  pkg/analytics/imagebuild_test.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/translate.go
Labels: release/internal, echoes/intent: grow, run-e2e

#4019 Display a friendly error when the local proxy cannot start
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/deploy/local_test.go
  cmd/deploy/proxy.go
  cmd/deploy/proxy_test.go
Labels: release/internal, echoes/intent: run

#4010 feat: add `--include-token` flag to `okteto ctx show` command
  cmd/context/show.go
Labels: release/new-feature, echoes/intent: grow, run-e2e

#4024 Update analytics data
  cmd/build/remote/build.go
  cmd/build/v1/build.go
  cmd/context/create.go
  cmd/push.go
  pkg/analytics/track.go
  pkg/cmd/build/build.go
  pkg/okteto/context.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/types/cluster_metadata.go
Labels: release/internal, echoes/intent: fix

#4023 add build service context generation to image build event
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/environment_test.go
  cmd/build/v2/services_test.go
  pkg/analytics/imagebuild.go
  pkg/analytics/imagebuild_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/internal, echoes/intent: run

#4007 Skip selector in `okteto down` when only 1 dev container is active
  cmd/down.go
Labels: new-contributor, release/new-feature, echoes/intent: grow

#4009 User Friendly Errors
  cmd/build/command.go
  cmd/deploy/deploy.go
  go.mod
  pkg/errors/errors.go
  pkg/model/contextresource.go
  pkg/model/devrc.go
  pkg/model/manifest.go
  pkg/model/manifest_friendly_err.go
  pkg/model/manifest_friendly_err_test.go
  pkg/model/manifest_test.go
  pkg/model/schema.go
  pkg/model/schema_test.go
  pkg/suggest/rules.go
  pkg/suggest/rules_test.go
  pkg/suggest/suggest.go
  pkg/suggest/suggest_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow, run-e2e

#4011 chore: update error when not-in-okteto-context for guiding next step more clearly (fix #3792)
  cmd/build/v2/build.go
  cmd/context/context.go
  cmd/context/use.go
  cmd/deploy/deploy.go
  cmd/deploy/local.go
  pkg/cmd/login/login.go
  pkg/errors/errors.go
  pkg/okteto/secrets.go
Labels: new-contributor, release/internal, echoes/intent: run

#4027 Fix panic when interrupt deploy
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/deploy/proxy.go
  cmd/deploy/proxy_test.go
Labels: release/bug-fix, echoes/intent: fix
