Repository okteto/okteto, pull requests merged in 2023-01, with the labels that each got.

#3308 Solves okteto/app#5180. Destroy preview calls Okteto API to destroy the preview and stream logs
  cmd/preview/destroy.go
  cmd/preview/destroy_test.go
  cmd/preview/errors.go
  internal/test/client/preview.go
  pkg/okteto/preview.go
  pkg/types/interface.go
Labels: release/new-feature, echoes/intent: grow

#3318 Filled up an incomplete comment
  cmd/namespace/namespace.go
Labels: release/internal, echoes/intent: run

#3215 feat: add support for custom commands in `okteto up`
  cmd/up/up.go
  cmd/up/up_test.go
  cmd/utils/dev.go
Labels: stale, release/new-feature, echoes/intent: grow

#3300 Check deployed dev environments when inferring the name
  cmd/build/v2/build.go
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/logs/logs.go
  cmd/manifest/init-v1_test.go
  cmd/manifest/init-v2.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/push.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  cmd/utils/manifest.go
  pkg/devenvironment/name.go
  pkg/devenvironment/name_test.go
  pkg/model/stack.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3335 Jlopezbarb/remote-deploy-logs
  cmd/build/v2/environment.go
  cmd/deploy/remote.go
  cmd/utils/executor/executor.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/logger.go
Labels: release/new-feature, echoes/intent: grow

#3337 refactor remote deploy
  cmd/build/remote/build.go
  cmd/build/remote/build_test.go
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/local.go
  cmd/deploy/remote.go
  integration/deploy/manifest_test.go
  pkg/cmd/build/logger.go
  pkg/constants/constants.go
  pkg/model/serializer.go
Labels: release/internal, echoes/intent: run

#3338 Jlopezbarb/move common code to deploy
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/local.go
  cmd/deploy/remote.go
Labels: release/internal, echoes/intent: run

#3339 add dockerignore as part of remote deploy
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  pkg/model/serializer_test.go
Labels: release/internal, echoes/intent: run

#3292 Add parameter for pass thru of allowPrivilegeEscalation (#3291)
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: no-dco, new-contributor, release/new-feature

#3347 fix deploy when field notes not given to external
  pkg/externalresource/external_resource.go
  pkg/externalresource/external_resource_test.go
Labels: release/bug-fix, echoes/intent: fix

#3344 Add fixes for remote deploy
  Dockerfile
  cmd/deploy/cfghandler.go
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  pkg/cmd/build/logger.go
  pkg/constants/constants.go
Labels: release/internal, echoes/intent: fix

#3349 Fix remote deploy image empty
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  cmd/deploy/local.go
  cmd/deploy/remote.go
  cmd/utils/executor/json.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/internal, echoes/intent: grow

#3351 Wait for cronjobs to finish the execution of their jobs
  pkg/okteto/const.go
  pkg/okteto/pipeline.go
  pkg/okteto/pipeline_test.go
  pkg/okteto/preview.go
Labels: release/new-feature, echoes/intent: grow, backport release-2.12

#3350 add possible values for icon for external resource
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/externalresource/control.go
  pkg/externalresource/control_test.go
  pkg/externalresource/k8s/fake/fake_external_resource.go
  pkg/externalresource/k8s/interface.go
  pkg/externalresource/k8s/types.go
  pkg/externalresource/serializer.go
  pkg/externalresource/serializer_test.go
Labels: release/internal, echoes/intent: grow

#3356 fix zero value for external icon field
  pkg/externalresource/k8s/types.go
Labels: release/internal, echoes/intent: fix

#3361 Remove github.com/rancher/wrangler dependency
  go.mod
  go.sum
  pkg/k8s/namespaces/namespace.go
Labels: release/internal, echoes/intent: run

#3354 add external url to okteto env file
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  pkg/constants/constants.go
  pkg/externalresource/control.go
  pkg/externalresource/control_test.go
  pkg/externalresource/external_resource.go
  pkg/externalresource/external_resource_test.go
  pkg/externalresource/serializer.go
  pkg/externalresource/serializer_test.go
Labels: release/new-feature, echoes/intent: grow
