Repository okteto/okteto, pull requests merged in 2023-08, with the labels that each got.

#3811 Fix hybrid interactive terminal and processes
  cmd/exec.go
  cmd/up/exec.go
  cmd/up/exec_unix.go
  cmd/up/exec_windows.go
  cmd/up/up.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3852 Run e2e tests from PR labels
  .circleci/config.yml
  .github/workflows/run-circleci-from-label.yml
Labels: release/internal, echoes/intent: run, run-e2e, run-e2e-unix

#3861 fix: preview output json
  cmd/preview/endpoints.go
Labels: release/bug-fix, echoes/intent: fix

#3870 add logs for image digest getter
  cmd/build/v2/build.go
  cmd/build/v2/environment.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/services.go
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  pkg/log/json.go
  pkg/log/json_test.go
  pkg/log/log.go
  pkg/log/tty.go
  pkg/registry/client.go
  pkg/registry/registry.go
Labels: release/internal, echoes/intent: run

#3848 track deploy and destroy on remote
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/destroy.go
  cmd/destroy/local.go
  cmd/preview/list_test.go
  cmd/up/activate.go
  cmd/up/exec_test.go
  cmd/up/up.go
  docs/how-to-run-tests.md
  integration/up/hybridmode_test.go
  pkg/analytics/deploy.go
  pkg/analytics/deploy_test.go
  pkg/analytics/destroy.go
  pkg/analytics/destroy_test.go
  pkg/analytics/track.go
  pkg/analytics/tracker.go
  pkg/analytics/tracker_test.go
  pkg/model/manifest_test.go
  pkg/okteto/secrets_test.go
  scripts/ci/release.sh
Labels: technical debt, release/internal, echoes/intent: run

#3872 revert: track deploy and destroy
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/destroy.go
  cmd/destroy/local.go
  cmd/preview/list_test.go
  cmd/up/activate.go
  cmd/up/exec_test.go
  cmd/up/up.go
  docs/how-to-run-tests.md
  pkg/analytics/deploy.go
  pkg/analytics/deploy_test.go
  pkg/analytics/destroy.go
  pkg/analytics/destroy_test.go
  pkg/analytics/track.go
  pkg/analytics/tracker.go
  pkg/analytics/tracker_test.go
  pkg/model/manifest_test.go
  pkg/okteto/secrets_test.go
Labels: release/internal, echoes/intent: fix

#3808 [Hybrid] Support additional Dev fields
  integration/k8s-client.go
  integration/up/hybridmode_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3877 Revert "add logs for image digest getter (#3870)"
  cmd/build/v2/build.go
  cmd/build/v2/environment.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/services.go
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  pkg/log/json.go
  pkg/log/json_test.go
  pkg/log/log.go
  pkg/log/tty.go
  pkg/registry/client.go
  pkg/registry/registry.go
Labels: release/internal, echoes/intent: run

#3874 fix: compute build envs in local
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.18

#3873 track deploy destroy on remote
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/destroy.go
  cmd/destroy/local.go
  cmd/preview/list_test.go
  cmd/up/activate.go
  cmd/up/exec_test.go
  cmd/up/up.go
  docs/how-to-run-tests.md
  pkg/analytics/deploy.go
  pkg/analytics/deploy_test.go
  pkg/analytics/destroy.go
  pkg/analytics/destroy_test.go
  pkg/analytics/track.go
  pkg/analytics/tracker.go
  pkg/analytics/tracker_test.go
  pkg/model/manifest_test.go
  pkg/okteto/secrets_test.go
Labels: no-dco, release/internal, echoes/intent: run, run-e2e

#3845 Add CA to kubeconfig in insecure mode
  cmd/context/create.go
  cmd/context/update-kubeconfig.go
  pkg/okteto/context.go
Labels: no-dco, release/bug-fix, echoes/intent: run

#3888 Wrap kubetoken client into OktetoClient
  cmd/kubetoken/kubetoken.go
  internal/test/client/kubetoken.go
  internal/test/client/okteto_client.go
  pkg/okteto/client.go
  pkg/okteto/kubetoken_client.go
  pkg/okteto/kubetoken_client_test.go
  pkg/types/interface.go
  pkg/types/kubetoken.go
Labels: no-dco, release/internal, echoes/intent: run, run-e2e

#3890 fix: compose not getting image expansion from build
  cmd/deploy/deploy.go
  integration/commands/deploy.go
  integration/deploy/compose_test.go
  pkg/cmd/stack/deploy.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.18, run-e2e

#3875 Up event refactor
  cmd/up/activate.go
  cmd/up/syncthing.go
  cmd/up/types.go
  cmd/up/up.go
  pkg/analytics/deploy.go
  pkg/analytics/destroy.go
  pkg/analytics/track.go
  pkg/analytics/tracker.go
  pkg/analytics/up.go
  pkg/analytics/up_test.go
  pkg/syncthing/completion.go
Labels: release/internal, echoes/intent: run

#3876 Add new props to up event
  cmd/up/activate.go
  cmd/up/syncthing.go
  cmd/up/up.go
  pkg/analytics/up.go
  pkg/analytics/up_test.go
Labels: release/internal, echoes/intent: run

#3895 fix: if repo is not clean always return err
  pkg/repository/git.go
  pkg/repository/git_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.18, backport release-2.19

#3880 fix panic when displayer has no cancel function
  cmd/utils/displayer/json.go
  cmd/utils/displayer/plain.go
  cmd/utils/displayer/tty.go
  cmd/utils/executor/executor.go
Labels: release/bug-fix, echoes/intent: fix

#3887 Add exec to kubeconfig when okteto context init
  .circleci/config.yml
  cmd/context/update-kubeconfig.go
  cmd/context/update-kubeconfig_test.go
  cmd/kubeconfig.go
  integration/actions/apply_test.go
  integration/kubeconfig/kubeconfig_test.go
  internal/test/client/kubetoken.go
Labels: no-dco, release/new-feature, echoes/intent: grow, run-e2e

#3891 Use dynamic kube token for k8s requests
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/namespace/create_test.go
  cmd/namespace/delete_test.go
  cmd/namespace/use_test.go
  integration/commands/kubetoken.go
  internal/test/client/user.go
  pkg/errors/errors.go
  pkg/okteto/context.go
  pkg/okteto/kubetoken_client.go
  pkg/okteto/kubetoken_client_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow, run-e2e

#3908 fix: wait until build stops logs to return
  pkg/cmd/build/buildkit.go
Labels: release/bug-fix, echoes/intent: fix

#3910 Add cache to registry credentials
  pkg/okteto/registry_credentials.go
  pkg/okteto/registry_credentials_test.go
Labels: no-dco, release/bug-fix, echoes/intent: run, backport release-2.19

#3893 Feature Flag to Opt-In to Static Tokens/Existing Flow
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/context/update-kubeconfig.go
  cmd/context/update-kubeconfig_test.go
  integration/kubetoken/kubetoken_test.go
  pkg/constants/constants.go
  pkg/model/const.go
Labels: no-dco, release/new-feature, echoes/intent: grow, run-e2e

#3920 fix `okteto kubeconfig` for non okteto contexts
  cmd/context/update-kubeconfig.go
  cmd/context/update-kubeconfig_test.go
Labels: release/internal, echoes/intent: fix

#3899 Adding syncthing api unittests.
  pkg/syncthing/api.go
  pkg/syncthing/api_test.go
Labels: no-dco, release/internal, echoes/intent: run

#3917 Extend help from kubeconfig command to mention that the generated kub…econfig requires to have Okteto CLI in the path
  cmd/context/update-kubeconfig.go
  cmd/kubeconfig.go
Labels: no-dco, release/internal, echoes/intent: run

#3928 Fix kubetoken remote deploy
  cmd/context/create.go
  cmd/context/create_test.go
Labels: release/bug-fix, echoes/intent: fix

#3937 fix(hybrid): read env vars from configmap
  cmd/up/exec.go
  cmd/up/exec_test.go
Labels: release/bug-fix, echoes/intent: fix

#3931 fix(hybrid): read secrets from kubernetes
  cmd/up/exec.go
  cmd/up/exec_test.go
  pkg/k8s/secrets/crud.go
Labels: no-dco, release/bug-fix, echoes/intent: fix, run-e2e

#3940 Tag with global and dev when pushing to global registry
  cmd/build/v1/build.go
  cmd/build/v2/build.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/registry/image.go
  pkg/registry/image_test.go
  pkg/types/build.go
Labels: release/new-feature, echoes/intent: grow, run-e2e

#3950 feat: clone from global to dev reg already built images
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/deploy/deploy_test.go
  pkg/registry/client.go
  pkg/registry/client_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
Labels: release/new-feature, echoes/intent: grow

#3939 tests: add kubetoken unit tests
  cmd/kubeconfig.go
  cmd/kubetoken/kubetoken.go
  cmd/kubetoken/kubetoken_test.go
  cmd/kubetoken/validator.go
  cmd/kubetoken/validator_test.go
  main.go
  pkg/log/format.go
  pkg/log/silent.go
Labels: release/internal, echoes/intent: run

#3929 handle 423 api error a trial license expiration
  cmd/context/create.go
  pkg/errors/errors.go
  pkg/okteto/auth.go
  pkg/okteto/auth_test.go
  pkg/okteto/client.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3953 add e2e using static token
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/context/update-kubeconfig.go
  cmd/context/update-kubeconfig_test.go
  integration/kubeconfig/kubeconfig_test.go
Labels: release/internal, echoes/intent: grow, run-e2e
