Repository okteto/okteto, pull requests merged in 2023-02, with the labels that each got.

#3369 Add HasReverse to metadata sent to metrics for `okteto up` command
  cmd/up/up.go
  pkg/analytics/track.go
Labels: release/internal, echoes/intent: run

#3365 switch to personal namespace if previous namespace is missing
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/context/options.go
  cmd/context/use.go
  cmd/namespace/use.go
Labels: new-contributor, release/bug-fix

#3373 improve spinner for remote deploy
  pkg/cmd/build/logger.go
Labels: release/internal, echoes/intent: grow

#3374 fix: omit auth error on build
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/authprovider_test.go
Labels: release/bug-fix, echoes/intent: fix

#3386 Jlopezbarb/upgrade syncthing to 1.23.1
  pkg/model/dev.go
  pkg/syncthing/install.go
Labels: release/internal, echoes/intent: run

#3385 Fixed bug of memory requests/reservations
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: release/bug-fix, echoes/intent: fix

#3375 Don't delete volume snapshot on DestroyWithLabel if -v flag is not set
  pkg/k8s/namespaces/namespace.go
Labels: release/bug-fix, echoes/intent: fix

#3390 trigger a new context store write
  cmd/context/use.go
Labels: release/internal, echoes/intent: fix

#3370 log a warning instead of prompting to ignore .git
  cmd/up/stignore.go
Labels: new-contributor, release/bug-fix

#3393 remote deploy/destroy improvements
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/internal, echoes/intent: run

#3397 feat: update to golang to 1.19.5
  .circleci/config.yml
  .golangci.yml
  Dockerfile
  contributing.md
  go.mod
Labels: release/internal, echoes/intent: run

#3384 Support for divert with Istio
  cmd/deploy/deploy.go
  cmd/destroy/destroy.go
  go.mod
  go.sum
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/divert/driver.go
  pkg/divert/istio/divert.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/istio/virtualservices_test.go
  pkg/divert/weaver/cache.go
  pkg/divert/weaver/cache_test.go
  pkg/divert/weaver/crd.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/divert_test.go
  pkg/divert/weaver/endpoints.go
  pkg/divert/weaver/ingresses.go
  pkg/divert/weaver/services.go
  pkg/k8s/virtualservices/client.go
  pkg/k8s/virtualservices/crud.go
  pkg/model/const.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/okteto/context.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3400 feat: merge remote deploy branch
  Dockerfile
  cmd/build/remote/build.go
  cmd/build/remote/build_test.go
  cmd/build/v2/environment.go
  cmd/context/utils_test.go
  cmd/deploy/cfghandler.go
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/kubeconfig.go
  cmd/deploy/local.go
  cmd/deploy/remote.go
  cmd/deploy/wait.go
  cmd/destroy/all.go
  cmd/destroy/cfghandler.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  cmd/destroy/local.go
  cmd/destroy/remote.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  cmd/utils/executor/executor.go
  cmd/utils/executor/json.go
  cmd/utils/git.go
  integration/commands/deploy.go
  integration/deploy/endpoints_test.go
  integration/deploy/manifest_test.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/logger.go
  pkg/constants/constants.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/okteto/k8s.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3411 fix issues from manual testing and remote deploy
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/local.go
  pkg/cmd/build/logger.go
  pkg/model/manifest.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.13
