Repository okteto/okteto, pull requests merged in 2023-04, with the labels that each got.

#3508 Added Platform to BuildOptions return of OptsFromBuildInfo
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/bug-fix, echoes/intent: fix

#3521 fix: duplicated logs on same stage
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/logger.go
Labels: release/bug-fix, echoes/intent: fix

#3534 fix .env removal locally
  cmd/deploy/local.go
  cmd/deploy/local_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3533 fix: adding .git folder to the folder should propagate okteto git commit
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  pkg/constants/constants.go
  pkg/model/const.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3538 [Backport 2.14]fix: adding .git folder to the folder should propagate okteto git com…
  cmd/deploy/command_configuration.go
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  pkg/constants/constants.go
  pkg/model/const.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/bug-fix, echoes/intent: fix

#3541 feat(build): improve missing cache error message
  .gitignore
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/log_filter.go
  pkg/cmd/build/log_filter_test.go
Labels: release/internal, echoes/intent: grow

#3545 Support for diverting a list of virtual services
  cmd/deploy/local.go
  cmd/destroy/local.go
  pkg/constants/constants.go
  pkg/divert/driver.go
  pkg/divert/istio/divert.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/istio/virtualservices_test.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/divert_test.go
  pkg/k8s/virtualservices/crud.go
  pkg/model/const.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/new-feature, echoes/intent: grow

#3544 Support for custom divert headers
  cmd/deploy/local.go
  cmd/destroy/local.go
  pkg/constants/constants.go
  pkg/divert/driver.go
  pkg/divert/istio/divert.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/istio/virtualservices_test.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/divert_test.go
  pkg/k8s/virtualservices/crud.go
  pkg/model/const.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/new-feature, echoes/intent: grow

#3529 remote output fixes
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/utils/displayer/json.go
  pkg/cmd/build/logger.go
  pkg/log/json.go
Labels: release/internal, echoes/intent: fix

#3550 fix(translate): use selector name if available
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
Labels: release/bug-fix, echoes/intent: fix

#3543 Apply divert transformation in the local deploy proxy
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/deploy/proxy.go
  cmd/destroy/local.go
  pkg/constants/constants.go
  pkg/divert/driver.go
  pkg/divert/istio/divert.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/istio/virtualservices_test.go
  pkg/divert/weaver/divert.go
  pkg/divert/weaver/divert_test.go
  pkg/k8s/virtualservices/crud.go
  pkg/model/const.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#3555 Always use baggage header name for istio divert driver
  pkg/constants/constants.go
  pkg/divert/istio/divert.go
  pkg/divert/istio/virtualservices.go
  pkg/divert/istio/virtualservices_test.go
  pkg/model/manifest.go
Labels: release/new-feature, echoes/intent: grow

#3557 fix: e2e test for remote deploy
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  contributing.md
  integration/deploy/manifest_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/constants/constants.go
Labels: release/internal, echoes/intent: fix

#3551 Added dev.okteto.com/namespace label to external resource objects when they are being created
  pkg/constants/constants.go
  pkg/externalresource/control.go
  pkg/externalresource/control_test.go
Labels: release/internal, echoes/intent: run

#3565 feat: deactivate git pull approach
  cmd/build/v2/build.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.14

#3559 Automatically create a namespace if needed while doing okteto up
  cmd/up/up.go
Labels: release/new-feature

#3360 Recreating pods in error state
  cmd/deploy/deploy.go
  cmd/deploy/local.go
  cmd/utils/okteto.go
  pkg/cmd/pipeline/translate.go
  pkg/log/log.go
Labels: release/new-feature

#3539 build empty `.dockerignore` in tmp dir for remote build if no `.oktetodeployignore` provided
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
Labels: release/bug-fix, echoes/intent: fix

#3547 Fix multicluster preview deploy
  cmd/context/create.go
  cmd/preview/deploy.go
  cmd/preview/destroy.go
  cmd/preview/endpoints.go
Labels: release/bug-fix, echoes/intent: fix

#3573 Modified the spinner text to mention about destroying dev env
  pkg/cmd/build/logger.go
Labels: release/bug-fix, echoes/intent: fix

#3561 load envs in cmap when deploy
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/deploy/local_test.go
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/pipeline/translate_test.go
  pkg/constants/constants.go
Labels: release/internal, echoes/intent: grow

#3568 Remove preview from deployPreview mutation response
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
Labels: no-dco, release/internal, echoes/intent: run

#3566 fix device resource parsing
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/const.go
Labels: new-contributor, release/bug-fix, echoes/intent: fix

#3574 Set the sleep and wake command to perform actions on current namespace
  cmd/namespace/sleep.go
  cmd/namespace/wake.go
Labels: release/new-feature
