Repository okteto/okteto, pull requests merged in 2023-11, with the labels that each got.

#4030 fix: panic on interrupt of deploy --remote
  cmd/deploy/deploy.go
Labels: no-dco, release/bug-fix, echoes/intent: fix, backport release-2.22

#4028 Adds add/delete to docker credentials helper
  pkg/auth/dockercredentials/helper.go
  pkg/auth/dockercredentials/helper_test.go
Labels: no-dco, release/bug-fix, echoes/intent: run

#4039 Added OKTETO_GIT_BRANCH environment variable to remote Dockerfile as argument to have it available in the commands executed there
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
Labels: release/new-feature, echoes/intent: run, backport release-2.22

#4041 fix:downgrade spinner module
  go.mod
  go.sum
Labels: release/bug-fix, echoes/intent: fix

#4043 Extract dev `secrets` and `envFiles` validation from serializer
  cmd/context/utils_test.go
  cmd/up/up.go
  cmd/utils/dev_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/volumes.go
Labels: no-dco, release/bug-fix, echoes/intent: run, run-e2e, backport release-2.22

#4046 [Backport release-2.22] Extract dev `secrets` and `envFiles` validation from serializer (#4043)
  cmd/context/utils_test.go
  cmd/up/up.go
  cmd/utils/dev_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/volumes.go
Labels: release/internal, echoes/intent: run

#4045 add quotes for variables added in remote
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
Labels: bug, release/bug-fix, echoes/intent: fix, run-e2e

#4050 Update Dockerfile to use kubectl 1.25.11
  Dockerfile
Labels: no-dco, release/internal, echoes/intent: run

#4048 show hint to deploy using remote feature
  cmd/deploy/deploy.go
Labels: release/internal, echoes/intent: run

#4053 CLI Quality - Lint - gci
  .golangci.yml
  cmd/build/command.go
  cmd/build/v1/build.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  cmd/context/create_test.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  cmd/exec.go
  cmd/namespace/sleep.go
  cmd/namespace/wake.go
  cmd/registrytoken/registrytoken.go
  cmd/restart.go
  cmd/up/exec.go
  cmd/up/up.go
  integration/commands/kubetoken.go
  main.go
  pkg/cache/cache_from_test.go
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/errors_test.go
  pkg/cmd/build/log_filter.go
  pkg/cmd/build/logger.go
  pkg/cmd/stack/translate.go
  pkg/externalresource/control.go
  pkg/externalresource/k8s/client.go
  pkg/externalresource/k8s/fake/fake_external_resource.go
  pkg/externalresource/k8s/fake/fake_external_resource_client.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/forward/manager.go
  pkg/k8s/ingresses/crud.go
  pkg/k8s/ingresses/crud_test.go
  pkg/k8s/ingressesv1/crud.go
  pkg/k8s/ingressesv1/crud_test.go
  pkg/k8s/kubeconfig/client.go
  pkg/k8s/statefulsets/crud.go
  pkg/k8s/volumes/crud.go
  pkg/k8s/volumes/crud_test.go
  pkg/model/manifest_test.go
  pkg/model/serializer_test.go
  pkg/model/translation_test.go
  pkg/okteto/client_test.go
  pkg/okteto/kubetoken_client.go
  pkg/okteto/secrets.go
  pkg/registry/registry_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/local_git.go
  pkg/suggest/rules.go
  pkg/syncthing/syncthing.go
Labels: no-dco, release/internal, echoes/intent: run

#4059 fix: linter (goheader)
  pkg/externalresource/k8s/client.go
Labels: release/internal, echoes/intent: run

#4049 Refactor: remove `CheckIfRegularFile` in favour of `filesystem.FileExistsAndNotDir`
  cmd/build/remote/build.go
  cmd/build/v1/build.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  pkg/cmd/build/build.go
  pkg/discovery/manifest.go
  pkg/filesystem/file.go
  pkg/filesystem/file_test.go
  pkg/model/contextresource.go
  pkg/model/dev.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: no-dco, release/internal, echoes/intent: run, run-e2e

#4060 fix: linter
  cmd/build/remote/build.go
  cmd/build/v1/build.go
  pkg/filesystem/file.go
  pkg/filesystem/file_test.go
  pkg/model/contextresource.go
  pkg/model/dev.go
  pkg/model/manifest_test.go
Labels: release/internal, echoes/intent: run

#4047 Refactor: create `env` and `dependencies` pkg to reduce `model` pkg and make testing easier
  cmd/build/v1/build.go
  cmd/build/v2/build.go
  cmd/context/create.go
  cmd/context/update-kubeconfig.go
  cmd/context/utils_test.go
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/deploy/validate.go
  cmd/destroy/cfghandler.go
  cmd/destroy/destroy.go
  cmd/preview/deploy_utils.go
  cmd/push.go
  cmd/stack/deploy.go
  cmd/up/exec_test.go
  cmd/up/stignore.go
  cmd/up/up.go
  cmd/up/up_test.go
  cmd/utils/executor/executor.go
  cmd/utils/okteto.go
  cmd/utils/stack_test.go
  pkg/analytics/up_test.go
  pkg/cmd/build/build.go
  pkg/cmd/doctor/run.go
  pkg/cmd/doctor/run_test.go
  pkg/cmd/stack/translate_test.go
  pkg/deps/deps.go
  pkg/deps/deps_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/files.go
  pkg/env/files_test.go
  pkg/env/var.go
  pkg/env/var_test.go
  pkg/linguist/dev.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/devrc.go
  pkg/model/devrc_test.go
  pkg/model/manifest.go
  pkg/model/manifest_friendly_err_test.go
  pkg/model/manifest_test.go
  pkg/model/schema_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/stack.go
  pkg/model/stack_expander.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
  pkg/model/stack_test.go
  pkg/model/translation.go
  pkg/model/translation_test.go
Labels: no-dco, release/internal, echoes/intent: run, run-e2e

#4052 fix: use okteto api to retrieve dev env endpoints
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/endpoints_test.go
  pkg/endpoints/control.go
  pkg/okteto/client.go
  pkg/okteto/endpoint.go
  pkg/okteto/endpoint_test.go
  pkg/okteto/preview_test.go
  pkg/types/interface.go
Labels: bug, release/bug-fix, echoes/intent: fix

#4066 fix linters errors for goheader and govet linters
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints_test.go
  pkg/endpoints/control.go
  pkg/okteto/endpoint.go
  pkg/okteto/endpoint_test.go
Labels: release/internal, echoes/intent: fix

#4063 CLI Quality - Lint- exhaustive
  .golangci.yml
  pkg/k8s/apps/deployments.go
  pkg/k8s/apps/statefulsets.go
  pkg/k8s/pods/pod.go
  pkg/k8s/services/crud_test.go
Labels: release/internal, echoes/intent: run

#4062 CLI Quality - Lint - durationcheck
  .golangci.yml
  cmd/up/syncthing.go
Labels: no-dco, release/internal, echoes/intent: run

#4057 CLI Quality - Lint - bodyclose
  .golangci.yml
  pkg/okteto/k8s_test.go
  pkg/okteto/kubetoken_client.go
  pkg/syncthing/api_test.go
Labels: no-dco, release/internal, echoes/intent: run

#4051 feat: add feature flag to enable context build
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/hasher.go
  cmd/build/v2/hasher_test.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/services.go
  cmd/build/v2/tagger_test.go
  pkg/registry/registry.go
Labels: no-dco, release/new-feature, echoes/intent: grow

#4064 CLI Quality - Lint- musttag
  .circleci/config.yml
  .golangci.yml
  pkg/deps/deps_test.go
  pkg/k8s/apps/utils.go
  pkg/model/contextresource.go
  pkg/model/dev.go
Labels: no-dco, release/internal, echoes/intent: run

#4061 CLI Quality - Lint - gomnd
  .golangci.yml
  cmd/deploy/local.go
  cmd/deploy/proxy.go
  cmd/deploy/validate.go
  cmd/destroy/build_control.go
  cmd/exec.go
  cmd/logs/logs.go
  cmd/pipeline/deploy.go
  cmd/preview/deploy.go
  cmd/registrytoken/registrytoken.go
  cmd/status.go
  cmd/up/activate.go
  cmd/up/dependencies.go
  cmd/up/syncthing.go
  cmd/up/up.go
  cmd/utils/selector.go
  cmd/utils/syncthing.go
  integration/k8s-client.go
  integration/okteto.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_docker.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/log_filter.go
  pkg/cmd/down/run.go
  pkg/cmd/init/run.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/status/run.go
  pkg/env/var.go
  pkg/k8s/forward/manager.go
  pkg/k8s/namespaces/namespace.go
  pkg/k8s/pods/pod.go
  pkg/k8s/volumes/crud.go
  pkg/log/spinner.go
  pkg/model/forward/forward_serializer.go
  pkg/model/forward/global_forward_serializer.go
  pkg/model/serializer.go
  pkg/model/stack_serializer.go
  pkg/model/utils.go
  pkg/okteto/context.go
  pkg/registry/image.go
  pkg/repository/local_git.go
  pkg/ssh/manager.go
  pkg/syncthing/completion.go
  pkg/syncthing/install.go
  pkg/syncthing/monitor.go
  pkg/syncthing/syncthing.go
Labels: no-dco, release/internal, echoes/intent: run

#4058 Add `make lint-fix-fieldalignment`
  Makefile
Labels: release/internal, echoes/intent: run

#4071 fix: ssh remote deploy tests
  .circleci/config.yml
Labels: release/internal, echoes/intent: fix, run-e2e-windows

#4069 Fix panic on okteto up with plain output
  cmd/utils/executor/plain.go
  cmd/utils/executor/plain_test.go
  pkg/log/log.go
  pkg/log/log_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.23

#4014 refactor: logger for build command
  Dockerfile
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/remote/build.go
  cmd/build/v1/build.go
  cmd/build/v1/build_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/environment.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/imagechecker_test.go
  cmd/build/v2/services.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/destroy/destroy.go
  cmd/destroy/remote.go
  cmd/manifest/init-v2.go
  cmd/push.go
  cmd/stack/deploy.go
  cmd/stack/stack.go
  cmd/up/up.go
  cmd/up/up_test.go
  go.mod
  go.sum
  integration/commands/deploy.go
  internal/test/build.go
  main.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/translate.go
  pkg/log/io/decorator.go
  pkg/log/io/decorator_test.go
  pkg/log/io/formatter.go
  pkg/log/io/formatter_test.go
  pkg/log/io/in.go
  pkg/log/io/io.go
  pkg/log/io/io_test.go
  pkg/log/io/logger.go
  pkg/log/io/logger_test.go
  pkg/log/io/logrus.go
  pkg/log/io/logrus_test.go
  pkg/log/io/out.go
  pkg/log/io/out_test.go
  pkg/log/io/spinner.go
  pkg/log/io/spinner_test.go
Labels: no-dco, release/internal, echoes/intent: grow, run-e2e

#4074 Fix connection issues to dev containers using vscode remote ssh
  pkg/k8s/apps/translate_test.go
  pkg/model/dev.go
  pkg/model/translation_test.go
Labels: release/bug-fix, echoes/intent: fix

#4076 fix external resource markdown able to generate it dinamycally using …
  cmd/deploy/local.go
  pkg/model/manifest.go
Labels: release/bug-fix, echoes/intent: fix
