Repository okteto/okteto, pull requests merged in 2023-06, with the labels that each got.

#3682 fix: endpoints should only return the json if the flag specify it
  cmd/preview/endpoints.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.16

#3688 Fix variables deploy installer
  cmd/deploy/cfghandler.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/local.go
  pkg/cmd/pipeline/translate.go
  pkg/types/deploy.go
  pkg/types/deploy_test.go
Labels: release/bug-fix, echoes/intent: fix, backport release-2.16

#3689 fix: variable expansion on buildargs that only have one env
  cmd/build/v2/config_test.go
  go.mod
  go.sum
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, echoes/intent: fix

#3694 Revert "Fix variables deploy installer"
  cmd/deploy/cfghandler.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/local.go
  cmd/destroy/local_test.go
  pkg/cmd/pipeline/translate.go
  pkg/types/deploy.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3695 Support for node selector in the docker-compose spec
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
  pkg/model/stack_test.go
Labels: release/new-feature, echoes/intent: grow

#3693 Revert "Restore "Okteto kubeconfig will use kubetoken client auth if available on okteto server"""
  .circleci/config.yml
  Makefile
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/namespace/create_test.go
  go.mod
  go.sum
  integration/actions/apply_test.go
  integration/commands/preview.go
  integration/commands/push.go
  integration/commands/stacks.go
  pkg/model/port.go
  pkg/okteto/client.go
  pkg/okteto/context.go
  pkg/okteto/context_test.go
  pkg/types/credential.go
Labels: no-dco, release/internal

#3680 chore: make git logs debug lvl
  pkg/repository/git.go
Labels: release/internal, echoes/intent: run

#3705 Call parent PersistentPreRun instead of root
  cmd/context/context.go
Labels: release/bug-fix, echoes/intent: fix

#3706 Show error if deploying services with persistentVolume as `disabled`
  cmd/up/activate.go
Labels: no-dco, release/bug-fix, echoes/intent: fix

#3712 update golang-ci at circleci config
  .circleci/config.yml
Labels: release/internal, echoes/intent: run

#3714 Revert "update golang-ci at circleci config"
  .circleci/config.yml
Labels: no-dco, release/internal, echoes/intent: run

#3715 update config with new builder and version of golang-ci
  .circleci/config.yml
Labels: release/internal, echoes/intent: run

#3711 feat: add label flag to preview list cmd
  cmd/preview/list.go
  cmd/utils/okteto.go
  internal/test/client/preview.go
  pkg/okteto/client.go
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
  pkg/types/interface.go
  pkg/types/preview.go
Labels: release/new-feature, echoes/intent: grow

#3716 Revert "update config with new builder and version of golang-ci"
  .circleci/config.yml
Labels: no-dco, release/internal, echoes/intent: run

#3703 Fix depends on when loading stack from file
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/stack.go
Labels: release/bug-fix, echoes/intent: fix

#3723 Don't copy ca-certs on deploy image
  cmd/deploy/remote.go
  cmd/destroy/remote.go
Labels: release/internal, echoes/intent: run

#3725 Use ARG instead of ENV to pass metadata for "--remote"
  cmd/build/v2/build.go
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/destroy.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  cmd/utils/executor/executor.go
  pkg/constants/constants.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/internal, echoes/intent: run

#3726 Always create ".dockerignore" for "okteto destroy"
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
Labels: release/bug-fix, echoes/intent: run

#3732 Propagate "--wait" and "--timeout" flags to "okteto deploy --remote"
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
Labels: release/bug-fix, echoes/intent: fix

#3683 gracefull shutdown for hybrid process
  cmd/exec.go
  cmd/up/activate.go
  cmd/up/exec.go
  cmd/up/exec_unix.go
  cmd/up/exec_windows.go
  cmd/up/types.go
  cmd/up/up.go
Labels: no-dco, release/internal, echoes/intent: fix

#3729 Removed feature for automatically export/import the build cache
  pkg/cache/cache_from.go
  pkg/cache/cache_from_test.go
  pkg/cache/export_cache.go
  pkg/cache/export_cache_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/internal, echoes/intent: fix

#3740 docs(helper): improve description of label flag
  cmd/preview/list.go
Labels: release/internal, echoes/intent: grow

#3736 Fix silent error when build images as part of "okteto deploy"
  cmd/deploy/deploy.go
Labels: release/bug-fix, echoes/intent: fix

#3707 fix: no optional locks on git read only commands
  pkg/repository/local_git.go
Labels: no-dco, release/internal, echoes/intent: fix

#3742 Update hybrid analytics
  cmd/exec.go
  cmd/up/up.go
  pkg/analytics/track.go
  pkg/constants/constants.go
  pkg/model/dev.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer_test.go
Labels: release/internal, echoes/intent: grow

#3722 Update the log message when no endpoints are available
  cmd/deploy/endpoints.go
Labels: release/internal, echoes/intent: run

#3749 Fix integration hybrid
  cmd/up/exec_unix.go
  cmd/up/up.go
  integration/commands/dev.go
Labels: release/bug-fix, echoes/intent: fix

#3606 Fix kubetoken usage message
  cmd/kubetoken/kubetoken.go
Labels: keep, release/internal

#3747 Remove git credentials from debug logs
  pkg/devenvironment/name.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/bug-fix, echoes/intent: fix

#3757 Improve "cannot create pid" error message
  cmd/up/up.go
Labels: release/internal, echoes/intent: grow

#3762 Jlopezbarb/fix-security-issues
  Dockerfile
  go.mod
  go.sum
Labels: release/internal, echoes/intent: run, backport release-2.17

#3765 Add "scope" to the `okteto preview deploy` command metric
  cmd/preview/deploy.go
  pkg/analytics/track.go
Labels: release/internal, echoes/intent: run

#3754 add envs from manifest to local process
  cmd/up/exec.go
  cmd/up/exec_test.go
  pkg/model/serializer.go
Labels: release/bug-fix, echoes/intent: fix
