Repository okteto/okteto, pull requests merged in 2024-12, with the labels that each got.

#4589 feat: get cli image from cluster metadata
  pkg/config/image.go
  pkg/config/image_test.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/types/cluster_metadata.go
Labels: release/new-feature

#4594 chore: remove deprecated dependency
  go.mod
  go.sum
  pkg/cmd/doctor/run.go
Labels: release/internal

#4596 chore: update dependencies to patches versions in Dockerfile and go.mod
  .circleci/config.yml
  Dockerfile
  go.mod
  pkg/syncthing/install.go
Labels: release/internal, backport release-3.2

#4601 feat: add FSGroup to PodSecurityContext in StatefulSet translation
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: release/internal, backport release-3.2

#4604 chore: update google.golang.org/grpc to v1.66.3 and replace buildkit dependency version
  go.mod
  go.sum
Labels: release/internal, backport release-3.2

#4609 fix bug compose deploy sts
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
Labels: release/bug-fix, backport release-3.2

#4611 Update Okteto Manifest JSON Schema Title and Description
  pkg/schema/schema.go
  schema.json
Labels: release/internal

#4600 Remove depot dependency
  .circleci/config.yml
  go.mod
  go.sum
  integration/build/build_test.go
  integration/commands/build.go
  integration/deploy/manifest_test.go
  integration/deploy/remote_test.go
  pkg/build/buildkit/errors.go
  pkg/build/buildkit/errors_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/internal, run-e2e

#4614 DEV-828: Don't allow execution of empty tests names
  cmd/test/cmd.go
Labels: release/bug-fix, run-e2e, backport release-3.2

#4615 revert: rootless image
  Dockerfile
Labels: release/internal, run-e2e, backport release-3.2

#4613 [JSON Schema] Add `deploy.compose` object notation
  pkg/schema/deploy.go
  schema.json
Labels: release/internal

#4617 Added execution of integration tests for okteto test command
  .circleci/config.yml
  Makefile
  integration/commands/test.go
  integration/test/test_test.go
Labels: release/internal, run-e2e

#4595 Enhance healthcheck failure handling and logging
  pkg/cmd/stack/deploy.go
  pkg/errors/errors.go
  pkg/k8s/events/crud.go
  pkg/k8s/pods/pod.go
Labels: release/bug-fix

#4620 Fix error image tag and hint message
  pkg/build/buildkit/errors.go
  pkg/build/buildkit/errors_test.go
Labels: release/bug-fix

#4627 Skip min CLI version check for CircleCI
  .circleci/config.yml
Labels: release/internal, run-e2e

#4623 Update contributing docs for json schema
  .github/pull_request_template.md
  Makefile
  contributing.md
Labels: release/internal

#4630 revert: restore kustomize in the cli binary
  Dockerfile
Labels: release/bug-fix, backport release-3.2

#4583 Update the pre-commit config; Fix linting errors
  .gitignore
  .mdlrc
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  cmd/destroy/destroy.go
  cmd/up/activate.go
  pkg/constants/constants.go
  scripts/start.sh
Labels: release/internal

#4631 chore: update buildkit dependency to 0.18.2
  go.mod
  go.sum
Labels: release/internal

#4625 Add kubetoken and kubeconfig integration tests to e2e tests
  integration/commands/kubeconfig.go
  integration/commands/kubetoken.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  integration/deploy/external_test.go
  integration/deploy/helm_test.go
  integration/deploy/k8s_manifest_test.go
  integration/deploy/manifest_test.go
  integration/deploy/pipeline_test.go
  integration/deploy/smartbuild_test.go
  integration/deploy/variables_test.go
  integration/okteto/autowake_test.go
  integration/okteto/dependencies_test.go
  integration/okteto/deploy_test.go
  integration/okteto/kubeconfig_test.go
  integration/okteto/kubetoken_test.go
  integration/okteto/pipeline_test.go
  integration/test/test_test.go
  integration/up/autocreate_test.go
  integration/up/compose_test.go
  integration/up/compose_with_okteto_manifest_test.go
  integration/up/deploy_remote_test.go
  integration/up/deploy_test.go
  integration/up/deployment_test.go
  integration/up/exec_test.go
  integration/up/globalforward_test.go
  integration/up/hybridmode_test.go
  integration/up/statefulset_test.go
Labels: release/internal, run-e2e

#4624 Add integration tests for `validate` and `generate-schema`
  integration/commands/generate_schema.go
  integration/commands/validate.go
  integration/okteto/generate_schema_test.go
  integration/validate/manifests/invalid-dev.yml
  integration/validate/manifests/invalid-empty.yml
  integration/validate/manifests/invalid-non-existing-root-level-prop.yml
  integration/validate/manifests/invalid-syntax.yml
  integration/validate/manifests/valid-aws-lambda-with-terraform.yml
  integration/validate/manifests/valid-gcp-cloud-credentials.yml
  integration/validate/manifests/valid-go-getting-started-chart.yml
  integration/validate/manifests/valid-go-getting-started.yml
  integration/validate/manifests/valid-movies-frontend.yml
  integration/validate/manifests/valid-movies-multi-repo.yml
  integration/validate/manifests/valid-movies-rental.yml
  integration/validate/manifests/valid-movies.yml
  integration/validate/manifests/valid-okteto-load-testing-with-artillery.yml
  integration/validate/manifests/valid-tacopshop-with-cloudflare.yml
  integration/validate/validate_test.go
  pkg/schema/schema_test.go
Labels: release/internal, run-e2e

#4629 DEV-834: Fixed scenario where an okteto deploy executed within a manifest with remote flag wasn't getting correctly the variables
  cmd/deploy/deploy.go
  integration/deploy/deploy_remote_test.go
Labels: release/bug-fix, run-e2e

#4621 Refactor json schema ToJSON to simplify code
  cmd/generate-schema.go
  cmd/validate.go
  pkg/schema/build_test.go
  pkg/schema/deploy_test.go
  pkg/schema/destroy_test.go
  pkg/schema/external_test.go
  pkg/schema/forward_test.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/schema/test_test.go
  schema.json
Labels: release/internal
