Repository okteto/okteto, pull requests merged in 2024-04, with the labels that each got.

#4214 fix: run remote on buildkit
  integration/deploy/manifest_test.go
  pkg/cmd/build/build.go
Labels: release/bug-fix, run-e2e-unix

#4211 DEV-188: Refactor destroy command to follow same pattern used for deploy
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/deploy/validate.go
  cmd/destroy/all.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  cmd/destroy/local.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  cmd/remoterun/command.go
  cmd/remoterun/command_test.go
  cmd/remoterun/deploy.go
  cmd/remoterun/deploy_test.go
  cmd/remoterun/destroy.go
  cmd/remoterun/destroy_test.go
  cmd/up/up.go
  internal/test/client/user.go
  pkg/constants/constants.go
  pkg/deployable/deploy.go
  pkg/deployable/deploy_test.go
  pkg/deployable/destroy.go
  pkg/deployable/destroy_test.go
  pkg/env/var.go
  pkg/model/const.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/internal, run-e2e-windows, run-e2e, run-e2e-unix

#4220 Init dag package
  go.mod
  go.sum
  pkg/dag/dag.go
  pkg/dag/dag_test.go
  pkg/dag/doc.go
Labels: no-dco, release/internal

#4218 Do not execute local or remote destroy if no commands within destroy section is defined
  cmd/destroy/destroy.go
Labels: release/internal, run-e2e-windows, run-e2e, run-e2e-unix

#4219 DEV-258: Changed command used to get the latest commit for a folder
  cmd/build/v2/build.go
  cmd/build/v2/config.go
  cmd/build/v2/config_test.go
  cmd/build/v2/smartbuild/hasher.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/bug-fix, run-e2e-windows, run-e2e, run-e2e-unix

#4205 feat: add events for build using manifest
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/environment_test.go
  cmd/build/v2/services_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  cmd/init.go
  cmd/manifest/init-v2.go
  cmd/pipeline/deploy_test.go
  cmd/stack/deploy.go
  cmd/stack/stack.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/up/up_test.go
  main.go
  pkg/analytics/imagebuild.go
  pkg/analytics/imagebuild_test.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/translate.go
  pkg/insights/build.go
  pkg/insights/build_test.go
  pkg/insights/insights.go
  pkg/insights/insights_test.go
  pkg/k8s/events/crud.go
  pkg/repository/git.go
  pkg/repository/remote.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/new-feature

#4216 Initialize test command
  cmd/deploy/build.go
  cmd/deploy/build_test.go
  cmd/deploy/cfghandler.go
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/pipeline/deploy.go
  cmd/test/cmd.go
  cmd/test/dag.go
  cmd/test/lib.go
  main.go
  pkg/dag/dag.go
  pkg/model/manifest.go
  pkg/model/manifest_friendly_err_test.go
  pkg/model/manifest_test.go
  pkg/model/schema_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/test.go
Labels: no-dco, release/new-feature

#4221 fix: e2e test
  cmd/stack/deploy.go
  cmd/stack/stack.go
  main.go
Labels: release/bug-fix, run-e2e

#4222 refactor: change json to snake case
  pkg/insights/build.go
Labels: release/internal

#4217 feat: add variable expansion in manifest.build.dockerfile
  pkg/build/info.go
  pkg/build/info_test.go
Labels: release/new-feature

#4206 feat: add deploy insights
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  cmd/destroy/build_control_test.go
  cmd/init.go
  cmd/manifest/init-v2.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/pipeline/translate_test.go
  pkg/deployable/deploy.go
  pkg/deployable/deploy_test.go
  pkg/insights/build.go
  pkg/insights/deploy.go
  pkg/insights/deploy_test.go
  pkg/insights/insights.go
  pkg/insights/insights_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: no-dco, release/new-feature, run-e2e, backport release-2.26

#4226 dep: update syncthing dependency
  pkg/model/dev.go
  pkg/syncthing/install.go
Labels: release/internal, backport release-2.26

#4229 fix: log on ui
  pkg/deployable/deploy.go
Labels: release/bug-fix, backport release-2.26

#4234 Update message and link to recommend remote execution
  cmd/deploy/deploy.go
Labels: release/internal, backport release-2.26

#4231 fix: skip volume mount translation into okteto manifest build
  pkg/model/manifest.go
Labels: release/bug-fix, backport release-2.26

#4237 fix: repo with double url
  pkg/repository/git.go
  pkg/repository/git_test.go
Labels: release/bug-fix, backport release-2.26

#4233 remove translateCacheHandler func from build pkg
  pkg/cmd/build/file.go
  pkg/cmd/build/file_test.go
Labels: release/internal

#4239 Support variable expansion in `.env`: `"VAR1=${VAR2:-default}"`
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/context/use.go
Labels: release/new-feature

#4232 [okteto test] Don't deploy if app already exists
  cmd/deploy/command_configuration.go
  cmd/test/cmd.go
Labels: release/internal

#4246 update e2e tests due to changes in variables masking logic
  integration/commands/deploy.go
  integration/deploy/variables_test.go
  integration/okteto/deploy_test.go
Labels: release/internal, run-e2e

#4248 Persist okteto env between deploy and test
  cmd/remoterun/command.go
  cmd/remoterun/test.go
  cmd/remoterun/test_test.go
  cmd/test/cmd.go
  pkg/cmd/pipeline/translate.go
  pkg/deployable/deploy.go
  pkg/deployable/env_stepper.go
  pkg/deployable/env_stepper_test.go
  pkg/deployable/test.go
  pkg/deployable/test_test.go
Labels: release/internal

#4249 fix push script
  scripts/ci/push-image.sh
Labels: release/bug-fix, backport release-2.26

#4252 chore: add devcontainer to gitignore
  .gitignore
Labels: release/internal

#4256 Fix linting errors in master (samples, etc)
  .pre-commit-config.yaml
  README.md
  cmd/test/cmd.go
  samples/README.md
  samples/aspnetcore/Controllers/HelloWorldController.cs
  samples/aspnetcore/Properties/launchSettings.json
  samples/aspnetcore/README.md
  samples/aspnetcore/appsettings.Development.json
  samples/aspnetcore/appsettings.json
  samples/aspnetcore/k8s.yml
  samples/aspnetcore/obj/helloworld.csproj.nuget.dgspec.json
  samples/aspnetcore/obj/helloworld.csproj.nuget.g.props
  samples/aspnetcore/obj/helloworld.csproj.nuget.g.targets
  samples/aspnetcore/obj/project.assets.json
  samples/aspnetcore/obj/project.nuget.cache
  samples/aspnetcore/okteto.yml
  samples/golang/Dockerfile
  samples/golang/Makefile
  samples/golang/README.md
  samples/golang/bashrc
  samples/golang/k8s.yml
  samples/java-gradle/README.md
  samples/java-gradle/build.gradle
  samples/java-gradle/k8s.yml
  samples/java-gradle/src/main/java/com/okteto/helloworld/RestHelloWorld.java
  samples/java-gradle/src/main/resources/application.properties
  samples/java-maven/README.md
  samples/java-maven/k8s.yml
  samples/java-maven/mvnw.cmd
  samples/java-maven/src/main/java/com/okteto/helloworld/RestHelloWorld.java
  samples/java-maven/src/main/resources/application.properties
  samples/node.js/README.md
  samples/node.js/index.js
  samples/node.js/k8s.yml
  samples/node.js/package.json
  samples/php/.stignore
  samples/php/Dockerfile
  samples/php/composer.json
  samples/php/index.php
  samples/php/info.php
  samples/php/k8s.yml
  samples/php/xdebug.ini
  samples/python/k8s.yml
  samples/python/requirements.txt
  samples/ruby/.dockerignore
  samples/ruby/Gemfile
  samples/ruby/README.md
  samples/ruby/app.rb
  samples/ruby/bashrc
  samples/ruby/k8s.yml
Labels: release/internal

#4250 Okteto Test Spike
  cmd/build/v2/services.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/destroy/destroy_test.go
  cmd/test/analytics.go
  cmd/test/cmd.go
  pkg/analytics/imagebuild.go
  pkg/analytics/imagebuild_test.go
  pkg/analytics/test.go
  pkg/analytics/test_test.go
  pkg/model/manifest.go
  pkg/model/schema_test.go
  pkg/model/test.go
  pkg/remote/remote.go
Labels: release/internal

#4262 `okteto up`: display warning when available disk space is running low
  cmd/up/syncthing.go
  pkg/syncthing/syncthing.go
Labels: release/new-feature

#4257 Move from concept of "Secret" to "Variable"
  cmd/context/create.go
  cmd/context/use.go
  cmd/context/use_test.go
  cmd/up/exec.go
  cmd/up/exec_test.go
  internal/test/client/user.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
  pkg/types/interface.go
  pkg/types/secret.go
  pkg/types/user_context.go
Labels: release/internal, run-e2e

#4263 fix: hash on untracked folders
  pkg/repository/git.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
  pkg/repository/repository_test.go
Labels: release/bug-fix

#4265 Don't read nor persist OKTETO_ENV in test cmd
  cmd/remoterun/command.go
  cmd/remoterun/test.go
  pkg/deployable/test.go
  pkg/deployable/test_test.go
Labels: release/internal

#4254 feat: deprecate compose file detection by naming
  cmd/utils/stack_test.go
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/new-feature

#4251 mask multiline variables
  pkg/log/log.go
Labels: release/new-feature, run-e2e

#4267 Add targets to test command
  cmd/test/cmd.go
  pkg/dag/dag.go
  pkg/dag/dag_test.go
Labels: release/internal

#4225 chore: deprecation warning for manifest context & namespace
  pkg/model/contextresource.go
Labels: release/internal

#4276 Add test action to CLI release
  scripts/ci/release-github-actions.sh
  scripts/set_latest_actions.sh
Labels: release/internal
