Repository okteto/okteto, pull requests merged in 2024-08, with the labels that each got.

#4415 feat: add last okteto up branch on cmap
  cmd/up/activate.go
  pkg/cmd/pipeline/translate.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/repository/git.go
  pkg/repository/repository.go
Labels: release/internal, backport release-2.30

#4402 feat: validate manifest before executing a command
  cmd/doctor.go
  cmd/down.go
  cmd/exec/cmd.go
  cmd/restart.go
  cmd/status.go
  cmd/up/up.go
  pkg/build/manifest_section.go
  pkg/build/manifest_section_test.go
  pkg/deps/deps.go
  pkg/externalresource/external_resource.go
  pkg/externalresource/external_resource_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/internal, 3.0, run-e2e

#4418 Update windows executors to pinned version
  .circleci/config.yml
Labels: release/internal, run-e2e-windows

#4421 Fix 3.0 build after merge from master
  cmd/up/activate.go
Labels: release/internal, 3.0, run-e2e

#4414 feat: refactor syntax for lifecycle
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/schema_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/new-feature

#4420 Update README.md to make the difference of CLIs clearer
  README.md
Labels: community, release/internal, enhancement

#4425 Cherrypick deleted commit (466)
  cmd/context/use.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/context.go
  pkg/okteto/context_stateless.go
Labels: release/internal

#4424 Cherrypick deleted commit (465)
  cmd/build/command.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/kubetoken/kubetoken.go
  cmd/kubetoken/kubetoken_test.go
  cmd/logs/logs.go
  cmd/namespace/create.go
  cmd/namespace/use.go
  cmd/namespace/wake.go
  cmd/preview/endpoints.go
  cmd/remoterun/deploy.go
  cmd/remoterun/destroy.go
  cmd/remoterun/test.go
  cmd/test/cmd.go
  pkg/errors/errors.go
Labels: release/internal

#4426 DEV-575: Fix UpdateEnvs function to allow variable values with '='
  pkg/cmd/pipeline/translate.go
  pkg/cmd/pipeline/translate_test.go
  pkg/deployable/deploy.go
  pkg/log/json.go
Labels: release/bug-fix, backport release-2.30

#4423 Prevent logs to be written from registry credential
  cmd/kubetoken/kubetoken.go
  main.go
  pkg/log/io/logger.go
  pkg/log/io/logrus.go
Labels: release/bug-fix

#4384 Merge build.name and build.image in Manifest
  cmd/context/utils_test.go
  pkg/build/info.go
  pkg/build/info_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/schema_test.go
  pkg/model/serializer_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
  pkg/model/stack_test.go
Labels: release/internal, 3.0, run-e2e

#4422 Return success when destroy/delete preview/namespace and err is not found
  cmd/namespace/delete.go
  cmd/namespace/delete_test.go
  cmd/preview/destroy.go
  cmd/preview/destroy_test.go
Labels: release/new-feature, run-e2e

#4430 fix: cve for helm
  Dockerfile
Labels: release/internal

#4431 remove unused func getRepoNameFromGitURL in pkg/deps
  pkg/deps/deps.go
  pkg/deps/deps_test.go
Labels: release/internal

#4432 fix smartbuild nested scenario
  cmd/build/v2/build.go
Labels: release/bug-fix, backport release-2.30

#4435 Add EC encryption to `okteto up`
  pkg/model/dev.go
  pkg/ssh/key.go
  pkg/ssh/key_test.go
  pkg/ssh/ssh.go
Labels: release/bug-fix

#4436 feat: Add env vars wit prefix OKTETO_ENV
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/new-feature
