Repository okteto/okteto, pull requests merged in 2024-03, with the labels that each got.

#4195 fix: clean manifest path in remote deploy to fix regression
  cmd/build/v1/build.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  pkg/filesystem/manifest.go
  pkg/filesystem/manifest_test.go
Labels: release/bug-fix, run-e2e, backport release-2.25

#4198 DEV-186: Refactor deploy remote command to execute the minimum in the remote
  .circleci/config.yml
  cmd/deploy/build.go
  cmd/deploy/build_test.go
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/local.go
  cmd/deploy/local_test.go
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/local.go
  cmd/manifest/init-v2.go
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/remoterun/command.go
  cmd/remoterun/command_test.go
  cmd/stack/deploy.go
  cmd/up/up.go
  integration/deploy/external_test.go
  integration/okteto/dependencies_test.go
  main.go
  pkg/cmd/pipeline/translate.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/constants/constants.go
  pkg/deployable/certs.go
  pkg/deployable/kubeconfig.go
  pkg/deployable/proxy.go
  pkg/deployable/proxy_test.go
  pkg/deployable/runner.go
  pkg/deployable/runner_test.go
  pkg/divert/driver.go
  pkg/divert/istio/divert.go
  pkg/divert/noop/divert.go
  pkg/divert/weaver/divert.go
  pkg/externalresource/serializer.go
Labels: no-dco, release/internal, run-e2e-windows, run-e2e, run-e2e-unix

#4201 [Backport][2.25] Manifest path fixes for remote deploy
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/filesystem/manifest.go
  pkg/filesystem/manifest_test.go
Labels: release/bug-fix, run-e2e

#4196 feat: add okteto local credentials by env var
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/authprovider_test.go
  pkg/registry/client.go
Labels: release/new-feature, run-e2e-unix

#4207 Don't add extra hosts for remote deploy w/ depot
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  pkg/cmd/build/build.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
Labels: no-dco, release/internal

#4210 Remove "Build section is not defined in your okteto manifest" info me…
  cmd/build/v2/services.go
Labels: no-dco, release/bug-fix

#4203 Smart Build fixes and improvements
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/environment_test.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/build/v2/smartbuild/hasher.go
  cmd/build/v2/smartbuild/hasher_test.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  cmd/context/use.go
  cmd/deploy/build.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/remote.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/destroy/remote.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/up/up_test.go
  integration/build/build_test.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  integration/deprecated/stack/compose_test.go
  integration/okteto/dependencies_test.go
  integration/okteto/deploy_test.go
  integration/up/compose_test.go
  pkg/build/manifest_section.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/constants.go
  pkg/cmd/build/file.go
  pkg/cmd/build/logger.go
  pkg/cmd/stack/translate.go
  pkg/log/io/out.go
  pkg/model/const.go
  pkg/okteto/context_stateless.go
  pkg/registry/image.go
  pkg/registry/image_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
Labels: release/bug-fix, run-e2e-windows, run-e2e, run-e2e-unix

#4204 [Compose] Allow setting K8S labels from `docker-compose.yml`
  integration/deploy/compose_test.go
  integration/k8s-client.go
  pkg/cmd/stack/translate.go
  pkg/model/stack_serializer.go
  pkg/model/stack_serializer_test.go
Labels: no-dco, release/new-feature, run-e2e
