Repository okteto/okteto, pull requests merged in 2024-06, with the labels that each got.

#4321 remove unused code
  cmd/build/v2/build.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/down.go
  cmd/stack/deploy.go
  cmd/stack/destroy.go
  cmd/test/cmd.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  pkg/cmd/pipeline/translate.go
  pkg/discovery/compose.go
  pkg/discovery/helm.go
  pkg/discovery/k8s.go
  pkg/discovery/pipeline.go
  pkg/errors/errors.go
  pkg/filesystem/manifest.go
  pkg/filesystem/manifest_test.go
  pkg/filesystem/workdir.go
  pkg/filesystem/workdir_test.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/statefulsets/crud.go
  pkg/model/const.go
  pkg/model/file.go
  pkg/model/file_test.go
  pkg/model/manifest.go
  pkg/model/stack.go
Labels: release/internal, run-e2e

#4327 fix: CVE-2023-47108
  go.mod
  go.sum
Labels: release/internal, run-e2e, backport release-2.28

#4326 fix: use the correct image on okteteo test
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/deploy/build.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/build_control.go
  cmd/destroy/build_control_test.go
  cmd/test/cmd.go
  cmd/test/cmd_test.go
  cmd/up/types.go
  cmd/up/up.go
  cmd/up/up_test.go
  pkg/build/manifest_section.go
  pkg/build/manifest_section_test.go
  pkg/cmd/stack/translate.go
  pkg/model/utils/utils.go
  pkg/model/utils/utils_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, backport release-2.28

#4329 fix: only use requirements from yaml
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
Labels: release/bug-fix

#4331 Reserved variable names
  cmd/deploy/deploy.go
  cmd/deploy/validate.go
  cmd/deploy/validate_test.go
  cmd/pipeline/deploy.go
  cmd/preview/deploy_utils.go
  cmd/preview/deploy_utils_test.go
  cmd/test/cmd.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: release/internal

#4333 Preview deploy scope to default global
  cmd/preview/deploy.go
  integration/commands/preview.go
Labels: release/internal, run-e2e

#4335 fix: build friendly err
  pkg/model/manifest_friendly_err.go
Labels: release/internal

#4270 fix: clone images on specified services
  cmd/build/basic/build.go
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/imagechecker.go
  cmd/build/v2/imagechecker_test.go
  cmd/build/v2/services.go
  cmd/build/v2/services_test.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  cmd/deploy/deploy_test.go
  cmd/remoterun/deploy.go
  cmd/remoterun/destroy.go
  cmd/remoterun/test.go
  internal/test/build.go
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/context.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
  pkg/cmd/build/file.go
  pkg/okteto/context_stateless.go
  pkg/registry/image.go
  pkg/registry/image_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/types/build.go
Labels: release/bug-fix

#4338 feat: configure ci for 3.0
  .circleci/config.yml
Labels: release/new-feature, 3.0

#4341 remove `create/list/delete namespace`
  cmd/create.go
  cmd/delete.go
  cmd/list.go
  integration/commands/namespace.go
  main.go
Labels: release/internal, 3.0, run-e2e-unix

#4339 remove okteto push
  .circleci/config.yml
  Makefile
  cmd/manifest/init-v1_test.go
  cmd/push.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  integration/actions/push_test.go
  integration/commands/push.go
  integration/deprecated/push/push_test.go
  main.go
  pkg/analytics/track.go
  pkg/cmd/doctor/run.go
  pkg/devenvironment/name.go
  pkg/errors/errors.go
  pkg/k8s/apps/crud.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/schema_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  scripts/set_latest_actions.sh
Labels: release/new-feature, 3.0

#4348 Added transient error to retry on build operation
  pkg/cmd/build/errors.go
  pkg/cmd/build/errors_test.go
Labels: release/internal

#4334 Generate artifacts in `okteto test` including when tests fail
  integration/commands/test.go
  integration/test/test_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/new-feature, run-e2e

#4349 refactor: remove --builder in context use
  cmd/context/context.go
  cmd/context/create.go
  cmd/context/options.go
  cmd/context/use.go
  cmd/context/utils.go
  pkg/okteto/context.go
Labels: release/internal, 3.0

#4336 fix: okteto test to use always root user
  cmd/test/cmd.go
  integration/test/test_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, run-e2e

#4337 fix: rebuilding for already created image
  cmd/test/cmd.go
Labels: release/bug-fix

#4345 remove okteto cloud mentions
  cmd/context/context_test.go
  cmd/context/create_test.go
  cmd/context/list.go
  cmd/context/selector.go
  cmd/context/use.go
  cmd/up/up.go
  integration/actions/actions_test.go
  integration/actions/context_test.go
  integration/actions/login_test.go
  integration/build/build_test.go
  integration/deploy/deploy_test.go
  integration/deprecated/push/push_test.go
  integration/deprecated/stack/stack_test.go
  integration/okteto/okteto_test.go
  integration/up/up_test.go
  pkg/analytics/config.go
  pkg/analytics/track.go
  pkg/analytics/track_test.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
  pkg/okteto/client_test.go
  pkg/okteto/cloud.go
  pkg/okteto/context.go
  pkg/okteto/context_test.go
  pkg/okteto/k8s_test.go
Labels: release/internal, run-e2e-unix

#4351 ignore stack syntax by default
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/internal, 3.0

#4350 remove `okteto init`
  cmd/init.go
  cmd/manifest/init-v1.go
  cmd/manifest/init-v1_test.go
  cmd/manifest/init-v2.go
  cmd/manifest/selector.go
  cmd/manifest/selector_test.go
  cmd/up/stignore.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/stack.go
  main.go
  pkg/analytics/track.go
  pkg/cmd/down/down.go
  pkg/cmd/init/run.go
  pkg/cmd/init/run_test.go
  pkg/errors/errors.go
  pkg/k8s/pods/pod.go
  pkg/k8s/services/crud.go
  pkg/linguist/dev.go
Labels: release/internal, 3.0

#4353 feat: up --deploy always build the latest changes
  cmd/up/up.go
Labels: release/internal, 3.0

#4332 Show test command when running 'okteto --help'
  cmd/test/cmd.go
  main.go
Labels: release/internal

#4358 fix v3 integration tests
  integration/deploy/compose_test.go
Labels: release/internal, 3.0, run-e2e

#4354 Admins to be able to deploy into namespaces or previews
  cmd/context/create_test.go
  cmd/context/utils.go
  cmd/namespace/use.go
  cmd/namespace/use_test.go
  cmd/utils/okteto.go
  cmd/utils/okteto_test.go
  internal/test/client/namespace.go
  internal/test/client/preview.go
  pkg/errors/errors.go
  pkg/okteto/client.go
  pkg/okteto/namespace.go
  pkg/okteto/namespace_test.go
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
  pkg/types/interface.go
Labels: release/internal

#4352 remove stack commands
  .circleci/config.yml
  Makefile
  cmd/context/utils.go
  cmd/deploy/deploy.go
  cmd/stack/deploy.go
  cmd/stack/deploy_test.go
  cmd/stack/destroy.go
  cmd/stack/endpoints.go
  cmd/stack/stack.go
  cmd/utils/stack.go
  integration/commands/stacks.go
  integration/deprecated/stack/compose_test.go
  integration/deprecated/stack/stack_test.go
  main.go
  pkg/analytics/track.go
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/endpoints.go
Labels: release/internal, 3.0

#4361 fix: smart build stuck on untracked files
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/local_git.go
Labels: release/bug-fix, backport release-2.28

#4362 feat: change the default behavior of OKTETO_LOCAL_REGISTRY_STORE_ENABLED
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/authprovider_test.go
  pkg/registry/client.go
Labels: release/internal, 3.0

#4359 remove manifest v1 support
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v1/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/environment_test.go
  cmd/context/utils_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/up/activate.go
  cmd/up/up.go
  cmd/utils/dev_test.go
  integration/okteto/autowake_test.go
  integration/up/autocreate_test.go
  integration/up/deployment_test.go
  integration/up/exec_test.go
  integration/up/statefulset_test.go
  pkg/analytics/up.go
  pkg/analytics/up_test.go
  pkg/cmd/doctor/run.go
  pkg/cmd/doctor/run_test.go
  pkg/k8s/apps/crud_test.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/statefulsets/crud.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/translation_test.go
Labels: release/internal, 3.0, run-e2e
