Repository okteto/okteto, pull requests merged in 2024-05, with the labels that each got.

#4273 chore: upgrade deps
  Dockerfile
  go.mod
  go.sum
Labels: release/internal, run-e2e-windows, run-e2e, run-e2e-unix

#4272 tests(fix): remove defer on tests
  integration/build/build_test.go
  integration/deploy/compose_test.go
  integration/deploy/endpoints_test.go
  integration/deploy/external_test.go
  integration/deploy/helm_test.go
  integration/deploy/k8s_manifest_test.go
  integration/deploy/manifest_test.go
  integration/deploy/pipeline_test.go
  integration/deploy/variables_test.go
  integration/deprecated/push/push_test.go
  integration/deprecated/stack/compose_test.go
  integration/okteto/autowake_test.go
  integration/okteto/build_test.go
  integration/okteto/dependencies_test.go
  integration/okteto/deploy_test.go
  integration/okteto/pipeline_test.go
  integration/up/autocreate_test.go
  integration/up/compose_test.go
  integration/up/deploy_remote_test.go
  integration/up/deploy_test.go
  integration/up/deployment_test.go
  integration/up/globalforward_test.go
  integration/up/hybridmode_test.go
  integration/up/statefulset_test.go
Labels: release/bug-fix, run-e2e

#4279 fix: golang ci linter
  Makefile
  pkg/analytics/config_test.go
  pkg/cmd/build/depot.go
  pkg/cmd/login/html/email_error.go
  pkg/cmd/login/html/login_fail.go
  pkg/cmd/login/html/login_success.go
  pkg/cmd/login/html/template.go
  pkg/cmd/pipeline/crud.go
  pkg/cmd/pipeline/crud_test.go
  pkg/format/format.go
  pkg/format/format_test.go
  pkg/k8s/ingresses/translate_test.go
  pkg/model/dev.go
  pkg/model/forward/forward_serializer_test.go
  pkg/model/forward/global_forward_serializer_test.go
  pkg/path/path.go
  pkg/path/path_test.go
  pkg/ssh/resize_window_unix.go
  pkg/textblock/doc.go
  pkg/textblock/error.go
  pkg/textblock/textblock.go
Labels: release/internal

#4282 fix: not show unwanted warning
  cmd/build/command.go
Labels: release/bug-fix, backport release-2.27

#4283 fix linter
  .golangci.yml
  Makefile
  pkg/analytics/test.go
  pkg/model/stack.go
  pkg/registry/image.go
  scripts/ci/push-image.sh
Labels: release/internal

#4285 fix: retry builds on depot
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
Labels: release/bug-fix, backport release-2.27

#4260 Remove deprecated code related to okteto chart `0.10.8`
  pkg/okteto/auth.go
  pkg/okteto/auth_test.go
  pkg/okteto/pipeline.go
  pkg/okteto/pipeline_test.go
  pkg/okteto/secrets.go
  pkg/okteto/secrets_test.go
Labels: release/internal, run-e2e

#4299 chore: update golang-ci to 2.5.0
  .circleci/config.yml
Labels: release/internal

#4298 Include all manifest properties to "friendly err" util + Add okteto test alias
  pkg/model/manifest_friendly_err.go
  pkg/model/schema.go
  pkg/model/schema_test.go
  pkg/model/test.go
Labels: release/bug-fix

#4297 Fix regression with `OKTETO_TOKEN` and improve DevX for invalid token
  cmd/context/create.go
  cmd/context/options.go
  cmd/context/options_test.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/push.go
  cmd/test/cmd.go
  pkg/okteto/client.go
Labels: release/bug-fix, run-e2e, backport release-2.27

#4303 `Preserve local env vars if also declared in `.env` + Add E2E test for Okteto Variables
  cmd/context/create.go
  cmd/context/create_test.go
  cmd/context/use.go
  integration/deploy/variables_test.go
Labels: release/bug-fix, run-e2e, backport release-2.27

#4304 fix: warning displayed even when the file was invalid
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/bug-fix, backport release-2.27

#4306 fix: warning displayed even when the file was invalid (#4304)
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/bug-fix

#4310 remove unused code
  cmd/update.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
Labels: release/internal, run-e2e

#4311 remove unused code (build)
  cmd/build/basic/build.go
  cmd/build/v2/smartbuild/hasher.go
  cmd/build/v2/smartbuild/hasher_test.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
Labels: release/internal, run-e2e

#4312 fix panic when inferring stack with empty image
  integration/up/compose_with_okteto_manifest_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/bug-fix, run-e2e, backport release-2.27, backport release-2.26

#4320 [okteto test] only deploy when using `--deploy` flag
  cmd/test/cmd.go
  pkg/analytics/test.go
  pkg/analytics/test_test.go
Labels: release/internal

#4322 fix: panics on command initialsation
  cmd/deploy/deploy.go
  cmd/init.go
  cmd/manifest/init-v2.go
  cmd/up/types.go
  cmd/up/up.go
Labels: release/bug-fix, backport release-2.27, backport release-2.26

#4289 okteto exec to work the same as kubectl exec
  cmd/down.go
  cmd/exec.go
  cmd/exec/app.go
  cmd/exec/app_test.go
  cmd/exec/cmd.go
  cmd/exec/cmd_test.go
  cmd/exec/executor.go
  cmd/exec/executor_test.go
  cmd/exec/mixpanel.go
  cmd/exec/mixpanel_test.go
  cmd/exec/options.go
  cmd/exec/options_test.go
  cmd/exec_test.go
  cmd/utils/selector.go
  integration/commands/exec.go
  integration/up/autocreate_test.go
  integration/up/deployment_test.go
  integration/up/exec_test.go
  integration/up/statefulset_test.go
  integration/up/up_test.go
  main.go
  pkg/k8s/apps/crud.go
  pkg/k8s/apps/crud_test.go
  pkg/ssh/exec.go
Labels: release/bug-fix, run-e2e

#4325 fix test logs
  cmd/test/cmd.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/constants.go
  pkg/cmd/build/logger.go
  pkg/deployable/test.go
  pkg/remote/remote.go
Labels: release/bug-fix
