Repository okteto/okteto, pull requests merged in 2024-07, with the labels that each got.

#4373 up: skip refresh token for vanilla clusters
  cmd/up/up.go
Labels: release/bug-fix, backport release-2.29

#4356 Reuse exec args syntax on up
  cmd/args/errors.go
  cmd/args/lister.go
  cmd/args/lister_test.go
  cmd/args/parser.go
  cmd/args/parser_test.go
  cmd/exec/cmd.go
  cmd/exec/cmd_test.go
  cmd/exec/options.go
  cmd/up/up.go
  cmd/up/up_test.go
Labels: release/internal, 3.0, run-e2e

#4377 fix: global image clone
  cmd/build/v2/build.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  integration/commands/deploy.go
  integration/deploy/manifest_test.go
  integration/deploy/smartbuild_test.go
  integration/git.go
Labels: release/bug-fix, backport release-2.29

#4375 feat: remove support for deploy certain services
  cmd/deploy/build.go
  cmd/deploy/build_test.go
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/errors/errors.go
Labels: release/internal, 3.0

#4381 Migrate circleci deploy to run
  .circleci/config.yml
Labels: release/internal

#4376 remove support for automatic deployment without an okteto manifest
  integration/deploy/helm_test.go
  integration/deploy/k8s_manifest_test.go
  pkg/constants/constants.go
  pkg/deployable/deploy.go
  pkg/discovery/helm.go
  pkg/discovery/helm_test.go
  pkg/discovery/k8s.go
  pkg/discovery/k8s_test.go
  pkg/errors/errors.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/internal, 3.0, run-e2e

#4370 Remove remote check when running build inside deploy remote
  cmd/build/v2/build.go
  integration/deploy/remote_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: release/bug-fix, run-e2e

#4379 Allow remote deploy inside remote deploy
  cmd/deploy/cfghandler.go
  cmd/deploy/deploy.go
  integration/deploy/deploy_remote_test.go
  integration/deploy/endpoints_test.go
  integration/deploy/manifest_test.go
  pkg/remote/remote.go
Labels: release/bug-fix

#4383 Remove top level devs from the okteto manifest
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/internal, 3.0, run-e2e

#4385 fix: okteto test can export artifact dirs
  integration/test/test_test.go
  pkg/model/manifest_friendly_err.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, run-e2e-unix, backport release-2.29

#4390 deploy waits by default
  cmd/deploy/deploy.go
  integration/commands/deploy.go
  integration/deploy/compose_test.go
Labels: release/internal, 3.0, run-e2e

#4392 add metrics in order to know the usage
  cmd/build/command.go
  pkg/analytics/track.go
Labels: release/internal, 3.0

#4393 remove global from build command
  cmd/build/command.go
  pkg/cmd/build/build.go
  pkg/types/build.go
Labels: release/internal, 3.0

#4388 Remove deprecated fields from dev
  cmd/up/up.go
  integration/up/hybridmode_test.go
  pkg/k8s/apps/crud.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/volumes/crud.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/schema_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/translation_test.go
Labels: release/internal, 3.0, run-e2e

#4397 pipeline deploy/destroy wait by default
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
Labels: release/internal, 3.0

#4398 preview deploy/ wait by default
  cmd/preview/deploy.go
  cmd/preview/destroy.go
Labels: release/internal, 3.0

#4407 DEV-520: Scan image on release
  .circleci/config.yml
Labels: release/internal

#4405 DEV-494: Handling an special error from the registry when an image digest is malformed
  main.go
  pkg/registry/client.go
  pkg/registry/client_test.go
Labels: release/internal

#4409 remove cache for test
  cmd/test/cmd.go
  pkg/remote/remote.go
Labels: release/bug-fix, backport release-2.29

#4391 Split integration tests into jobs
  .circleci/config.yml
  .dockerignore
Labels: release/internal, run-e2e

#4406 fix: deploy remote falback to dockerignore instead of skipping it
  integration/deploy/remote_test.go
  pkg/ignore/ignore_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, run-e2e, backport release-2.29

#4410 fix: add extra hosts in okteot test
  cmd/test/cmd.go
  pkg/model/schema_test.go
  pkg/model/test.go
  pkg/model/test_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
  pkg/types/build.go
Labels: release/bug-fix, backport release-2.29

#4413 [Backport 2.29] deploy remote falback to dockerignore instead of skipping it (#4406)
  pkg/ignore/ignore_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix

#4400 Use default cfgmaphandler for destroy in deploy
  cmd/destroy/cfghandler.go
Labels: release/bug-fix
