Repository okteto/okteto, pull requests merged in 2024-02, with the labels that each got.

#4163 Using mix panel proxy
  pkg/analytics/track.go
Labels: release/internal

#4165 fix: e2e actions tests: pipeline with compose
  integration/actions/pipeline_test.go
Labels: release/internal

#4173 fix: linter
  scripts/ci/push-image.sh
Labels: release/internal

#4176 Add Branch column to preview environment list command output
  cmd/preview/list.go
  cmd/preview/list_test.go
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
  pkg/types/preview.go
Labels: no-dco, new-contributor, release/new-feature

#4177 Fix panic in `okteto up` when using remote deploy
  .circleci/config.yml
  cmd/build/v2/smartbuild/hasher.go
  cmd/up/up.go
  integration/up/deploy_remote_test.go
Labels: release/bug-fix, run-e2e, backport release-2.25

#4180 fix: backport to 2.25.x
  integration/up/deploy_remote_test.go
Labels: release/internal, run-e2e-unix

#4171 fix: double warning on --insecure-skip-tls-verify
  cmd/context/context.go
Labels: release/bug-fix

#4174 fix: context insecure is maintained until deleted the context
  cmd/context/create.go
  pkg/okteto/client.go
Labels: release/bug-fix

#4169 Changed some documentation links as some were broken (pointing to old pages)
  cmd/deploy/deploy.go
  cmd/push.go
  cmd/stack/destroy.go
Labels: release/internal

#4172 Improve experience for overnight `okteto up` sessions, and syntching timeouts
  cmd/up/activate.go
  cmd/up/errors.go
  cmd/up/errors_test.go
  cmd/up/syncthing.go
  cmd/up/up.go
  pkg/errors/errors_test.go
  pkg/syncthing/syncthing.go
Labels: no-dco, release/new-feature, run-e2e

#4181 fix: realpath on mac
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/context/utils.go
  cmd/context/utils_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/logs/logs.go
  cmd/manifest/init-v1_test.go
  cmd/manifest/init-v2.go
  cmd/push.go
  cmd/restart.go
  cmd/stack/deploy.go
  cmd/stack/destroy.go
  cmd/stack/endpoints.go
  cmd/status.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/utils/dev_test.go
  cmd/utils/stack_test.go
  pkg/filesystem/realpath.go
  pkg/filesystem/realpath_test.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
  pkg/model/schema_test.go
  pkg/model/serializer_test.go
  pkg/model/stack.go
  pkg/model/stack_test.go
Labels: release/bug-fix, run-e2e

#4185 [Hybrid] Improve process management
  cmd/up/up.go
  cmd/up/up_unix.go
  cmd/up/up_windows.go
  pkg/process/process.go
  pkg/process/process_unix.go
  pkg/process/process_windows.go
Labels: no-dco, release/bug-fix, run-e2e-unix

#4186 Fix `okteto endpoints` namespace detection from `okteto.yml`
  cmd/context/utils.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
Labels: no-dco, release/bug-fix, run-e2e-unix

#4192 Update links to docs to map the new docs structure
  README.md
  cmd/analytics.go
  cmd/build/command.go
  cmd/context/context.go
  cmd/context/create.go
  cmd/context/delete.go
  cmd/context/list.go
  cmd/context/show.go
  cmd/context/update-kubeconfig.go
  cmd/context/use-namespace.go
  cmd/context/use.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/init.go
  cmd/kubeconfig.go
  cmd/login.go
  cmd/logs/logs.go
  cmd/manifest/init-v1.go
  cmd/namespace/namespace.go
  cmd/namespace/use.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/pipeline/pipeline.go
  cmd/push.go
  cmd/restart.go
  cmd/stack/stack.go
  cmd/status.go
  cmd/up/activate.go
  cmd/up/up.go
  cmd/utils/dev.go
  cmd/version.go
  docs/how-does-it-work.md
  pkg/cmd/login/login.go
  pkg/k8s/apps/validation.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/model/dev_test.go
  pkg/model/devrc.go
  pkg/model/manifest.go
  pkg/model/manifest_friendly_err.go
  pkg/model/manifest_friendly_err_test.go
  pkg/model/stack.go
  pkg/model/stack_serializer.go
  pkg/ssh/exec.go
Labels: release/internal
