Repository okteto/okteto, pull requests merged in 2024-10, with the labels that each got.

#4500 Fix okteto status: namespace load for synthing
  cmd/context/utils.go
  cmd/down.go
  cmd/exec/cmd.go
  cmd/restart.go
  cmd/status.go
Labels: release/bug-fix, 3.0, backport release-3.0

#4502 fix: build command to handle Okteto Manifest without a build section
  cmd/build/command.go
  cmd/build/command_test.go
Labels: release/bug-fix, 3.0, backport release-3.0

#4503 Refactor error messages for Docker Compose usage
  cmd/build/command.go
  pkg/model/manifest.go
Labels: release/internal, backport release-3.0

#4509 fix: versions getting last 15 from gh
  cmd/utils/upgrade.go
Labels: release/internal, run-e2e, backport release-3.0

#4506 Fix `okteto build -f <folder>`
  cmd/build/basic/build.go
  cmd/build/command.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec/cmd.go
  cmd/logs/logs.go
  cmd/restart.go
  cmd/status.go
  cmd/test/cmd.go
  cmd/up/up.go
  pkg/validator/arguments.go
  pkg/validator/arguments_test.go
Labels: release/bug-fix, 3.0, backport release-3.0

#4512 [Backport release-3.0 ]Fix `okteto build -f <folder>` (#4506)
  cmd/build/basic/build.go
  cmd/build/command.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec/cmd.go
  cmd/logs/logs.go
  cmd/restart.go
  cmd/status.go
  cmd/test/cmd.go
  cmd/up/up.go
  pkg/validator/arguments.go
  pkg/validator/arguments_test.go
Labels: release/bug-fix

#4513 Support for "priorityClassName" in dev containers
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/statefulsets/crud.go
  pkg/model/dev.go
  pkg/model/schema_test.go
  pkg/model/translation.go
  pkg/model/translation_test.go
Labels: release/new-feature, backport release-3.0

#4514 refactor: improve circleci config
  .circleci/config.yml
Labels: release/internal, backport release-3.0

#4511 move name inferrer inside destroyCommand.destroy
  cmd/destroy/build_control.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
Labels: release/bug-fix, 3.0, backport release-3.0

#4518 test: change trivy cmd in intergraiton test
  integration/deploy/deploy_remote_test.go
Labels: release/bug-fix, 3.0, run-e2e, backport release-3.0

#4491 Jlo/merge with master
  .circleci/config.yml
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  cmd/exec/app_test.go
  cmd/exec/cmd.go
  cmd/logs/logs.go
  cmd/test/cmd.go
  pkg/analytics/track.go
  pkg/cmd/build/errors.go
  pkg/cmd/build/errors_test.go
  pkg/cmd/pipeline/crud.go
  pkg/log/io/logrus.go
  pkg/model/forward/global_forward.go
  pkg/model/forward/global_forward_test.go
  pkg/okteto/auth.go
  pkg/okteto/client.go
  pkg/registry/image.go
  samples/node.js/package.json
  samples/node.js/yarn.lock
  scripts/ci/push-image.sh
  scripts/set_latest_actions.sh
Labels: release/internal

#4484 refactor (release): refactor the actions release script to match the …
  .circleci/config.yml
  scripts/ci/push-image.sh
  scripts/ci/release-github-actions.sh
Labels: release/internal, backport release-3.0

#4520 refactor (release): refactor the actions release script to match the … (#4484)
  .circleci/config.yml
  scripts/ci/push-image.sh
  scripts/ci/release-github-actions.sh
Labels: release/internal

#4521 fix: gh actions release script
  scripts/ci/push-image.sh
  scripts/ci/release-github-actions.sh
Labels: release/internal

#4522 Updated ssh key to be used on circleCI jobs to use oktetobot identity
  .circleci/config.yml
  scripts/ci/release-branch.sh
  scripts/ci/release-github-actions.sh
  scripts/update_homebrew_formula.sh
Labels: release/internal, backport release-3.0

#4525 Enable OKTETO_LOCAL_REGISTRY_STORE_PRIORITY_ENABLED in CircleCI config
  .circleci/config.yml
Labels: release/internal

#4524 refactor: update trivy commands in CircleCI config
  .circleci/config.yml
Labels: release/internal, backport release-3.0

#4528 feat(build): if buildkit is not available wait for it
  cmd/build/v2/build.go
  pkg/analytics/imagebuild.go
  pkg/analytics/imagebuild_test.go
  pkg/build/buildkit/client.go
  pkg/build/buildkit/client_test.go
  pkg/build/buildkit/metadata.go
  pkg/build/buildkit/wait.go
  pkg/build/buildkit/wait_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
Labels: release/new-feature

#4529 feat: retry if buildkit not available
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  pkg/build/buildkit/errors.go
  pkg/build/buildkit/errors_test.go
  pkg/build/buildkit/runner.go
  pkg/build/buildkit/runner_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/logger.go
  pkg/env/env.go
  pkg/env/env_test.go
Labels: release/new-feature, run-e2e

#4535 fix lint errors
  .circleci/config.yml
  README.md
  scripts/ci/push-image.sh
  scripts/ci/release-github-actions.sh
Labels: release/internal

#4530 update stack destroy logic to use service name label
  pkg/cmd/pipeline/translate.go
  pkg/cmd/stack/destroy.go
  pkg/cmd/stack/destroy_test.go
Labels: release/bug-fix

#4539 fix: ui build logs
  pkg/cmd/build/buildkit.go
Labels: release/bug-fix

#4537 DEV-758: Implement ssh-forwarder to contact with ssh-agent running in the cluster when executing remote operations (deploy, destroy, test)
  cmd/remoterun/deploy.go
  cmd/remoterun/destroy.go
  cmd/remoterun/ssh.go
  cmd/remoterun/ssh_test.go
  cmd/remoterun/test.go
  pkg/constants/constants.go
  pkg/okteto/secrets.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
  pkg/types/cluster_metadata.go
Labels: release/internal, run-e2e

#4533 remove validation from context store
  pkg/okteto/context.go
  pkg/okteto/context_test.go
Labels: release/bug-fix

#4536 Deploy Execution default and flags outcome
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/destroy/destroy.go
  cmd/destroy/destroy_test.go
  cmd/destroy/remote.go
  cmd/test/cmd.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/new-feature

#4544 DEV-765: Allow to custom known_hosts from runner image
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/internal, run-e2e
