Repository okteto/okteto, pull requests merged in 2024-09, with the labels that each got.

#4438 DEV-624: Added scan for okteto/bin image, and update okteto/bin dependency to 1.6.1
  .circleci/config.yml
  .github/workflows/release-bin.yml
  pkg/model/dev.go
Labels: release/internal, backport release-2.31

#4440 Fixed typo in a feature flag to enable dev branch tracking on okteto up
  cmd/up/activate.go
Labels: release/bug-fix, backport release-2.31

#4450 fix depot builds in ci
  pkg/cmd/build/buildkit.go
  pkg/remote/remote.go
Labels: release/bug-fix, run-e2e

#4446 feat: Update contextCMD.Run() arguments to include K8sContext
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/preview/deploy.go
  cmd/preview/destroy.go
  cmd/preview/endpoints.go
  cmd/preview/list.go
  cmd/preview/sleep.go
  cmd/preview/wake.go
  cmd/status.go
Labels: release/bug-fix, 3.0

#4454 Fix typos and remove dead code
  cmd/deploy/deploy.go
  cmd/exec/app_test.go
  cmd/exec/cmd.go
  cmd/logs/logs.go
  pkg/analytics/track.go
  pkg/log/io/logrus.go
  pkg/model/forward/global_forward.go
  pkg/model/forward/global_forward_test.go
  pkg/okteto/auth.go
  pkg/registry/image.go
Labels: release/internal

#4453 Update cobra help message to be aligned with out official docs
  cmd/analytics.go
  cmd/build/command.go
  cmd/context/context.go
  cmd/context/delete.go
  cmd/context/list.go
  cmd/context/show.go
  cmd/context/use.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/destroy/destroy.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec/cmd.go
  cmd/kubetoken/kubetoken.go
  cmd/logs/logs.go
  cmd/namespace/create.go
  cmd/namespace/delete.go
  cmd/namespace/list.go
  cmd/namespace/namespace.go
  cmd/namespace/use.go
  cmd/namespace/wake.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/pipeline/list.go
  cmd/pipeline/pipeline.go
  cmd/preview/deploy.go
  cmd/preview/destroy.go
  cmd/preview/endpoints.go
  cmd/preview/list.go
  cmd/preview/preview.go
  cmd/preview/sleep.go
  cmd/preview/wake.go
  cmd/restart.go
  cmd/status.go
  cmd/test/cmd.go
  cmd/up/up.go
  cmd/version.go
  main.go
Labels: release/internal

#4455 revert default wait flag values
  cmd/deploy/deploy.go
  cmd/pipeline/deploy.go
  cmd/pipeline/destroy.go
  cmd/preview/deploy.go
  cmd/preview/destroy.go
Labels: release/internal, run-e2e, backport release-3.0

#4458 Support okteto volume access mode, volume mode, labels and annotations
  pkg/k8s/apps/translate.go
  pkg/k8s/volumes/crud.go
  pkg/k8s/volumes/crud_test.go
  pkg/k8s/volumes/translate.go
  pkg/k8s/volumes/translate_test.go
  pkg/model/dev.go
  pkg/model/schema_test.go
  pkg/model/translation_test.go
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: release/new-feature, backport release-3.0

#4452 fix(remote): :bug: multiline preparation on dockerfile
  integration/deploy/deploy_remote_test.go
  integration/deploy/deploy_test.go
  integration/deploy/remote_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, 3.0, run-e2e

#4465 Update CTA to install Okteto in the cluster for unsupported command/f…
  pkg/errors/errors.go
  pkg/model/manifest.go
Labels: release/internal, backport release-3.0

#4467 Host "busybox" in the "okteto" DockerHub organization
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/constants/constants.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, run-e2e-unix

#4461 Add CI env var to okteto test
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  cmd/destroy/remote.go
  cmd/destroy/remote_test.go
  cmd/test/cmd.go
  pkg/constants/constants.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, backport release-3.0

#4475 Fix checking for pod sandbox creation error
  cmd/up/activate.go
Labels: release/internal, run-e2e, backport release-3.0

#4464 PROD-218: Add a timeout flag to okteto preview destroy command
  cmd/preview/destroy.go
  cmd/preview/destroy_test.go
Labels: release/new-feature, run-e2e, backport release-3.0

#4448 feat: Add extractImageTagFromPullAccessDeniedError function
  cmd/deploy/remote.go
  pkg/cmd/build/errors.go
  pkg/cmd/build/errors_test.go
Labels: release/bug-fix

#4471 remove remote deploy CTA on vanilla
  cmd/up/up.go
Labels: release/internal, 3.0, backport release-3.0

#4470 Refactor authProvider to prioritize local registry credentials
  pkg/cmd/build/authprovider.go
  pkg/cmd/build/authprovider_test.go
  pkg/registry/client.go
Labels: release/internal, 3.0, backport release-3.0

#4473 Add specific error for compose on cli only
  cmd/build/command.go
  pkg/model/manifest.go
Labels: release/internal, 3.0, backport release-3.0

#4463 Refactor dockerfile to use private cache sharing
  pkg/remote/remote.go
Labels: release/bug-fix, 3.0, run-e2e, backport release-3.0

#4485 revert pipeline and preview file check
  cmd/pipeline/deploy.go
  cmd/pipeline/pipeline.go
  cmd/preview/deploy_utils.go
  main.go
Labels: release/internal, backport release-3.0

#4483 Refactor deploy.go to conditionally display recommendation for enabling remote execution
  cmd/deploy/deploy.go
Labels: release/bug-fix, backport release-3.0

#4486 check abs with abs
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
Labels: release/internal, run-e2e, backport release-3.0

#4488 Remove context and namespace from manifestRaw
  cmd/context/utils_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/bug-fix, 3.0, backport release-3.0

#4495 Use "IfNotPresent" when using busybox for init volumes and hybrid mode
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
Labels: release/new-feature, run-e2e, backport release-3.0

#4487 Refactor getStackServicesToDeploy function to handle multiple Compose…
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
Labels: release/internal, backport release-3.0

#4492 refactor: remove context and namespace from Stack
  pkg/model/stack_serializer.go
Labels: release/internal, 3.0, backport release-3.0

#4494 DEV-690: Use right build context path to get the right diff and sha in git operations for Smart Builds
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/smartbuild/hasher.go
  cmd/build/v2/smartbuild/hasher_test.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  pkg/repository/local_git.go
Labels: release/bug-fix, run-e2e, backport release-3.0
