Repository okteto/okteto, pull requests merged in 2024-01, with the labels that each got.

#4089 feat: use build context for isClean
  cmd/build/v2/build.go
  cmd/build/v2/build_test.go
  cmd/build/v2/config_test.go
  cmd/build/v2/hasher_test.go
  cmd/build/v2/services.go
  cmd/build/v2/smartbuild/hasher.go
  cmd/build/v2/smartbuild/hasher_test.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
  cmd/build/v2/tagger.go
  cmd/build/v2/tagger_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/repository/git.go
  pkg/repository/git_test.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
  pkg/repository/remote.go
  pkg/repository/remote_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: no-dco, release/new-feature

#4107 fix: wrap error while creating secrets
  cmd/up/activate.go
  cmd/up/stignore.go
  cmd/up/up.go
  pkg/divert/weaver/ingresses.go
  pkg/k8s/apps/deployments.go
  pkg/k8s/apps/statefulsets.go
  pkg/k8s/pods/pod.go
  pkg/k8s/secrets/crud.go
  pkg/k8s/statefulsets/crud.go
  pkg/k8s/volumes/crud.go
  pkg/ssh/client.go
  pkg/ssh/config.go
  pkg/ssh/exec.go
  pkg/ssh/key.go
  pkg/ssh/manager.go
  pkg/ssh/ssh.go
  pkg/syncthing/install.go
  pkg/syncthing/syncthing.go
Labels: release/bug-fix, run-e2e, backport release-2.24

#4111 fix: panic in okteto up caused by already closed readyChan
  pkg/k8s/forward/manager.go
Labels: release/bug-fix, run-e2e, backport release-2.24

#4113 fix: panic in okteto build caused by nil `oc.Store`
  cmd/build/command.go
Labels: release/bug-fix, run-e2e, backport release-2.24

#4117 Backport: fix: missing trailing slash in IsGlobalRegistry
  pkg/registry/registry.go
  pkg/registry/registry_test.go
Labels: release/bug-fix, echoes/intent: fix

#4118 fix: add test for missing trailing slash in IsGlobalRegistry
  pkg/registry/registry.go
  pkg/registry/registry_test.go
Labels: release/internal

#4119 feat: expand build secrets
  cmd/build/v2/build.go
  pkg/build/info.go
  pkg/build/info_test.go
  pkg/build/manifest_section_test.go
Labels: no-dco, release/new-feature, run-e2e

#4122 docs: refactor helper usage
  cmd/exec.go
  cmd/up/up.go
Labels: release/new-feature

#4125 Upgrade staging domain for user apps
  .circleci/config.yml
Labels: no-dco, release/internal, echoes/intent: run

#4127 fix: statefulset reconnection error
  cmd/up/activate.go
Labels: release/bug-fix, run-e2e

#4124 fix: multi tag bullds
  cmd/build/v1/build.go
  cmd/build/v2/build.go
  pkg/cmd/build/build.go
Labels: release/bug-fix

#4123 feat: always refresh kubetoken on okteto up errors
  cmd/up/up.go
Labels: release/internal, echoes/intent: run, run-e2e

#4126 docs: rename svc to service in helper
  cmd/doctor.go
  cmd/down.go
  cmd/push.go
  cmd/restart.go
Labels: release/internal

#4132 update golangci goheader config for 2024
  .golangci.yml
Labels: release/internal

#4134 fix okteto up double shutdown when interrupting with ctrl+c
  cmd/up/activate.go
Labels: release/bug-fix, run-e2e, backport release-2.24

#4133 update codeowners to backend team
  CODEOWNERS
Labels: no-dco, release/internal

#4135 rename launch to deploy
  cmd/exec.go
  cmd/manifest/init-v2.go
  cmd/up/up.go
  cmd/utils/dev.go
Labels: release/internal

#4131 Log all requests made to K8S's API
  cmd/build/command.go
  cmd/build/command_test.go
  cmd/build/v2/build.go
  cmd/delete.go
  cmd/deploy/cfghandler.go
  cmd/deploy/command_configuration.go
  cmd/deploy/command_configuration_test.go
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  cmd/deploy/endpoints.go
  cmd/deploy/local.go
  cmd/deploy/local_test.go
  cmd/deploy/wait.go
  cmd/destroy/destroy.go
  cmd/doctor.go
  cmd/down.go
  cmd/exec.go
  cmd/logs/logs.go
  cmd/manifest/init-v2.go
  cmd/namespace/delete.go
  cmd/namespace/delete_test.go
  cmd/namespace/namespace.go
  cmd/namespace/namespace_test.go
  cmd/up/up.go
  cmd/up/up_test.go
  cmd/utils/okteto.go
  docs/how-to-run-tests.md
  integration/up/deploy_test.go
  internal/test/k8s_provider.go
  main.go
  main_test.go
  pkg/cmd/doctor/run.go
  pkg/k8s/volumes/crud.go
  pkg/log/io/io_test.go
  pkg/log/io/k8s_logger.go
  pkg/log/io/k8s_logger_test.go
  pkg/log/io/logger.go
  pkg/okteto/context.go
  pkg/okteto/k8s.go
  pkg/okteto/k8s_test.go
Labels: no-dco, release/internal, run-e2e

#4140 fix: panic on race condition
  pkg/k8s/forward/manager.go
Labels: release/bug-fix

#4128 fix: remote with parent folders
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  integration/deploy/manifest_test.go
Labels: no-dco, release/bug-fix, run-e2e

#4143 fix: missing whitespace on spinner
  pkg/log/io/spinner.go
  pkg/log/io/spinner_test.go
Labels: release/bug-fix, backport release-2.25

#4146 fix: integration test after linter refactor
  integration/deploy/manifest_test.go
Labels: release/internal, run-e2e

#4147 fix: log k8s request before any return
  pkg/okteto/k8s.go
Labels: release/internal, backport release-2.25

#4149 fix: avoid panic in k8s logger if resp is nil
  pkg/okteto/k8s.go
Labels: release/internal, backport release-2.25

#4151 Update links to the new docs structure
  cmd/context/create.go
  cmd/context/kubetoken.go
  cmd/context/use.go
  cmd/deploy/deploy.go
  cmd/deploy/endpoints.go
  cmd/kubeconfig.go
  pkg/errors/errors.go
Labels: release/internal

#4153 fix cves
  cmd/deploy/command_configuration.go
  go.mod
  go.sum
  pkg/cmd/pipeline/translate.go
  pkg/deps/deps.go
  pkg/deps/deps_test.go
  pkg/repository/repository.go
Labels: no-dco, release/internal, backport release-2.25

#4129 push releases to all the possible images at dockerhub
  scripts/ci/push-image.sh
Labels: no-dco, release/new-feature

#4106 add depot.dev as a valid builder
  .circleci/config.yml
  cmd/build/command.go
  cmd/build/remote/build.go
  cmd/build/v1/build.go
  cmd/build/v2/build.go
  go.mod
  go.sum
  integration/build/build_test.go
  integration/commands/build.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
Labels: release/new-feature, run-e2e

#4157 fix: json build output
  pkg/log/io/formatter.go
  pkg/log/io/formatter_test.go
  pkg/log/io/out_test.go
Labels: release/bug-fix, backport release-2.25

#4160 add depot.dev as a valid builder (#4106)
  .circleci/config.yml
  cmd/build/command.go
  cmd/build/remote/build.go
  cmd/build/v1/build.go
  cmd/build/v2/build.go
  go.mod
  go.sum
  integration/build/build_test.go
  integration/commands/build.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
Labels: release/new-feature, run-e2e

#4156 Improve experience for overnight `okteto up` sessions, and syntching timeouts
  cmd/up/activate.go
  cmd/up/errors.go
  cmd/up/errors_test.go
  cmd/up/syncthing.go
  cmd/up/types.go
  cmd/up/up.go
  pkg/errors/errors_test.go
  pkg/syncthing/syncthing.go
Labels: release/internal

#4162 Revert "Improve experience for overnight `okteto up` sessions, and sy…
  cmd/up/activate.go
  cmd/up/errors.go
  cmd/up/errors_test.go
  cmd/up/syncthing.go
  cmd/up/types.go
  cmd/up/up.go
  pkg/errors/errors_test.go
  pkg/syncthing/syncthing.go
Labels: no-dco, release/internal, run-e2e
