Repository okteto/okteto, pull requests merged in 2024-11, with the labels that each got.

#4541 Fix #4540 by removing duplicated `if-then-else` branches
  pkg/model/manifest.go
Labels: release/internal

#4546 refactor: rename env vars to follow same syntax
  pkg/build/buildkit/runner.go
  pkg/build/buildkit/wait.go
Labels: release/internal, backport release-3.1

#4545 DEV-510: Fix availability of CI env var on remote executions
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix, run-e2e, backport release-3.1

#4543 feat (build): support overriding default frontend image
  cmd/build/command.go
  cmd/build/v2/build.go
  cmd/deploy/remote.go
  cmd/destroy/remote.go
  cmd/test/cmd.go
  pkg/build/buildkit/frontend.go
  pkg/build/buildkit/frontend_test.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/log_filter.go
  pkg/cmd/build/log_filter_test.go
Labels: release/new-feature

#4547 Update `okteto deploy` timeout and wait output
  cmd/deploy/deploy.go
  cmd/deploy/wait.go
Labels: release/internal

#4559 DEV-774: When inferring dev environment name, check if `OKTETO_NAME` is set if cannot get the name from the repository and before getting the name from the folder
  pkg/devenvironment/name.go
  pkg/devenvironment/name_test.go
Labels: release/bug-fix, run-e2e

#4564 Update golang-ci dependency to 2.7.0 to have CLI 3.x
  .circleci/config.yml
  cmd/args/parser.go
  cmd/up/activate.go
  cmd/up/exec.go
  cmd/up/exec_test.go
  internal/test/client/user.go
  main.go
  pkg/build/info.go
  pkg/cmd/build/logger.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/statefulsets/crud.go
  pkg/model/stack.go
  pkg/syncthing/syncthing.go
Labels: release/internal, run-e2e

#4567 Simplify "make integration-actions" to reduce their execution time
  integration/actions/apply_test.go
  integration/actions/pipeline_test.go
Labels: release/internal, run-e2e

#4570 Build images with depot.dev
  .circleci/config.yml
  scripts/ci/push-image.sh
Labels: release/internal

#4560 move to manifest v2
  okteto.yml
Labels: release/internal

#4562 bump cli to use buildkit 0.17
  go.mod
  go.sum
  pkg/build/buildkit/authprovider.go
  pkg/build/buildkit/authprovider_test.go
  pkg/build/buildkit/frontend.go
  pkg/build/buildkit/frontend_test.go
  pkg/build/buildkit/opt.go
  pkg/build/buildkit/opt_test.go
  pkg/build/buildkit/runner.go
  pkg/cmd/build/build.go
  pkg/cmd/build/buildkit.go
  pkg/cmd/build/depot.go
  pkg/cmd/build/depot_test.go
Labels: release/new-feature

#4568 Fix compose deployServices ticker loop
  pkg/cmd/stack/deploy.go
Labels: release/bug-fix, run-e2e

#4566 Add command to generate Okteto Manifest JSON Schema
  cmd/generate-schema.go
  go.mod
  go.sum
  main.go
  pkg/externalresource/external_resource.go
  pkg/model/dev.go
  pkg/model/manifest_friendly_err.go
  pkg/model/schema.go
  pkg/model/schema_test.go
  pkg/schema/build.go
  pkg/schema/build_test.go
  pkg/schema/dependencies.go
  pkg/schema/dependencies_test.go
  pkg/schema/deploy.go
  pkg/schema/deploy_test.go
  pkg/schema/destroy.go
  pkg/schema/destroy_test.go
  pkg/schema/dev.go
  pkg/schema/dev_test.go
  pkg/schema/external.go
  pkg/schema/external_test.go
  pkg/schema/forward.go
  pkg/schema/forward_test.go
  pkg/schema/icon.go
  pkg/schema/icon_test.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/schema/test.go
  pkg/schema/test_test.go
  pkg/schema/yaml.go
Labels: release/internal

#4573 Add Okteto JSON schema to repo
  .circleci/config.yml
  schema.json
Labels: release/internal

#4578 [JSON Schema] `dev.environment` multi-type support
  pkg/schema/dev.go
  schema.json
Labels: release/internal

#4575 Add command `validate`
  cmd/validate.go
  main.go
  pkg/errors/errors.go
  pkg/model/manifest.go
  pkg/model/manifest_friendly_err.go
  pkg/model/manifest_friendly_err_test.go
  pkg/model/manifest_test.go
  pkg/schema/schema_test.go
  pkg/schema/yaml.go
Labels: release/new-feature

#4579 Fixed log message format
  pkg/cmd/build/authprovider.go
Labels: release/internal

#4580 Implement use of OKTETO_DEV_PERSISTENT_VOLUME_SIZE
  pkg/model/volumes.go
  pkg/model/volumes_test.go
Labels: release/new-feature

#4558 Unify CLI images
  .circleci/config.yml
  .dockerignore
  Dockerfile
  cmd/up/activate.go
  cmd/up/exec.go
  main.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/config/image.go
  pkg/config/image_test.go
  pkg/constants/constants.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/model/manifest_test.go
  pkg/model/serializer.go
  pkg/model/serializer_test.go
  pkg/model/translation_test.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
  scripts/start.sh
Labels: release/internal, run-e2e

#4582 Added runAsNonRoot field to Json Schema for dev.securityContext property
  pkg/schema/dev.go
  pkg/schema/dev_test.go
  schema.json
Labels: release/internal

#4586 fixes for `make lint`
  .pre-commit-config.yaml
  cmd/context/create.go
  cmd/remoterun/ssh.go
  pkg/schema/build_test.go
  pkg/schema/dev_test.go
  pkg/schema/icon_test.go
  pkg/schema/schema_test.go
  scripts/ci/push-image.sh
  scripts/start.sh
Labels: release/internal

#4584 Remove endpoints from deprecated function resources
  pkg/okteto/endpoint.go
  pkg/okteto/endpoint_test.go
Labels: release/internal

#4588 fix: push image
  scripts/ci/push-image.sh
Labels: release/internal

#4591 Setenv OKTETO_DOMAIN when okteto context use cmd
  cmd/context/use.go
Labels: release/bug-fix

#4572 Update error when image does not exist on `okteto deploy`
  cmd/deploy/deploy.go
  cmd/deploy/remote.go
  pkg/build/buildkit/errors.go
  pkg/build/buildkit/errors_test.go
  pkg/build/buildkit/runner.go
  pkg/cmd/build/depot.go
Labels: release/bug-fix

#4593 Use always user 0 for remote operations to make it work for rootless runner images
  cmd/test/cmd.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/internal, run-e2e

#4581 Update e2e tests once staging.okteto.dev is applied to the new stagin…
  .circleci/config.yml
Labels: release/internal, run-e2e
