Repository okteto/okteto, pull requests merged in 2025-05, with the labels that each got.

#4709 remove upx
  Dockerfile
Labels: release/internal, backport release-3.7

#4711 fix: update SYNCTHING_VERSION to 1.29.6 and add syncthing data volume mounts
  Dockerfile
  pkg/k8s/apps/translate_test.go
  pkg/model/dev.go
  pkg/model/translation_test.go
Labels: release/internal, run-e2e

#4715 Adds the flag for redeploying dependencies in pipeline and preview dependencies.
  cmd/pipeline/deploy.go
  cmd/pipeline/deploy_test.go
  cmd/preview/deploy.go
  internal/test/client/preview.go
  pkg/okteto/pipeline.go
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
  pkg/types/gitdeploy.go
  pkg/types/interface.go
Labels: release/new-feature

#4718 feat: add destroy with dependencies on CLI
  cmd/destroy/destroy.go
  cmd/pipeline/destroy.go
  internal/test/client/pipeline.go
  pkg/okteto/pipeline.go
  pkg/okteto/pipeline_test.go
  pkg/types/interface.go
Labels: release/new-feature

#4722 Fixes #4714. Added output option to namespace list command to specify json or yaml
  cmd/build/command.go
  cmd/deploy/deploy.go
  cmd/namespace/create.go
  cmd/namespace/delete.go
  cmd/namespace/list.go
  cmd/namespace/list_test.go
  cmd/namespace/namespace.go
  cmd/namespace/sleep.go
  cmd/namespace/use.go
  cmd/namespace/wake.go
  cmd/test/cmd.go
  cmd/up/up.go
  main.go
Labels: release/new-feature, run-e2e
