Repository okteto/okteto, pull requests merged in 2025-06, with the labels that each got.

#4733 Fix: fixed error typo
  pkg/errors/errors.go
Labels: release/internal

#4731 fix: wait until sync completes to run services
  cmd/up/activate.go
  cmd/up/devdeployer.go
  cmd/up/devdeployer_test.go
  integration/up/deployment_test.go
  integration/up/exec_test.go
Labels: release/bug-fix, run-e2e

#4732 feat: implement AutoDown functionality with tests
  cmd/up/autodown.go
  cmd/up/autodown_test.go
  cmd/up/pid.go
  cmd/up/types.go
  cmd/up/up.go
Labels: release/new-feature

#4736 Avoid build error messages on okteto test execution
  cmd/test/cmd.go
  pkg/build/buildkit/errors.go
Labels: release/internal
