Repository okteto/okteto, pull requests merged in 2025-04, with the labels that each got.

#4695 pkg(ignore): fix spelling in Go files
  pkg/ignore/multi.go
  pkg/ignore/never.go
  pkg/ignore/oktetoignore_test.go
Labels: release/internal

#4692 Add context command initialization in restart command
  cmd/restart.go
Labels: release/bug-fix

#4701 PROD-343: Change when the divert deploy logic is called to avoid problems when endpoints are defined in the manifest
  cmd/deploy/deploy.go
  cmd/deploy/deploy_test.go
  pkg/deployable/deploy.go
  pkg/deployable/deploy_test.go
Labels: release/bug-fix, run-e2e

#4704 Add git binary for the dockerfile image
  Dockerfile
Labels: release/internal

#4705 Option 2: add spinner forchecking services
  cmd/build/v2/build.go
  cmd/build/v2/smartbuild/hasher.go
  cmd/build/v2/smartbuild/hasher_test.go
  cmd/build/v2/smartbuild/smartbuild.go
  cmd/build/v2/smartbuild/smartbuild_test.go
Labels: release/new-feature

#4706 build(deps): update Helm, Syncthing, and Okteto remote versions
  Dockerfile
Labels: release/internal

#4707 fix: revert SYNCTHING_VERSION to 1.29.4 for compatibility
  Dockerfile
Labels: release/internal, run-e2e, backport release-3.7
