Repository okteto/okteto, pull requests merged in 2025-07, with the labels that each got.

#4741 [TEST] feat: implement nodeSelector and resources inheritance from Kubernetes resources
  go.mod
  go.sum
  pkg/k8s/apps/crud.go
  pkg/k8s/apps/crud_test.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/model/const.go
  pkg/model/dev.go
  pkg/model/dev_test.go
Labels: release/new-feature, okteto-ai-agent-fleets

#4738 Add installation instructions to minimum CLI version error
  cmd/context/create.go
  cmd/utils/upgrade.go
  cmd/version.go
Labels: stale, release/internal

#4743 reduce severity of JSON parsing error log, and skip parsing when the log is empty
  pkg/cmd/build/logger.go
Labels: release/bug-fix

#4748 Add unit test for CreateDev function and fix TargetPort type in Service translation
  pkg/k8s/services/crud_test.go
  pkg/k8s/services/translate.go
Labels: release/bug-fix

#4745 Enhance DestroyPreview functionality to include timeout parameter
  cmd/preview/destroy.go
  internal/test/client/preview.go
  pkg/okteto/preview.go
  pkg/okteto/preview_test.go
  pkg/types/interface.go
Labels: release/new-feature
