Repository okteto/okteto, pull requests merged in 2025-09, with the labels that each got.

#4765 fix: update golangci to v2
  .circleci/config.yml
  .golangci.yml
Labels: release/internal, backport release-3.11

#4773 Add 3 more official pre-commit hooks; update hooks
  .pre-commit-config.yaml
Labels: release/internal

#4778 update remote to new version
  Dockerfile
Labels: release/internal

#4786 update syncthing
  Dockerfile
  pkg/syncthing/install.go
Labels: release/internal

#4779 Change prettier pre-commit to a local hook
  .pre-commit-config.yaml
  .prettierignore
Labels: stale, release/internal

#4785 Fix Cache tests
  cmd/test/cmd.go
  pkg/remote/remote.go
  pkg/remote/remote_test.go
Labels: release/bug-fix
