Repository okteto/okteto, pull requests merged in 2025-02, with the labels that each got.

#4661 Optimize remote executions of deploy and destroy operations when buildkit execution is not needed
  cmd/deploy/remote.go
  cmd/deploy/remote_test.go
  pkg/deployable/deploy.go
  pkg/deployable/deploy_test.go
  pkg/model/manifest.go
  pkg/model/manifest_test.go
Labels: release/new-feature

#4663 fix: cli was not waiting if buildkit not available
  pkg/cmd/build/build.go
Labels: release/bug-fix

#4667 Fine tune codecov configuration
  .codecov.yml
Labels: release/internal

#4664 DEV-859: Updated kubernetes dependencies to 0.31.x
  cmd/logs/stern.go
  go.mod
  go.sum
  main.go
  pkg/cmd/stack/translate.go
  pkg/cmd/stack/translate_test.go
  pkg/k8s/apps/deployments.go
  pkg/k8s/apps/statefulsets.go
  pkg/k8s/apps/translate.go
  pkg/k8s/apps/translate_test.go
  pkg/k8s/deployments/crud.go
  pkg/k8s/deployments/crud_test.go
  pkg/k8s/exec/exec.go
  pkg/k8s/jobs/crud_test.go
  pkg/k8s/pods/pod.go
  pkg/k8s/statefulsets/crud.go
  pkg/k8s/volumes/crud_test.go
  pkg/k8s/volumes/translate.go
  pkg/k8s/volumes/translate_test.go
  pkg/model/dev.go
  pkg/model/manifest_test.go
  pkg/model/serializer_test.go
  pkg/model/stack_serializer_test.go
  pkg/model/translation_test.go
Labels: release/internal, run-e2e

#4672 bump buildkit dependency to 0.19
  go.mod
  go.sum
Labels: release/internal

#4674 fix(ci): specify version for kubernetes-helm installation in CircleCI config
  .circleci/config.yml
Labels: release/internal, run-e2e

#4668 feat: allow proxy protobuff integration
  Dockerfile
  pkg/analytics/proxy.go
  pkg/analytics/proxy_test.go
  pkg/deployable/deploy.go
  pkg/deployable/deploy_test.go
  pkg/deployable/json_translator.go
  pkg/deployable/json_translator_test.go
  pkg/deployable/protobuf_translator.go
  pkg/deployable/protobuf_translator_test.go
  pkg/deployable/proxy.go
  pkg/deployable/proxy_test.go
Labels: release/new-feature, run-e2e

#4671 fix: autodeploy flag on okteto up
  cmd/up/deploy.go
  cmd/up/deploy_test.go
  cmd/up/up.go
  pkg/model/const.go
Labels: release/bug-fix, run-e2e

#4676 fix: count the number of restarts from the deployment instead of total
  pkg/cmd/stack/deploy.go
  pkg/cmd/stack/deploy_test.go
Labels: release/bug-fix

#4677 fix: cves
  Dockerfile
Labels: release/internal
