Repository okteto/okteto, pull requests merged in 2025-03, with the labels that each got.

#4678 Change how test namespace name for e2e tests are generated to avoid conflicts when names are too long
  .circleci/config.yml
  integration/k8s-client.go
  integration/okteto.go
Labels: release/internal, run-e2e

#4679 update buildkit to 0.20.1
  go.mod
  go.sum
  pkg/build/buildkit/opt.go
Labels: release/internal, run-e2e

#4682 add action e2e to okteto test
  integration/actions/test_test.go
Labels: release/internal, run-e2e

#4689 DEV-877: Split ignorer logic for Smart Build into 2 different functions according to the flag, and use a temporary file for the SHA calculation
  pkg/repository/git.go
  pkg/repository/local_git.go
  pkg/repository/local_git_test.go
Labels: release/bug-fix, run-e2e, backport release-3.5

#4691 Avoid to get an stuck channel to send a message to an unbuffered channel when timing out the list untracked files operation
  pkg/repository/git.go
Labels: release/internal, run-e2e

#4686 feat: add depends_on annotation support for services
  pkg/cmd/stack/translate.go
Labels: release/new-feature
